#!/usr/bin/env python3
# Edition No. 045 - 2026-08-26. Prepends 6 articles across 5 desks.
import json, pathlib
C = pathlib.Path("content")
articles = json.loads((C/"articles.json").read_text())
ed = json.loads((C/"editorial.json").read_text())

DATE = "2026-08-26"
for a in articles:
    if a.get("lead"): a["lead"] = False

NEW = []
def art(slug, desk, lead, kicker, minutes, byline, tags, title, dek, body, sources):
    assert len(body) == 5, slug
    assert body[-1].startswith("The desk's view:"), slug
    assert len(dek.split()) <= 40, (slug, len(dek.split()))
    d = {"slug":slug,"desk":desk,"date":DATE,"lead":lead,"kicker":kicker,"minutes":minutes,
         "byline":byline,"tags":tags,"title":title,"dek":dek,"body":body,"sources":sources}
    NEW.append(d); return d

RAP_DOYLE = {"title":"12ct. Diamond Takes Top Spot at Doyle New York Auction (24 August 2026) - Rapaport News","url":"https://rapaport.com/news/12ct-diamond-takes-top-spot-at-doyle-new-york-auction/"}
RAP_ELM = {"title":"Jewel from Queen Elizabeth II's Lady-in-Waiting Sells at Elmwood's (24 August 2026) - Rapaport News","url":"https://rapaport.com/news/jewel-from-queen-elizabeth-iis-lady-in-waiting-sells-at-elmwoods/"}
KIT = {"title":"Gold, Silver, Platinum & Palladium spot prices - Kitco (read 26 August 2026, board timestamp 05:59 ET)","url":"https://www.kitco.com/price/precious-metals"}

# ================= 1. LEAD - auctions - Doyle New York =================
art("one-eighty-percent-on-the-sapphires","auctions",True,"Lead Story - Auctions Desk",5,"The Auctions Desk",
["NUM","VS"],
"$457,700 led Doyle, and an 1890 sapphire pair beat its estimate by 180%",
"A 12.46-carat D VS2 ring took Doyle's Important Jewelry sale at $457,700, 30.8% above its high estimate. Four of the top five lots cleared the book, and the widest margin was a pair of sapphire earrings.",
[
"Doyle's Important Jewelry sale in New York was led by a 12.46-carat diamond ring at $457,700, against a high estimate of $350,000. The stone is a cut-cornered step-cut emerald cut, D colour, VS2 clarity, set between tapered baguette diamonds. Rapaport's report of 24 August, which takes the results from Doyle's own website, puts the whole sale above $8 million and records several jewels selling above their top estimates. On the ring alone that is $107,700 more than the house's own ceiling, or 30.8% above it, this desk's arithmetic on the two published figures. Per carat the ring returned $36,733.55.",
"The multiple is more useful than the margin, and across the top five it does not fall where the headline puts it. A JAR ring from around 1980, carrying a cushion modified brilliant of 5.78 carats, G colour and VS2, with pave-set rounds, made $165,600 against an $80,000 to $120,000 estimate, 1.38 times the high. A Cartier Mahango Panthere necklace of more than 500 round diamonds weighing about 30 carats made $133,850 against $50,000 to $70,000, which is 1.91 times the high. And a pair of antique earrings from 1890, one holding an oval 4-carat Ceylon sapphire and the other an oval 4.17-carat Kashmir sapphire, each ringed by ten old-mine diamonds, made $140,200 against $30,000 to $50,000. That is 2.80 times the high estimate and 180.4% above it, the widest margin in the top five on this desk's calculation.",
"One lot in the five did not beat its book. A Tiffany and Co. Fleurage bracelet, eight round diamonds of 10.80 carats forming the flower centres and 439 smaller rounds totalling 25 carats across the petals and leaves, made $127,500 against an estimate of $100,000 to $150,000. It sold inside the range, 15% below the high. It is also the only lot of the five whose estimate already reached six figures at the top, which is the ordinary pattern rather than a surprise: the lots that beat their books were the ones the house priced conservatively, and the one priced near the level it eventually made did not move. Together the five made $1,024,850, which against a sale of more than $8 million is at most 12.8% of the money.",
"The sapphire result is the one worth carrying, and it needs its limits stated. Kashmir is the scarcest origin in sapphire, and a 4.17-carat Kashmir stone in a period mount is a lot rather than a market. Doyle publishes no origin or treatment detail in the results this desk read, so it cannot be said which laboratory called the origin or whether the stones are unheated, and either fact moves a sapphire price by multiples on its own. What can be said is narrower. The house priced a pair of 1890 sapphire earrings at $30,000 to $50,000 and the room paid $140,200, which is 8.17 carats of sapphire at $17,160 a carat before any allowance for the diamonds or the mount. Whoever set that estimate was reading a different market from the one that arrived.",
"The desk's view: a sale where four of the top five clear their high estimates is not proof of a hot market, it is proof of a cautious estimator, and the two get confused every August. The transferable reading is in which lots ran furthest past the book. It was not the D VS2 diamond, which beat its ceiling by 30.8% and behaved about as a large white stone should in a year when those have been marked down. It was a period pair of coloured stones with an origin that cannot be replaced, and a designer ring where the signature does work no carat weight can. A jeweller pricing estate stock this autumn should note that the diamond in the room performed to expectation and everything scarce or signed performed past it."
],
[RAP_DOYLE,
 {"title":"Bonhams Sydney runs 39 of its first 48 lots away - Carat Capital (25 August 2026)","url":"https://caratcapital.org/a-thirty-nine-of-forty-eight.html"},
])

# ================= 2. auctions - Elmwood's London =================
art("three-times-the-royal-brooch","auctions",False,"Auctions Desk - London",4,"The Auctions Desk",
["NUM","VS"],
"A royal brooch made 23,750 pounds at Elmwood's; a 1927 feather made 75,000",
"The Verdura unicorn brooch from Queen Elizabeth II's lady-in-waiting drew the coverage at Elmwood's 19 August sale. Three other lots sold for more, and a Van Cleef feather brooch made 3.16 times as much.",
[
"Elmwood's Auctioneers sold a Verdura unicorn-head brooch for 23,750 pounds, or $32,400, at its London sale of 19 August, reported by Rapaport on 24 August. The brooch carries about 1.10 carats of diamonds in a pear-shaped fringe, a diamond-set horn and a brilliant-cut stone, under a circular cabochon turquoise crown, and it was made by Fulco di Verdura. Its provenance is why it travelled. It belonged to Virginia Fortune Ryan Ogilvy, dowager countess of Airlie, who was a lady-in-waiting to Queen Elizabeth II for close to fifty years.",
"That is the piece the coverage led with, and it is the cheapest of the four lots the same report names. An Art Deco diamond feather brooch by Van Cleef and Arpels, dated 1927, made 75,000 pounds, or $102,229. An Art Deco Egyptian Revival tiara made 65,000 pounds, or $88,595. A Cartier tutti frutti brooch from around 1940 made 60,000 pounds, or $81,780. The Van Cleef feather made 3.16 times what the royal brooch made, this desk's division of the two figures. A sale headline that puts the palace piece at the front is describing attention rather than price, and the same article carries the numbers that say so.",
"The dollar figures reconcile against a single rate, which is worth checking before any of them is set beside an American result. Dividing each dollar figure by its sterling figure returns 1.36305 on the Van Cleef, 1.36300 on the tiara, 1.36300 on the Cartier and 1.36421 on the Verdura. That is one conversion near $1.363 to the pound applied across the sale, the fourth differing only by rounding on the smallest number, rather than four separately struck prices. The four named lots together make 223,750 pounds, or $305,004. Elmwood's published no total for the sale in the report this desk read, so what share those four represent cannot be stated, and it is not stated here.",
"What the provenance bought is visible if the brooch is priced as jewellery rather than as history. About 1.10 carats of diamonds and a turquoise cabochon, in a signed Verdura mount, returned $29,455 for each carat of diamond content. No parcel of 1.10 carats of small pear and brilliant cut goods approaches that figure anywhere in the trade, so nearly the whole price is the name and the countess, in a proportion this desk cannot split from a single result. The honest reading is that Verdura plus a fifty-year royal household attachment was worth 23,750 pounds on the day, and a 1927 Van Cleef feather with no comparable story attached was worth three times more.",
"The desk's view: royal provenance sells newspapers more reliably than it sells jewellery, and this sale demonstrates it cleanly because both halves of the evidence sit in one report. The lot with the palace connection led every write-up and finished fourth of four on price. The lot that finished first was a signed Art Deco brooch from a house whose 1920s work has been bid up for a decade with no story attached at all. For anyone consigning estate goods this autumn, the practical point is that a documented provenance is worth having and is not worth pricing off. The room that wants the countess is smaller than the room that wants the 1927 Van Cleef."
],
[RAP_ELM,
 {"title":"Thirteen thousand for costume - Carat Capital (8 August 2026)","url":"https://caratcapital.org/a-thirteen-thousand-for-costume.html"},
])

# ================= 3. gemstones - IRGSS Jaipur =================
art("kagem-comes-to-jaipur","gemstones",False,"Gemstones Desk - Jaipur",5,"The Gemstones Desk",
["ACTOR","NUM"],
"Kagem brings rough emeralds to Jaipur, and 60 cutters skip the London room",
"The 13th India Rough Gemstones Sourcing Show opened on 24 August and runs to 11 September. Zambia's Kagem is showing rough emeralds to more than 60 Indian manufacturers who would otherwise bid in London.",
[
"The 13th India Rough Gemstones Sourcing Show opened in Jaipur on 24 August and runs to 11 September, a nineteen-day window, according to the Gem and Jewellery Export Promotion Council's release of 25 August. Kagem Mining Ltd of Zambia is showing rough emeralds. The council puts attendance at more than 60 Indian coloured-gemstone manufacturers and names R.K. Chandan, Commissioner of Customs at Jaipur, as chief guest, with Jeevan Ram Dhaka, Assistant Commissioner of Customs at ACC Jaipur, Yogendra Garg, the council's regional chairman for Rajasthan, and D.P. Khandelwal, convener of its coloured gemstones panel, also present. The stated purpose is to let Indian manufacturers buy rough at source without travelling abroad.",
"Kagem is the part of this worth pricing, and this paper has already priced it. The mine is Gemfields' Zambian emerald operation, 75% owned by the company, with the Industrial Development Corporation of Zambia holding the rest. Its higher-quality rough emerald auction, held in London across May and reported here on 24 July, took $26.8 million, clearing 36 of 37 lots and 183,385 of the 185,135 carats offered at an average of $146.08 a carat, 99% by weight. Across the first half of 2026 Gemfields took $102.9 million from auctions in total, 72% more than the same half of 2025, as this paper reported on 31 July. A London auction room is where those carats have been priced. Jaipur is not that room, and no price from this show has been published.",
"What the show changes is the cost of reaching the goods rather than the cost of the goods. India cuts most of the world's rough colour, and a manufacturer in Jaipur bidding on a Kagem book has until now had to be in London, or represented there, to do it. Removing that removes airfare, visa time and the intermediary's margin for a firm too small to send anyone. It does not remove the currency. This paper noted on 24 July that the Indian rupee had lost roughly 10% against the dollar since September 2025, and Gemfields' own sales management named that weakness as a drag on the trade's largest cutting hub. Rough sold at a Jaipur show is still sold in dollars, and a weaker rupee makes a $146 carat dearer at a Rajasthan bench whether the bench flies to London or walks across the city.",
"What the council did not publish is most of what a trade paper would want. There is no value on the rough shown, no carat weight on offer, no number of lots, no indication whether goods move by tender, by negotiation or not at all during the nineteen days, and no result, because the show does not close until 11 September. The figure of more than 60 manufacturers is the council's own count and is not independently audited. Kagem is the only source-country miner named in the release this desk read. On the evidence available this is a confirmed event with confirmed officials and no confirmed commerce, and it is reported here on that basis.",
"The desk's view: what matters about this show is where it sits in a supply chain, not what it will turn over. Coloured stone rough has been sold to the world from a small number of auction rooms, London chief among them for Gemfields, while the cutting has been done in India. Price discovery and manufacturing have sat on different continents, and a margin has lived in the gap. A source-country miner showing goods inside the cutting hub for nineteen days is that gap narrowing, and most of the 60-plus manufacturers the council counts are firms that would never have bid in London. This desk will look for a result after 11 September. Until there is one, nobody should price this as more than access."
],
[{"title":"GJEPC inaugurates 13th India Rough Gemstones Sourcing Show in Jaipur (25 August 2026) - GJEPC","url":"https://www.gjepc.org/news_detail.php?news=gjepc-inaugurates-13th-india-rough-gemstones-sourcing-show-in-jaipur-1"},
 {"title":"Emeralds hold at $146 a carat; rubies wait their turn - Carat Capital (24 July 2026)","url":"https://caratcapital.org/a-emeralds-hold-at-146.html"},
 {"title":"$102.9 million, up 72%: Gemfields' emeralds cover for its rubies - Carat Capital (31 July 2026)","url":"https://caratcapital.org/a-gemfields-covers-the-ruby.html"},
])

# ================= 4. watches - Fossil Q2 =================
art("watches-were-the-line-that-held","watches",False,"Watches Desk - Filings",5,"The Watches Desk",
["NUM","VS"],
"Fossil's sales fell 4.9%, and watches were the line that held",
"Fossil's quarter to 4 July shows net sales down 4.9% to $209.7 million. Traditional watches fell 1.5%, leathers fell 31.1% and jewellery fell 11.2%. Across six months, traditional watch sales rose.",
[
"Fossil Group's quarterly report for the thirteen weeks to 4 July 2026, filed with the Securities and Exchange Commission on 13 August, puts net sales at $209.7 million against $220.4 million in the comparable quarter to 5 July 2025. That is $10.7 million less, a fall of 4.9% on this desk's arithmetic against the company's own table of net sales by product class. The filing is thirteen days old and is reported here for its composition, which this desk has not seen read anywhere in the trade press, rather than for a top line that has already circulated.",
"The composition inverts the way the number has been described. Traditional watches, much the largest line, fell from $178.4 million to $175.7 million, which is $2.7 million or 1.5%. Smartwatches, now a rounding item, went from $1.40 million to $1.39 million. Total watches fell 1.5%, from $179.8 million to $177.1 million. The two lines that actually fell were leathers, down from $16.9 million to $11.7 million, a drop of $5.3 million or 31.1%, and jewellery, down from $19.4 million to $17.2 million, which is $2.2 million or 11.2%. Leathers alone account for roughly half of the company's entire decline in the quarter, out of a line worth less than 6% of sales.",
"Across six months the watch line is not falling at all. Traditional watch sales for the twenty-six weeks to 4 July came to $364.5 million against $363.1 million a year earlier, which is $1.4 million more, a rise of 0.4%. Total watches were down $0.9 million, or 0.25%, on a base of $368.5 million, which is flat in any practical sense. Half-year net sales still fell 4.2%, from $453.7 million to $434.4 million, because leathers dropped 34.6% and jewellery 10.3% over the same period. A company whose watch revenue is level and whose accessories revenue is down by a third is not a watch story with accessories attached.",
"The mix shift is the part a jeweller should read. Watches were 81.6% of Fossil's quarterly sales a year ago and are 84.5% now, on the company's own percentages. Jewellery slipped from 8.8% to 8.2% of sales and leathers from 7.7% to 5.6%. The watch business is not merely holding, it is taking share of a shrinking company. On the jewellery line itself the reading is plainer and worse: $17.2 million in a quarter, down 11.2%, and $37.4 million across the half, down 10.3%. That is a fashion-jewellery business contracting at roughly a tenth a year while the same firm's watches sit level, which is a data point about the accessory jewellery counter rather than about watches.",
"The desk's view: this filing has been passed around as evidence that the American mid-market watch buyer is in trouble, and the company's own table does not support it. The watch line fell 1.5% in the quarter and rose 0.4% across six months. What is in trouble at Fossil is leather goods, down by a third, and fashion jewellery, down by a tenth, in a season when gold on this paper's own tape has gone from $4,482.20 on 20 August to $4,622.30 this morning, a rise of $140.10 or 3.13%. The transferable point is about substitution at the low end of the counter. When metal runs, the branded fashion-jewellery shelf is the first thing a shopper skips and the watch is close to the last, because a watch is bought as an object and a plated pendant is bought as an impulse. Fossil's quarter reads as that, not as weakness in watches."
],
[{"title":"Fossil Group Form 10-Q, quarterly period ended 4 July 2026 (filed 13 August 2026) - SEC EDGAR","url":"https://www.sec.gov/Archives/edgar/data/883569/000088356926000055/fosl-20260704.htm"},
 {"title":"Net sales for each class of similar products, Fossil Group 10-Q segment table - SEC EDGAR","url":"https://www.sec.gov/Archives/edgar/data/883569/000088356926000055/R51.htm"},
 KIT,
])

# ================= 5. diamonds - Israeli Diamond Institute =================
art("only-the-last-test-was-decisive","diamonds",False,"Diamonds Desk - Detection",4,"The Diamonds Desk",
["NUM","STAKES"],
"Four tests on one rough stone, and only the last one settled it",
"The Israeli Diamond Institute reports a rough diamond that passed visual screening as natural, drew a qualified flag from a CVD detector, and was classified Type IIa by infrared. Single-source, and no weight published.",
[
"The Israeli Diamond Institute's technology department reports that a rough stone submitted to it on Tuesday 18 August, which passed an initial visual screening as ordinary natural rough, was classified as laboratory-grown by infrared spectroscopy. The account appears on the institute's own site, dated 25 August and bylined to Sergey Lazon, a certified gemologist there. This paper carries it as a single-source item. The testing laboratory is describing its own test, no independent outlet has reported it, and no submitting party, dealer or company is named.",
"The sequence matters more than the result. On first examination the stone's recorded data matched expected parameters and it looked externally like natural rough. Under the microscope it showed small clouds and inclusions of the kind natural rough carries, but also minor defects the institute describes as atypical of natural diamond and consistent with CVD growth. A dedicated CVD screening device then returned a preliminary indication of laboratory origin, which the institute qualifies itself, noting that such devices can give ambiguous readings where inclusions are weak. Fourier transform infrared spectroscopy gave what the institute calls an unambiguous result and classified the stone as Type IIa. Four steps, and the institute's own account treats only the fourth as settling anything.",
"Rough is where this is hard, and cut goods are where the trade's defences were built. A polished stone can be screened at speed against a large body of known optical behaviour, and the major laboratories have spent a decade automating that. A rough stone has no facets to read through, its surface is its skin, and the visual cues a sorter relies on, the clouds and included crystals named in this account, are the cues this stone presented correctly. Type IIa is the crux. It is the nitrogen-poor category most laboratory-grown diamond falls into, and the institute's position is that natural origin is difficult to argue for a Type IIa stone with this rough's structure and shape. Type IIa natural rough exists and is prized, which is exactly why a false negative at the sorting table is expensive.",
"What is missing from the account limits how far it can be taken. No carat weight, no measurements, no colour, no price and no country of submission are given, so this desk cannot say whether the stone was a parcel item or a single significant piece, and cannot put a value on what an undetected pass would have cost. The institute also states that the Gemological Institute of America identified a comparable stone days earlier, and attributes that to a report by IDEX Online rather than to the GIA directly. The claim is hedged twice in the original and is carried hedged here. This desk found no English-language trade coverage of the Israeli test and no GIA statement of its own, and neither absence settles anything either way.",
"The desk's view: the useful sentence in this account is the institute's own caveat about its screening device, not the infrared result. A dedicated CVD detector gave a preliminary and qualified answer on a stone that spectroscopy later settled without argument, which is the ordinary state of screening technology described honestly by an operator who owns one. The trade reads instrument marketing as though a flag were a verdict, and buys parcels on the strength of a green light at the sorting table. What this report describes, if it holds, is a rough stone that survived a trained eye and a machine and failed only at spectroscopy. A dealer buying rough on visual screening alone should price that risk in, and should also note that the party describing it is the laboratory that sells the deeper test."
],
[{"title":"Natural rough stone identified as CVD laboratory-grown (Hebrew, 25 August 2026) - Israeli Diamond Institute","url":"https://www.israelidiamond.co.il/%D7%97%D7%93%D7%A9%D7%95%D7%AA-%D7%94%D7%9E%D7%9B%D7%95%D7%9F/%D7%99%D7%94%D7%9C%D7%95%D7%9E%D7%99%D7%9D-%D7%91%D7%99%D7%A9%D7%A8%D7%90%D7%9C/%D7%90%D7%91%D7%9F-%D7%92%D7%9C%D7%9D-%D7%98%D7%91%D7%A2%D7%99%D7%AA-cvd/"},
 {"title":"DNA on the parcel: Provenance Proof marks melee - Carat Capital (25 August 2026)","url":"https://caratcapital.org/a-dna-on-the-parcel.html"},
])

# ================= 6. gold-metals - the tape =================
art("two-sessions-and-twenty-one-sixty","gold-metals",False,"Gold & Metals Desk - The Tape",4,"The Metals Desk",
["NUM","VS"],
"Gold gives back $21.60 in two sessions while silver takes back 0.99%",
"Gold was written back at $4,622.30 this morning, down $11.90 on yesterday's mark and $21.60 below Monday's. Silver went the other way at $68.55. Platinum and palladium held a sixth session.",
[
"This desk re-read all four metals on Kitco at press time, with the board's own quotes timestamped 05:59 New York time on 26 August, and wrote two of them back to the tape. Gold reads $4,622.30 the ounce. TradingEconomics, this paper's standing second page, read $4,623.84 the same morning, a gap of $1.54 or 0.033%, and the two agree. Silver reads $68.55 against TradingEconomics at $68.68, a gap of 13 cents or 0.19%. Both are now the marks of record and both are the numbers printed here. The 05:00 marks they replace were $4,626.00 and $68.462.",
"Gold has given back two sessions running. This paper's mark of record was $4,643.90 on Monday, $4,634.20 on Tuesday and $4,622.30 this morning: down $9.70, then down $11.90, for $21.60 or 0.465% across the two. Kitco's own board shows a larger fall of $35.60, or 0.76%, because it measures against its own previous close rather than against the hour this paper marks each morning, and those are different references rather than a disagreement between sources. The day's range on that board ran $4,615.50 to $4,674.60, so the morning mark sits $6.80 above the session low in a range $59.10 wide.",
"Silver went the other way and has nearly undone yesterday. The mark was $68.74 on Monday, $67.88 on Tuesday and $68.55 this morning, so a fall of 86 cents was followed by a rise of 67 cents, leaving the metal 19 cents or 0.28% below where Monday left it. Against yesterday alone it is up 0.99%. The gold to silver ratio, this desk's division of its own two marks, has narrowed to 67.43 from 68.27 yesterday, with Monday's at 67.56. Two sessions of gold falling while silver held have taken the ratio back to roughly where the week started, which is a smaller statement than either metal's own move suggests.",
"Platinum and palladium are held rather than written, for a sixth consecutive session. Kitco read platinum at $1,856.00 this morning and TradingEconomics at $1,871.40, a gap of $15.40 or 0.83%. Kitco read palladium at $1,321.00 and TradingEconomics at $1,339.50, a gap of $18.50 or 1.40%. Neither gap is inside the band this paper requires before it moves a mark, so the last agreed readings, $1,881.00 and $1,336.00, both set on 21 August, stand. Both were checked against Kitco's own day ranges rather than assumed. Platinum ran $1,846.00 to $1,887.00 today and palladium $1,305.00 to $1,375.00, and each held mark sits inside its range.",
"The desk's view: two down days after a run is a pause, and this desk will not dress it as anything else. The number a bench should carry out of this morning is not gold's direction but its width. A session that had already travelled $59.10 by six in the morning, on a metal that has added $140.10 or 3.13% since 20 August on this paper's own marks, is a session in which the cost of a gram moves more between two customer appointments than the retailer's margin on the finished piece. That is the operational problem and it does not care which way the metal closes. The white metals say the same thing in another register. Two pricing sources sit more than one percent apart on palladium this morning, which is not a quiet market either."
],
[KIT,
 {"title":"Gold - price, chart, historical data (read 26 August 2026) - TradingEconomics","url":"https://tradingeconomics.com/commodity/gold"},
 {"title":"Silver - price, chart, historical data (read 26 August 2026) - TradingEconomics","url":"https://tradingeconomics.com/commodity/silver"},
 {"title":"Platinum - price, chart, historical data (read 26 August 2026) - TradingEconomics","url":"https://tradingeconomics.com/commodity/platinum"},
 {"title":"Palladium - price, chart, historical data (read 26 August 2026) - TradingEconomics","url":"https://tradingeconomics.com/commodity/palladium"},
])

articles[:0] = NEW
(C/"articles.json").write_text(json.dumps(articles, indent=1, ensure_ascii=False))
print("articles now", len(articles), "leads", sum(1 for a in articles if a.get("lead")))
