#!/usr/bin/env python3
# Edition No. 040 - 2026-08-21. Prepends 9 articles + specs.
import json, pathlib
C = pathlib.Path("content")
articles = json.loads((C/"articles.json").read_text())
editorial = json.loads((C/"editorial.json").read_text())

DATE = "2026-08-21"
for a in articles:
    if a.get("lead"): a["lead"] = False

NEW = []
def art(slug, desk, lead, kicker, minutes, byline, tags, title, dek, body, sources):
    d = {"slug":slug,"desk":desk,"date":DATE,"lead":lead,"kicker":kicker,"minutes":minutes,
         "byline":byline,"tags":tags,"title":title,"dek":dek,"body":body,"sources":sources}
    NEW.append(d); return d

KIT = {"title":"Gold, Silver, Platinum & Palladium spot prices - Kitco (21 August 2026, 05:59 EST live board)","url":"https://www.kitco.com/price/precious-metals"}

# ========== 1. LEAD - platinum-takes-the-biggest-move ==========
art("platinum-takes-the-biggest-move","gold-metals",True,"Lead Story · Gold & Metals Desk",5,"The Gold & Metals Desk",
["NUM","VS"],
"Platinum adds 4.56% and takes the tape's biggest move from gold",
"Kitco read gold $4,581.60, silver $69.31, platinum $1,881.00 and palladium $1,336.00 at 05:59 New York. All four are written back, and platinum and palladium come off a one-session hold.",
[
"Kitco's live board at 05:59 New York time read gold at $4,581.60 an ounce, silver at $69.31, platinum at $1,881.00 and palladium at $1,336.00. All four are written back over the 04:58 marks the tape desk filed this morning, and all four are now this paper's marks of record, with the source named and the timestamp new. Against this paper's own marks of 20 August the moves are gold up $99.40 or 2.22%, silver up $2.72 or 4.08%, platinum up $82.00 or 4.56% and palladium up $28.00 or 2.14%. Measured instead on Kitco's own session, the four move the same way: gold up 1.40%, silver up 1.99%, platinum up 2.96%, palladium up 1.75%. Both bases point the same way this morning, which they did not yesterday.",
"The marks being retired are platinum's $1,799.00 and palladium's $1,308.00, both set by this desk at 06:02 on 20 August and held by the tape desk at 04:58 today. That hold was correctly taken. Kitco and TradingEconomics were 0.81% apart on platinum and 1.56% apart on palladium, well outside the band gold and silver cleared, and the two-page rule says a mark nobody can corroborate does not get written. At press time those gaps are still there, at $13.40 or 0.71% on platinum and $21.50 or 1.61% on palladium, and they are disclosed here rather than reconciled. What the disagreement does not support is either held mark. Platinum's $1,799.00 sits below both live readings, $1,881.00 and $1,894.40. Palladium's $1,308.00 sits below both $1,336.00 and $1,357.50. Kitco is taken as the tie-break because it is the board already carrying gold and silver on this tape.",
"Gold and silver each cleared their second page cleanly. TradingEconomics read gold at $4,582.37, seventy-seven cents or 0.017% from the mark printed here, and silver at $69.43, twelve cents or 0.17% away. The gold-to-silver ratio, this desk's division of its own gold mark by its own silver mark on the same board at the same minute, reads 66.10 against 67.31 on 20 August marks: 1.21 points narrower, in a session where silver outran gold by 1.87 points of percentage. At 31.1035 grams to the troy ounce the four marks work out at $147.30 a gram of fine gold, $2.23 a gram of fine silver, $60.48 a gram of fine platinum and $42.95 a gram of fine palladium, all this desk's arithmetic. For a bench repricing stock this morning those are the working numbers, and gold's has added $3.20 a gram in a day.",
"TradingEconomics attributes the move, on both its gold and its silver page, to safe-haven buying through volatility in currency and bond markets and to the Treasury's plan to at least double its long-term debt buybacks, which drove yields and the dollar lower; on gold it adds continued central bank purchasing, particularly from China. Its platinum page adds a tight supply and demand balance, and its palladium page adds lower Russian output and South African processing disruption. The buyback is the same mechanism this paper reported yesterday, dated to the 19 August session, so the driver is not new. The breadth is. Yesterday platinum was the metal on which the two outside pages could not agree even about direction, one printing it down 0.94% and the other up 0.18%. Today all four metals are higher on both pages and on both bases.",
"The desk's view: a rule that retires a stale mark is only worth having if it fires in both directions, and this is the third time in five days it has fired. What is different today is that the metal it fired on is the one this trade watches least. Platinum is a small, thinly quoted market that jewellers buy in grams and price into settings, and it has now added 4.56% against this paper's mark of record after adding 4.23% on 20 August, which is close to nine per cent across two of this paper's sessions. A workshop repricing platinum stock weekly is a week behind that. The gold number is the one that will be written everywhere this morning. The number that changes what something costs to make is the other one."
],
[
 KIT,
 {"title":"Gold - price, chart, historical data, news (read 21 August 2026) - TradingEconomics","url":"https://tradingeconomics.com/commodity/gold"},
 {"title":"Silver - price, chart, historical data, news (read 21 August 2026) - TradingEconomics","url":"https://tradingeconomics.com/commodity/silver"},
 {"title":"Platinum - price, chart, historical data, news (read 21 August 2026) - TradingEconomics","url":"https://tradingeconomics.com/commodity/platinum"},
 {"title":"Palladium - price, chart, historical data, news (read 21 August 2026) - TradingEconomics","url":"https://tradingeconomics.com/commodity/palladium"},
 {"title":"Two held marks come off the tape at once - Carat Capital (20 August 2026)","url":"https://caratcapital.org/a-both-holds-end-at-once.html"},
])

# ========== 2. fifty-nine-years-and-thirty-four-percent ==========
art("fifty-nine-years-and-thirty-four-percent","diamonds",False,"Diamonds Desk · Supply",5,"The Diamonds Desk",
["NUM","STAKES"],
"Finsch closes after 59 years, taking 34% of Petra's revenue with it",
"Creditors approved an asset sale on 7 August and the business rescue found no way to restart mining. Petra is now a one-mine company, and the goods that closed Finsch are the goods lab-grown took.",
[
"Petra Diamonds' Finsch mine in South Africa will not reopen. Business rescue practitioners put a plan to creditors on 7 August 2026 and it passed with the required voting thresholds, and the plan's own conclusion is that no viable outcome exists to resume mining operations. The mine had been in business rescue since 29 May and production had been suspended since June. Finsch generated about 34% of Petra's revenue in fiscal 2025. It began producing in 1967, which makes this the end of 59 years of commercial mining. The report is eleven days old as it prints here and this paper has not previously carried the permanent closure. It runs now because a mine of this size ending is a supply fact that does not expire, and because what this paper last told its readers, on 29 July, was that Finsch was suspended and in rescue.",
"The reason sits in the product mix rather than in the operation. More than 90% of Finsch's output was below two carats, which is precisely the band lab-grown stones have taken and in which natural rough prices have fallen hardest. Petra's own account is that lower diamond prices and a stronger rand overwhelmed the mine's revenue despite what the company described as strong operating performance. A mine can run well and still not clear its costs when the goods it produces are the goods the market has stopped paying for. That is the small-stone squeeze this paper reported against Petra's revenue on 29 July, arriving at its terminal point four weeks later.",
"What happens next is an asset sale, not a care-and-maintenance pause. A secured creditor has provided post-commencement funding to allow limited activity on site, including asset reclamation, and proceeds will be distributed according to the ranking of claims, with that secured creditor's claims, including the post-commencement funding, ranking highest. The distinction between suspension and closure matters to anyone modelling supply. A suspended mine is an option on a higher price, held for nothing, exercisable when the market turns. A mine whose plant is being sold to satisfy a creditor ranking is not, because the capital needed to reopen it would have to be spent a second time.",
"Petra is now a one-mine company. Cullinan carries what remains, and the company's stated direction there is toward larger, higher-value stones, which is the opposite end of the size distribution from the goods that closed Finsch. That is a rational response and it is also an admission: the part of the natural diamond business competing directly with lab-grown at the small end is the part being exited. The whole distance from rescue to closure took ten weeks, from 29 May to the creditors' vote on 7 August, with a market update on 28 July in between.",
"The desk's view: the number that should travel from this is not 59 years, it is 34%. A mine supplying a third of a listed producer's revenue has closed because the stones it produced are worth less than the cost of taking them out of the ground, and nobody bought it as a going concern. This trade has spent three years arguing about whether lab-grown displaces natural at the engagement counter, where the answer is contested and the evidence is survey data. Finsch is what the same argument looks like at the other end of the pipeline, where it is not a preference but an arithmetic, and where a mine that ran well for 59 years is worth more disassembled than running. The next question is which mine with the same size profile follows, and Petra has already answered it for its own book by moving Cullinan up the carat scale."
],
[
 {"title":"Finsch to Close as Small Stone Prices Collapse (10 August 2026) - IDEX Online","url":"https://www.idexonline.com/FullArticle?Id=51333"},
 {"title":"Update on Finsch Business Rescue Process - Petra Diamonds company announcement, Investegate","url":"https://www.investegate.co.uk/announcement/prn/petra-diamonds-ltd-di---pdl/update-on-finsch-business-rescue-process/9711572"},
 {"title":"Finsch closure epitomises slump in natural diamonds (15 August 2026) - TimesLIVE","url":"https://www.timeslive.co.za/news/business/2026-08-15-finsch-closure-epitomises-slump-in-natural-diamonds/"},
 {"title":"Another Diamond Mine Poised to Close - National Jeweler","url":"https://nationaljeweler.com/articles/15218-another-diamond-mine-poised-to-close"},
 {"title":"Petra's revenue caves as the small-stone squeeze bites - Carat Capital (29 July 2026)","url":"https://caratcapital.org/a-petra-caves-at-the-bottom.html"},
])

# ========== 3. sixty-seven-percent-buy-it-for-themselves ==========
art("sixty-seven-percent-buy-it-for-themselves","retail-tech",False,"Retail & Technology Desk · Signet",5,"The Retail & Technology Desk",
["NUM","ACTOR"],
"Zales says 67% of its core shoppers now buy for themselves",
"The Signet banner's new campaign is built on its own finding that two thirds of purchases among core shoppers are self-purchases. Two of its three style stories need no occasion at all, and the imagery includes men.",
[
"Zales has published a number about its own customers that is worth more than the campaign attached to it. Sixty-seven per cent of purchases among its core shoppers were made for themselves, on the retailer's own data, cited in its announcement of a campaign called You Are The Occasion. The campaign's argument is that fine jewellery should not be held back for milestones, and the figure underneath it is the reason the argument is being made now. Zales is a Signet banner, which makes this a reading of the largest specialty jewellery retailer in the United States on its own counter rather than a survey of the category.",
"The campaign is merchandised as three style stories rather than pitched as one message. Everyday Elevated covers tennis bracelets, rivière necklaces, ear stacks and solitaire pendants. Stacking and Layering covers mix-and-match gold chains, bracelets, bands and pendants. Bridal and Engagement is split into four aesthetics named Iconic Classic, Ethereal Romance, Grand Glamour and Modern Muse. Two of the three are built entirely on repeat purchase of pieces that require no occasion, and only the third depends on the event calendar the campaign is arguing against. It runs in store and across digital and social channels.",
"The imagery includes men wearing watches, gold chains and other accessories, which is the part a trade reader should notice. A self-purchase strategy aimed only at women is a change of occasion. A self-purchase strategy that puts men in the frame is a change in the addressable customer. Amanda Rather, Zales' vice president of style and trend brand marketing, framed the intent as helping women \"make their own rules, celebrate themselves.\" That is the same ground the retailer's Own It campaign covered last year, which is the honest way to read this: an iteration on a strategy already in market, now with a number attached, rather than a first move.",
"What a 67% self-purchase rate does to a jewellery business is change three things at once. It breaks the gift calendar's concentration, because a woman buying for herself does not wait for December or February. It moves the price point down and the frequency up, which is why the campaign leads with stacking and layering rather than with a centre stone. And it changes who has to be persuaded in the store, because the person wearing the piece and the person paying for it are the same person, which shortens the sale and removes the reassurance a gift-giver needs before spending someone else's idea of enough.",
"The desk's view: the campaign is advertising and will be judged as advertising, but the 67% is a disclosure and should be read as one. A retailer of Signet's size does not publish a figure about its own mix unless it has decided to reorganise around it, and this one says two thirds of what leaves a Zales counter is not a gift. Almost every convention of this trade was built for the other case: the window displays, the holiday staffing, the discounting rhythm, the bridal-led floor plan. The independent jeweller reading this does not need Zales' campaign. It needs Zales' number, checked against its own till, because if the figure is anywhere near true across the market then a good deal of this industry is merchandising for a customer who has already left the building."
],
[
 {"title":"Zales Wants You to Wear Fine Jewelry Every Day (19 August 2026) - National Jeweler","url":"https://nationaljeweler.com/articles/15240-zales-wants-you-to-wear-fine-jewelry-every-day"},
 {"title":"Zales Celebrates Everyday Moments That Deserve Your Best Jewelry - Signet Jewelers newsroom","url":"https://www.signetjewelers.com/newsroom/brand-news/media-center-details/2026/Zales-Celebrates-Everyday-Moments-That-Deserve-Your-Best-Jewelry/default.aspx"},
 {"title":"Signet gives Zales and Banter to a Mattel executive - Carat Capital (12 August 2026)","url":"https://caratcapital.org/a-zales-goes-to-mattel.html"},
])

# ========== 4. sixty-five-percent-on-a-chip-substrate ==========
art("sixty-five-percent-on-a-chip-substrate","diamonds",False,"Diamonds Desk · Lab-Grown",5,"The Diamonds Desk",
["NUM","VS"],
"China's lab-grown exports rise 65.3% on demand from chipmakers",
"Shanghai Customs data puts first-half lab-grown exports at 1.41 billion yuan, about $210 million. The growth is in thermal substrates for semiconductors, and it arrives while the jewellery reference price falls again.",
[
"China's lab-grown diamond exports rose 65.3% in the first half of 2026 to 1.41 billion yuan, about $210 million, on Shanghai Customs data reported through the Shanghai Diamond Exchange, the country's sole general-trade diamond platform. The dollar conversion implies about 6.71 yuan to the dollar, this desk's arithmetic on the two figures as published and offered as a check on the pair rather than as a currency quotation. The figure is nine days old as it prints here, and it is a half-year total, so it describes January to June rather than the market this morning.",
"The demand is not coming from jewellery. Synthetic diamond is being bought as heat spreaders and substrates in advanced semiconductors, where its thermal conductivity is roughly five times that of copper. The catalyst named in the reporting is Nvidia's announcement in February that its next-generation graphics processors would use a diamond composite material with liquid cooling as their thermal solution. That is a specification decision by a single very large buyer, and a specification decision is the kind of event that reprices an input material for everybody who makes it, not just for the buyer who made it.",
"Eighty per cent of global lab-grown production still goes to jewellery, which is the figure that keeps this in proportion: the industrial share is the minority, and so is the growth rate in absolute terms. But the two markets are supplied by the same reactors. A grower with chemical vapour deposition capacity can point it at gem rough or at a wafer-grade plate, and until this year the jewellery side was the only bidder that mattered. The one-carat lab-grown reference on this paper's tape reads $703 today on CaratRadar, down a dollar on yesterday and down from $705 on 20 August, which is the price signal the jewellery side is currently sending its growers.",
"Those two facts sit awkwardly together, and that is the story. Jewellery demand is telling growers the goods are worth slightly less every week. Semiconductor demand is telling the same growers that a different customer, with a different specification and a far higher tolerance for price, is arriving at 65.3% a year. Capacity that moves to the second customer stops competing with the first. This is the first mechanism anyone has identified that could take lab-grown supply out of the jewellery market without a single grower failing, and it is worth watching precisely because it does not require jewellery demand to recover.",
"The desk's view: the jewellery trade has been waiting for lab-grown prices to find a floor and has assumed the floor would come from demand. It may come from somewhere else entirely. A grower who can sell a plate into a data centre at an industrial specification does not need the engagement counter, and every unit of capacity that leaves is a unit no longer chasing the $703. Two cautions belong on that. Gem-quality growth and wafer-quality growth are not the same process and capacity does not switch overnight. And one half-year of Chinese export data at a small absolute value, $210 million, is a trend line with very few points on it. But the direction is the first genuinely good news the lab-grown supply side has had, and it arrives from an industry that has never once bought a diamond for what it looks like."
],
[
 {"title":"China's Lab-Grown Diamond Exports Jump 65% (12 August 2026) - IDEX Online","url":"https://www.idexonline.com/FullArticle?Id=51338"},
 {"title":"Lab-grown diamond prices, one-carat reference (read 21 August 2026) - CaratRadar","url":"https://caratradar.com/diamond-prices/lab-grown-diamonds/"},
 {"title":"Ninety-six down, eighty up - Carat Capital (19 August 2026)","url":"https://caratcapital.org/a-ninety-six-down-eighty-up.html"},
])

# ========== 5. second-largest-and-no-price ==========
art("second-largest-and-no-price","diamonds",False,"Diamonds Desk · Rough",5,"The Diamonds Desk",
["ACTOR","NUM","GAP"],
"Lucara sold the 2,488-carat Motswedi and published no price",
"The world's second-largest rough diamond has traded at an undisclosed figure, its proceeds folded into a quarter that fell 6% to $41.0 million. The comparison the trade will reach for is nine years old.",
[
"Lucara Diamond has sold the Motswedi, the 2,488-carat rough recovered at its Karowe mine in Botswana in 2024 and the second-largest diamond ever found, and has not said what it was paid. The stone weighed 2,488 carats after cleaning, against the 2,492 carats first reported. The proceeds sit inside the company's second-quarter results rather than being disclosed separately. The report is ten days old as it prints here. This paper has written about the stone twice, in July as a recovery and on 12 August as part of Lucara's quarter, and neither occasion carried a sale.",
"What fills the space where the price should be is a comparison the company itself invited and then qualified. The reference point is the 1,109-carat Lesedi La Rona, also from Karowe, which Graff bought for $53 million in 2017. Lucara's chief executive William Lamb has said the Motswedi \"was not as white as the 1,109-carat Lesedi La Rona\" and contained inclusions that reflected brown tones. That is a chief executive managing an expectation downward before anybody can set it, and it is the most useful thing said about the stone's value in public, because it fixes the direction of the comparison without giving the number.",
"The quarter it lands in is a soft one. Lucara reported $41.0 million of revenue for the second quarter, down 6% on the $43.7 million of a year earlier. The Motswedi's proceeds are inside that figure, which sets a ceiling on the stone rather than a price: whatever it made, it was not enough to lift a quarter above the prior year. That is the only quantitative bound the disclosure permits, and it is worth stating plainly because it is real information. This paper reported on 12 August that Lucara's price per carat rose 24% in the same period while diamond prices generally fell, and the two facts fit together only if the mix was carrying the average.",
"A stone that size has no comparables and now it has no price either. There have been very few diamonds over 2,000 carats in the modern record, and one of them has just traded in the dark. For a trade that prices everything off a reference, the absence reaches past Lucara: the next exceptional rough recovered anywhere will be negotiated against a comparison set with one fewer point in it than it should have. The Lesedi La Rona's $53 million is nine years old and describes a whiter stone in a different market. It is now doing more work than a nine-year-old number should have to do.",
"The desk's view: an undisclosed price is a commercial right and it is also a transfer. The buyer keeps what it paid to itself, the seller avoids publishing a figure that might have disappointed, and the cost lands on every miner who recovers the next great stone and has to argue its value from a comparison set that is thinning. Lucara has recovered more of these than anyone, which makes its silence more consequential than most houses' would be. The quarter tells us the sale was not transformative. The chief executive tells us the stone was not as good as the one that made $53 million. Between those two statements sits a number the market can bracket but cannot read, and bracketing is not pricing."
],
[
 {"title":"Lucara Sells the 2,488-carat Motswedi (11 August 2026) - IDEX Online","url":"https://www.idexonline.com/FullArticle?Id=51336"},
 {"title":"Lucara's price a carat rose 24% as its prices fell - Carat Capital (12 August 2026)","url":"https://caratcapital.org/a-the-mix-did-the-work.html"},
 {"title":"1,305 carats: Karowe finds its tenth thousand-carat diamond - Carat Capital (15 July 2026)","url":"https://caratcapital.org/a-lucara-tenth-thousand-carat.html"},
])

# ========== 6. eight-percent-deferred-to-march ==========
art("eight-percent-deferred-to-march","diamonds",False,"Diamonds Desk · Policy",5,"The Diamonds Desk",
["NUM","ACTOR","STAKES"],
"Russia's 8% rough duty slips to March and costs Alrosa $37.9 million",
"A government resolution published on 11 August moved the export duty from 1 September 2026 to 1 March 2027, so it now starts alongside the cluster decree that ends Russia's open rough market.",
[
"Russia has postponed its 8% export duty on rough diamonds from 1 September 2026 to 1 March 2027, in a government resolution published on 11 August. The duty applies to rough and partially processed diamonds leaving the customs territory of the Eurasian Economic Union. The new date is not arbitrary: it is the date the country's cluster decree takes effect, so the two measures now begin together as one programme rather than six months apart. Alrosa accounts for roughly 90% of Russia's domestic production and is the company the measure is built around.",
"The coverage of the duty is reported two different ways and this desk cannot resolve it, so both are printed. Rapaport and IDEX both describe it as applying to rough above 0.45 carats, including special-size goods weighing more than 10.8 carats. TASS, reporting the resolution itself, describes it as applying to rough weighing between 0.45 and 10.8 carats as well as special sizes. The first reading is a floor with no ceiling. The second is a band. The difference decides whether the largest Russian rough is taxed or exempt, which is not a detail, and it is disclosed here rather than smoothed into whichever version reads more cleanly.",
"The duty is the smaller change and the cluster decree is the larger. Russia is replacing its open rough sales model with a regulated cluster in which miners, meaning Alrosa, must first offer rough and partially processed goods to cutters inside the cluster before selling them anywhere else. That is a right of first refusal written into law over the entire book of the world's largest rough producer. The open market it replaces is the system of direct negotiation and sight-like arrangements through which international traders have bought Russian goods for decades. A tax changes a price. A first-refusal obligation changes who sees the goods at all.",
"The cost figure attached to the duty is 3.12 billion roubles, about $37.9 million, against Alrosa's profit, reported by Rapaport on 11 August. That estimate needs its date carried with it: it was published while the duty was still due to start on 1 September 2026, so it describes an annualised profit impact rather than a bill falling in this financial year, and the deferral pushes the first payment out by six months. This paper reported Alrosa's first-half loss on 6 August and does not restate it here. The duty and the cluster are the new facts; the loss is not.",
"The desk's view: sanctions were supposed to be the thing that separated Russian rough from the world market, and the Russian state is now doing a version of it to itself, deliberately. The cluster decree keeps goods inside the country until domestic cutters have passed on them, and the duty makes exporting whatever is left 8% dearer. Read from Antwerp, Dubai or Surat, the practical question is not what Alrosa pays. It is what reaches the tender at all, and from 1 March 2027 the answer is whatever Russian cutters did not want. That is a change in the quality of what leaves, not only the quantity, and it lands in the same market that has just watched Finsch close for want of buyers at the small end."
],
[
 {"title":"Russian government postpones diamond export duty to March 1, 2027 (11 August 2026) - TASS","url":"https://tass.com/economy/2172005"},
 {"title":"Russia Curbs Open Rough Market, Introduces 8% Export Duty on Diamonds (18 August 2026) - IDEX Online","url":"https://www.idexonline.com/FullArticle?Id=51348"},
 {"title":"Alrosa Skids to Loss as Weak Diamond Demand Persists (11 August 2026) - Rapaport","url":"https://rapaport.com/news/alrosa-skids-to-loss-as-weak-diamond-demand-persists/"},
 {"title":"Alrosa books a $134 million loss and starts idling the pits - Carat Capital (6 August 2026)","url":"https://caratcapital.org/a-alrosa-books-the-loss.html"},
])

# ========== 7. one-january-and-two-million-customers ==========
art("one-january-and-two-million-customers","retail-tech",False,"Retail & Technology Desk · People",4,"The Retail & Technology Desk",
["ACTOR","NUM"],
"Mike Alexander takes Jewelers Mutual on 1 January after Murphy's 12 years",
"Scott Murphy retires at the end of 2026 having turned a specialty insurer into a platform serving more than two million customers. His president since 2025 succeeds him, and he stays on the board.",
[
"Jewelers Mutual will change chief executive on 1 January 2027. Scott Murphy retires at the end of 2026 after twelve years in the job, having joined as chief executive in January 2015, and remains a member of the board. Mike Alexander, the company's president since 2025 and an employee since 2015, succeeds him as president and chief executive. The company announced the transition on 18 August, which gives the trade four months of notice and the incoming chief executive a full quarter of overlap before he owns the decisions.",
"What Murphy hands over is not the company he took. Jewelers Mutual began his tenure as a specialty insurer and ends it as a diversified platform of insurance and non-insurance businesses built on technology and data analytics, serving more than two million customers across the United States and Canada. It has also gone international, entering Australia through the acquisition of Jewellers Loop. For a mutual founded to insure American jewellers, that is a material change in what the institution is, and it happened without the ownership change that usually accompanies a change of that size.",
"Alexander's qualification is continuity rather than contrast: eleven years inside the company, promoted to president in 2025, with responsibility spanning digital transformation, product innovation and market and portfolio expansion, and board seats at Diamonds Do Good and the YMCA of the Fox Cities. Nothing in the announcement signals a change of direction, and the shape of the handover, an internal president elevated while the retiring chief executive stays on the board, is built to signal the opposite. Murphy's own line was that leading the company \"has been the greatest honor of my career.\"",
"The reason this matters beyond one company is what sits underneath it. The independent jeweller's inventory, transit, bench work and cyber exposure are underwritten disproportionately by one mutual that specialises in this trade and very little else. When margins compress, insurance is the line retailers examine first and the one they can least afford to get wrong, and a specialist underwriter is the difference between a claim that is understood and a claim that is argued. A leadership transition at a general insurer is corporate news. At the specialist backstop for an entire retail channel, it is infrastructure.",
"The desk's view: this trade reads people moves as gossip and price moves as news, and on insurance it has the weighting backwards. The substantive fact here is not the retirement. It is that a mutual serving more than two million customers has produced an internal successor with eleven years of context, at a moment when its customer base is under real margin pressure and its own business has expanded into places a 2015 board would not have recognised. Successions like this are noticed only when they go badly. This one has been arranged so that it should not have to be noticed at all, which is the whole point of arranging it four months early."
],
[
 {"title":"Jewelers Mutual CEO Scott Murphy to Retire at the End of 2026; Mike Alexander Named President and CEO (18 August 2026) - PR Newswire","url":"https://www.prnewswire.com/news-releases/jewelers-mutual-ceo-scott-murphy-to-retire-at-the-end-of-2026-mike-alexander-named-president-and-ceo-302854276.html"},
 {"title":"Mike Alexander To Succeed Scott Murphy as Jewelers Mutual CEO (19 August 2026) - National Jeweler","url":"https://nationaljeweler.com/articles/15242-mike-alexander-to-succeed-scott-murphy-as-jewelers-mutual-ceo"},
 {"title":"People Moves: Jewelers Mutual CEO Murphy to Retire at End of 2026 (20 August 2026) - Insurance Journal","url":"https://www.insurancejournal.com/news/midwest/2026/08/20/882329.htm"},
])

# ========== 8. one-twelve-online-one-seventy-five-live ==========
art("one-twelve-online-one-seventy-five-live","auctions",False,"Auctions Desk · Calendar",4,"The Auctions Desk",
["NUM"],
"Bonhams runs 112 lots online and 175 live inside eight days",
"Weekly: Jewelry closes in Los Angeles on 25 August with 112 lots. Modern Native American Art and Jewelry follows live on 26 August with 175. Both counts are read from the house's own listing.",
[
"Bonhams has two jewellery sales open for bidding in Los Angeles inside eight days. Weekly: Jewelry is an online sale running from 18 to 25 August with 112 lots. Modern Native American Art and Jewelry is a live sale on 26 August with 175 lots. Both counts and both dates are read from Bonhams' own Los Angeles listing rather than from a calendar aggregator, which matters because the aggregator entry for this series currently resolves to a February 2025 edition of the same sale. Neither sale has a result yet and this is a calendar note.",
"The weekly online format is the least discussed part of the auction jewellery business and by some distance the most frequent. It runs continuously, it is priced for the volume end rather than the trophy end, and previous editions have carried branded retail names alongside unsigned gold: the February 2025 edition of the same series offered work by Paloma Picasso for Tiffany, Valentin Magro, Gübelin, Gucci and Ippolita, in a band running from about $100 to $4,000, with the strongest lots settling near $5,000. That band is cited here as a description of a prior edition of the series, not of the sale now open, because Bonhams has published no estimate range for the current one that this desk could verify.",
"The live sale on 26 August is a different business. Modern Native American Art and Jewelry is a specialist category with its own collector base, in which named makers carry the value and the jewellery is bought as art rather than as gold. It is also a story this paper has now examined three times. On 17 August this desk killed a version of it that described the sale as a past April auction with a misattributed top lot. Bonhams' own listing now shows a live Los Angeles sale on 26 August 2026 with 175 lots, which settles the date question that killed it. A lot-level estimate reported elsewhere for a Jesse Monongya necklace could not be verified against the house's own catalogue this morning and is therefore not printed here.",
"Set against the other end of the market, the useful thing about both sales is that they will produce numbers. This paper reported on 17 August that Sotheby's had closed three jewellery sales without publishing a total for any of them, one of them thirty-two days earlier. Bonhams runs a weekly online jewellery sale that resolves in seven days and posts what things made. The volume end of the auction business is currently more transparent than the premium end, which is the reverse of what a reader would assume. One correction of this paper's own record belongs here: our Bureau filed the Weekly: Jewelry sale at 48 lots. The house's listing says 112, and the house's figure is the one printed.",
"The desk's view: the auction jewellery market that gets written about is four trophy nights a year, and the auction jewellery market that actually sets prices for ordinary secondhand goods runs every week at a few hundred to a few thousand dollars a lot and is almost never covered. A jeweller taking in an estate lot, or valuing a customer's inherited bracelet, is working against the second market and reading about the first. Two sales, 287 lots, eight days, one city. There is no headline in that and there is a great deal of price information, and it will be published within a week of the hammer, which is more than can currently be said for the houses that sell the famous stones."
],
[
 {"title":"Bonhams Los Angeles, upcoming auctions listing (read 21 August 2026) - Bonhams","url":"https://www.bonhams.com/location/LA/los-angeles/"},
 {"title":"Weekly: Jewelry, Bonhams Los Angeles online sale - Bonhams","url":"https://www.bonhams.com/auction/31003/weekly-jewelry/"},
 {"title":"Two Sotheby's jewel sales closed. Neither has published a number - Carat Capital (17 August 2026)","url":"https://caratcapital.org/a-no-total-for-the-gem-drop.html"},
])

# ========== 9. a-third-door-for-lab-grown ==========
art("a-third-door-for-lab-grown","retail-tech",False,"Retail & Technology Desk · Lab-Grown",4,"The Retail & Technology Desk",
["ACTOR","NUM"],
"Jean Dousset opens a third store, and it sells only lab-grown",
"The Cartier descendant's lab-grown-only brand opened at Westfield Valley Fair in Santa Clara on 13 August, after Los Angeles and New York. Price points are not disclosed. The address is the argument.",
[
"Jean Dousset opened a third store on 13 August, at Westfield Valley Fair in Santa Clara, California, after a Los Angeles flagship and a New York showroom. The brand has sold lab-grown diamonds exclusively since 2023, across engagement rings, eternity bands, necklaces, bracelets, studs and hoops. Three doors is not a chain and the location is the argument: Westfield Valley Fair is a top-tier American luxury mall, and it sits in the middle of Silicon Valley rather than in a jewellery district.",
"The founder is the great-great-grandson of Louis-François Cartier, which is the fact every piece of coverage leads with and the one doing the most commercial work. A lab-grown-only brand's central problem is legitimacy at a price point where the customer is choosing to spend real money on a stone this trade spent a decade calling a substitute. An inherited name is the cheapest available answer to that problem, and the brand uses it explicitly: the Santa Clara boutique carries a screen beside the consultation desk showing views of the Eiffel Tower.",
"The store follows the brand's Dorée collection in its design, with elongated lines, structural forms and an open, gallery-like layout, which is retail language for removing the case-and-counter transaction and replacing it with a consultation. Dousset describes the proposition as pairing lab-grown stones with \"exceptional design and uncompromising craftsmanship,\" which is the standard positioning claim in this category and is not by itself evidence of anything. What is evidence is where the money went. A brand with three stores put its third in a mall whose catchment earns its income from technology.",
"Price points are not disclosed, which limits what can be concluded from any of it. What can be said is that the expansion is happening while the one-carat lab-grown reference this paper's tape carries fell again today, to $703, and while Chinese lab-grown exports to industrial buyers rose 65.3% in the first half. Those three facts together describe a category whose input price keeps falling, whose industrial demand is climbing, and whose retail end is being built out by brands selling design rather than carat weight. A retailer competing on stone price is fully exposed to the first fact. A retailer competing on a name and a gallery is not.",
"The desk's view: the interesting number here is three, not the lineage. Lab-grown retail has mostly been a volume business run at falling prices through online channels and mall kiosks, and the segment nobody has yet proven is the one that charges a premium for a manufactured stone and defends it with design. Dousset is running that experiment slowly, in expensive addresses, with a surname that opens doors most founders have to knock on. Three stores in three years is not an expansion anybody should extrapolate from. It is, however, the version of lab-grown retail that survives if the stone itself keeps getting cheaper, because it was never selling the stone."
],
[
 {"title":"Jean Dousset Opens Third Store (13 August 2026) - National Jeweler","url":"https://nationaljeweler.com/articles/15226-jean-dousset-opens-third-store"},
 {"title":"Westfield Valley Fair boutique - Jean Dousset","url":"https://jeandousset.com/pages/westfield-valley-fair-boutique"},
 {"title":"China's lab-grown exports rise 65.3% on demand from chipmakers - Carat Capital (21 August 2026)","url":"https://caratcapital.org/a-sixty-five-percent-on-a-chip-substrate.html"},
])

articles = NEW + articles
(C/"articles.json").write_text(json.dumps(articles, indent=1, ensure_ascii=False))
print("articles.json: %d new, %d total" % (len(NEW), len(articles)))
