#!/usr/bin/env python3
import json, pathlib
C = pathlib.Path("content")
wire = json.loads((C/"wire.json").read_text())
record = json.loads((C/"record.json").read_text())

wire["date_line"] = "Sunday, August 9, 2026"
wire["edition"] = "Vol. I — No. 030"
wire["tape_ts"] = "7 Aug 2026, 5:00pm New York close · Kitco spot · carried unchanged, no weekend session"
wire["items"] = [
 {"b":"FOUR TIMES THE METAL","t":" — A 22-carat gold Cadbury 'Conundrum' egg made by Garrard & Co. in 1983 sold for £123,500, about $166,600, at Batemans Auctioneers & Valuers in Stamford on 1 August, reported by Forbes on 8 August and called a world auction record for a bejewelled egg of its type. It made close to six times its estimate and about eighteen times the £6,500 it took at its previous sale. The catalogue puts the egg at 323.6 grams of 22-carat gold, roughly $41,400 of bullion at Friday's close, a metal figure derived by this desk. Forbes dates the earlier sale to 2018 and the catalogue entry is dated July 2017; both are carried"},
 {"b":"640,000 OUNCES IN JULY","t":" — The People's Bank of China added 640,000 troy ounces of gold in July, about 19.9 tonnes, the largest single month since October 2023's 740,000 ounces and the twenty-first consecutive month of buying. Holdings reached 76.08 million ounces at the end of July from 75.44 million at the end of June, roughly 2,366 tonnes against 2,346. The gold reserve was valued at $306.35 billion inside total foreign-exchange assets of $3.419 trillion, about 8%. Against this paper's own reporting of 33 tonnes across the whole second quarter, July alone runs at close to double that monthly pace"},
 {"b":"THE TAPE STANDS","t":" — Spot markets did not trade over the weekend and the mark of record is unchanged for a second day: gold $4,341.30, silver $63.46, platinum $1,743.00, palladium $1,357.00, all from Kitco's 5:00pm New York close on Friday 7 August. The Editor re-read Kitco at press time and the page returned the identical Friday close, matching the 05:00 tape exactly, so the tape stands unamended and this edition prints the number the tape carries. Fine gold remains $139.58 a gram"},
 {"b":"938 AGAINST 1,286","t":" — Shanghai Gold Exchange Au99.99 traded at 938 yuan a gram on the morning of 8 August, up 7.53 yuan on the day. Chow Tai Fook listed 24-carat jewellery at 1,286 yuan a gram the same day, Chow Sang Sang 1,285, Lukfook 1,284, Lao Feng Xiang and Lao Miao 1,283, Zhou Liu Fu 1,281 — a spread of 348 yuan, about 37% over the benchmark, with every brand inside five yuan of the others. The same tally puts Shuibei wholesale to top brand counter at 170 yuan a gram. Brands raised counter prices by close to 60 yuan in a single session on 6 August. This is the figure the paper pulled on 7 August for want of verification"},
 {"b":"TURKEY UP 6.9%, AMERICA DOWN 14.8%","t":" — Federation of the Swiss Watch Industry figures for the first half put exports to Turkey at 165.2 million francs, up 6.9% from 154.5 million, the seventeenth largest market. The United States fell 14.8%, Germany 10.5%, China 5.0% and Japan 1.6%, while India rose 31.5%, Mexico 14.9%, South Korea 6.5%, the United Kingdom 5.8%, Hong Kong 3.3% and the UAE 1.6%. France rose 63.4% on a logistics reclassification. Precious-metal watches fell 6.5% and steel 6.5% while bimetallic rose 20.0%; seven million wristwatches shipped, up 2.3%, on a value down 0.6%"},
 {"b":"FORTY-SIX PER CENT CAME BACK","t":" — Kalyan Jewellers reported consolidated revenue of ₹10,589 crore for the June quarter, up 46% from ₹7,268 crore, and net profit of ₹349 crore, up 32%, announced 4 August. India same-store sales grew about 28%, international revenue 35% and the digital business Candere 112%, across 524 showrooms with 354 Kalyan-branded in India. The company says its Shine with India gold-recirculation campaign contributed more than 46% of revenue in the quarter and more than 55% in June alone"},
 {"b":"A COIN MADE OF OLD GOLD","t":" — MMTC-PAMP, India's only LBMA Good Delivery refiner of gold and silver, launched a limited-edition 10-gram commemorative coin on 4 August struck entirely from 999.9-plus recycled gold, capped at 8,000 pieces in assayer-certified packaging with unique identification numbers, unveiled in New Delhi by the Olympic medallist Mirabai Chanu. A refiner selling recycled provenance as a feature rather than disclosing it as a compromise is a change of position, and it lands in the same month a listed retailer reports nearly half its revenue resting on the same metal"},
 {"b":"PNG RETIRES LITESTYLE","t":" — P N Gadgil Jewellers replaced its lightweight diamond line Litestyle with a new brand, YOOU, on 8 August, offered in 9, 14, 18 and 22-carat gold and positioned for everyday rather than occasion wear. It trades through 13 exclusive outlets across Maharashtra and Goa plus shop-in-shop counters in five states, against a stated target of 100 stores by 2030. Sara Tendulkar continues as ambassador. The parent reported first-quarter revenue of ₹2,413 crore, up 41%, and plans roughly 103 store openings across its whole portfolio by the end of the financial year"},
 {"b":"WHAT DID NOT PRINT TODAY","t":" — Six slate items were killed on verification. China's first-half gold demand mix (jewellery down about 30%, bar and coin up about 31%) is a confirmed repeat, published here twice, on 3 August from the World Gold Council and on 7 August from the China Gold Association. A claimed SGE withdrawal figure of 161 tonnes for August traces to LBMA Alchemist issue 111, published October 2023 about August 2023 — a date trap, killed. A claimed PBoC purchase of 2 tonnes in August, a tenth consecutive month, was wrong on figure, month and streak; the verified July print appears above. Titan's first-quarter earnings and Chow Tai Fook's Macau same-store figure are both confirmed repeats. Israel's first-half export figures were dropped: the readings do not reconcile, at $625.7 million polished against $1.77 billion polished for the same half, and the reporting is twelve days old. Gemstones is dark for a fifth consecutive edition and diamonds for a second, the latter on a collapse in reachable sources rather than an empty beat. Sotheby's Arcade Hong Kong closed 6 August and has published no result for a fourth day. UAE retail gold is reported at 523.25 AED a gram for 24-carat on 8 August by one Arabic outlet, carried here with the caveat that three outlets stood AED 7.25 apart on the same session two days earlier. On the diamond lines NAT1 and LGD1 carry unchanged; the lab-grown reference reads $711 on CaratRadar, dated today, against $511 on StoneAlgo dated 7 August, a gap of roughly 39% this desk carries rather than reconciles. RAPI returned 403 for a fifth day and the Zimnisky rough index remains unreadable"},
]
wire["tape"] = [
 {"name":"Gold / oz","code":"XAU","px":"4,341.30","chg":"— unch.","dir":"flat",
  "pts":[15,16,15,16,15,18,19,21,23,23]},
 {"name":"Natural 1ct (RAPI proxy)","code":"NAT1","px":"5,232.00","chg":"— unch.","dir":"flat",
  "pts":[13,13,13,13,13,13,13,13,13,13]},
 {"name":"Lab-grown 1ct wholesale","code":"LGD1","px":"727.00","chg":"— unch.","dir":"flat",
  "pts":[13,13,13,13,13,13,13,13,13,13]},
 {"name":"Platinum / oz","code":"XPT","px":"1,743.00","chg":"— unch.","dir":"flat",
  "pts":[15,17,16,17,18,19,20,22,21,21]},
 {"name":"Silver / oz","code":"XAG","px":"63.46","chg":"— unch.","dir":"flat",
  "pts":[16,16,15,16,17,19,18,22,21,21]},
]
(C/"wire.json").write_text(json.dumps(wire,ensure_ascii=False,indent=1))

# ---- record: prepend into the current week ----
wk = record["weeks"][0]
assert wk["label"] == "This week — August 3", wk["label"]

newent = [
 {"d":"auctions","h":"A 1983 Garrard 'Conundrum' egg makes £123,500, about four times its metal",
  "t":"A 22-carat gold Cadbury's 'Conundrum' egg, named Cuckoo Cuckoo and made by Garrard & Co. of London in 1983, sold for £123,500, about $166,600, at Batemans Auctioneers & Valuers in Stamford, Lincolnshire on 1 August 2026. Forbes reported the result on 8 August and the auction house describes it as a world auction record for a bejewelled egg of its type. The price is close to six times the pre-sale estimate and about eighteen times the £6,500 the egg fetched at its previous appearance; Forbes dates that earlier sale to 2018 while the Batemans catalogue entry for the same lot is dated July 2017, and this paper carries both readings rather than resolving them. The catalogue puts the egg at 323.6 grams of 22-carat gold, engraved and enamelled in translucent green, blue, orange and white with a cat, a weather vane, stars, mice, a castle and a treasure hunter finding a golden egg. At 91.7% fineness that is roughly 296.6 grams, or 9.54 troy ounces, of pure gold, worth about $41,400 at the $4,341.30 an ounce this paper's tape carries from Kitco's 5:00pm New York close on 7 August. That metal figure is derived by this desk from the stated weight and fineness and is not published by any source. The egg was one of twelve individually designed 22-carat eggs commissioned by Cadbury's in 1983 for a nationwide treasure hunt, with Perspex caskets buried across the United Kingdom each holding a clue to one egg; a thirteenth was made in secret. Greg Bateman, managing director at Batemans, called the eggs a fascinating piece of British cultural history.",
  "s":"Forbes / Batemans catalogue via the-saleroom / Kitco"},
 {"d":"gold-metals","h":"The PBoC adds 640,000 ounces in July, its largest month since October 2023",
  "t":"The People's Bank of China increased its official gold reserves by 640,000 troy ounces, about 19.9 metric tonnes, during July 2026, published with the monthly reserve data on 7 August. Holdings rose to 76.08 million troy ounces at the end of July from 75.44 million at the end of June, roughly 2,366 tonnes against 2,346. It was the twenty-first consecutive month in which the bank reported a purchase and the largest single-month addition since the 740,000 ounces recorded in October 2023. The gold reserve was valued at $306.35 billion against $303.72 billion a month earlier, within total official foreign-exchange assets of $3.419 trillion, up from $3.416 trillion, putting gold at about 8% of the reserve. Set against this paper's reporting of 2 August, which carried World Gold Council figures showing central banks buying 289 tonnes in the second quarter, up 62%, with China taking 33 tonnes across those three months, July alone runs at close to double China's second-quarter monthly pace. The same World Gold Council data put first-half central-bank demand at 345 tonnes, the smallest first half since 2022's 241 tonnes, after a first quarter revised down to 57 tonnes. July was also the month gold closed at $4,041.70, up about half a per cent and its first monthly gain since February, so the increase in pace came into a market that had barely moved. At the $4,341.30 an ounce carried on this paper's tape, 640,000 ounces is worth about $2.78 billion, a figure derived by this desk from the published ounce count rather than reported.",
  "s":"PBoC monthly reserve data via The Private Banker and Bloomberg / World Gold Council / Kitco"},
 {"d":"gold-metals","h":"Shanghai brand counters run 348 yuan a gram above the exchange benchmark",
  "t":"The Shanghai Gold Exchange's Au99.99 contract traded at 938 yuan a gram on the morning of 8 August 2026, up 7.53 yuan from the previous close. On the same day, Chinese brand counter prices for 24-carat jewellery stood at 1,286 yuan a gram at Chow Tai Fook, 1,285 at Chow Sang Sang, 1,284 at Lukfook, 1,283 at Lao Feng Xiang and Lao Miao, and 1,281 at Zhou Liu Fu — every major brand inside five yuan of the others and roughly 37% above the exchange benchmark, a spread of 348 yuan a gram. The same Mandarin financial-press tally puts the distance from the Shuibei wholesale price in Shenzhen, where most Chinese gold jewellery is made and traded, to the highest brand counter price at 170 yuan a gram. On 6 August the major brands raised counter prices by close to 60 yuan a gram in a single session, as reported by Sina Finance, against a far smaller move in the benchmark, reversing the pattern in which brand list prices lagged the metal. This paper declined to print a Chinese brand-counter figure on 7 August because two independent reads of that day's price stood at 1,240 and 1,297 yuan a gram, the main aggregator returned empty price cells and a second site failed on its certificate; the 8 August table, cross-checked against two independent brand-price trackers, resolves it. The demand backdrop, previously filed by this paper on 7 August, is China Gold Association half-year figures putting gold jewellery consumption at 132.13 tonnes, down 33.88%, against bar and coin demand of 339.34 tonnes, up 28.42%.",
  "s":"Tencent News (Mandarin) / Sina Finance / China Gold Association via Carat Capital"},
 {"d":"watches","h":"Swiss exports to Turkey rise 6.9% while the United States falls 14.8% across the half",
  "t":"Federation of the Swiss Watch Industry figures for the first half of 2026 put exports to Turkey at 165.2 million Swiss francs, up 6.9% from 154.5 million in the first half of 2025 and 145.2 million in 2024, with Turkey the seventeenth largest market for Swiss watches. The figures were carried by the Turkish press on 6 August, sourced to the federation. Worldwide exports for the half came to 12.8 billion francs, down 0.7%, a total this paper filed on 21 July when the federation published it. The federation's country table shows the United States, the largest single market, down 14.8% for the half though still 2.6% ahead across two years; Germany down 10.5%, China down 5.0% and Japan down 1.6%. Against those, India rose 31.5%, Mexico 14.9%, South Korea 6.5%, the United Kingdom 5.8%, Hong Kong 3.3%, Singapore 2.2% and the United Arab Emirates 1.6%. France rose 63.4%, which the federation attributes to a logistics reclassification rather than to demand. By material, watches in precious metals fell 6.5% and steel watches fell 6.5%, while bimetallic models rose 20.0% and other metals rose 14.4%. Mechanical watches priced under 500 francs at export rose 23.8% while the 500 to 3,000 franc band fell 5.7%. Seven million wristwatches shipped across the half, up 2.3% in units, on a wristwatch value of 12.2 billion francs, down 0.6%. Turkey's 165.2 million francs represents about 1.3% of the half's total, a share derived by this desk from the published figures rather than published by the federation. This is the watches desk's first article since 4 August, after four consecutive dark editions.",
  "s":"Federation of the Swiss Watch Industry / Turkish Minute / Hürriyet Daily News"},
 {"d":"retail-tech","h":"More than 46% of Kalyan's quarterly revenue came in as recycled gold",
  "t":"Kalyan Jewellers reported consolidated revenue from operations of ₹10,589 crore for the quarter to 30 June 2026, up 46% from ₹7,268 crore a year earlier, and consolidated net profit of ₹349 crore, up 32%. The results were announced on 4 August 2026. Same-store sales in India grew about 28%, international revenue rose 35%, and Candere, the group's digital business, grew 112%. The company operates 524 showrooms worldwide, 354 of them Kalyan-branded in India. The company states that its gold-recirculation campaign, run under the name Shine with India, contributed more than 46% of revenue across the quarter and more than 55% in the month of June alone, reducing its reliance on imported gold. In the same week, MMTC-PAMP, India's only LBMA Good Delivery refiner of gold and silver, launched a limited-edition 10-gram commemorative coin on 4 August struck entirely from 999.9-plus recycled gold, capped at 8,000 pieces in assayer-certified packaging carrying unique identification numbers, unveiled in New Delhi by the Olympic silver medallist Mirabai Chanu. The volume backdrop, previously filed by this paper, is Indian gold jewellery demand down 15% by weight in the second quarter to 75.1 tonnes, its lowest second quarter since the pandemic, against a value up about 50%. A 46% revenue rise against a national tonnage down 15% therefore combines a price effect, an exchange effect and a store-count effect; the company's own same-store figure of about 28% is the comparable measure.",
  "s":"Business Standard Capital Market / Indian Television / The Tribune"},
 {"d":"retail-tech","h":"P N Gadgil retires Litestyle for YOOU and sets a 100-store target for 2030",
  "t":"P N Gadgil Jewellers announced on 8 August 2026 that it has replaced Litestyle by PNG, its lightweight diamond jewellery line, with a new brand called YOOU, offered in 9, 14, 18 and 22-carat gold and positioned for everyday rather than occasion wear. The line currently trades through 13 exclusive brand outlets across Maharashtra and Goa plus shop-in-shop counters across five states, against a stated target of 100 stores by 2030. Sara Tendulkar continues as brand ambassador, carried over from Litestyle. Saurabh Gadgil, chairman and managing director, described the brand as built for contemporary collections and everyday wear. The parent company reported first-quarter revenue of ₹2,413 crore, up 41% year on year, and has said it plans to open roughly 103 stores across its whole portfolio by the end of the current financial year. The segment context previously filed by this paper is that lightweight, low-carat diamond jewellery aimed at everyday wear is the most exposed category to lab-grown substitution: on 7 August this paper reported lab-grown diamond studs selling at $29.99 in the American mall channel. Two Indian jewellers filed news in the same week and both point the same way, Kalyan sourcing more than 46% of revenue from recycled gold and P N Gadgil building a chain around 9 to 18-carat pieces bought without an occasion, both responses to a gold price that has made the traditional heavy-gold Indian purchase unaffordable at the old frequency.",
  "s":"ScanX / InvestyWise / Carat Capital archive"},
]
wk["entries"] = newent + wk["entries"]
record["updated"] = "9 Aug 2026"
(C/"record.json").write_text(json.dumps(record,ensure_ascii=False,indent=1))
print("OK: wire No. 030 written, %d record entries prepended into '%s' (now %d)" % (len(newent), wk["label"], len(wk["entries"])))
