#!/usr/bin/env python3
import json, pathlib
C = pathlib.Path("content")
wire = json.loads((C/"wire.json").read_text())
record = json.loads((C/"record.json").read_text())

wire["date_line"] = "Monday, August 10, 2026"
wire["edition"] = "Vol. I — No. 031"
wire["tape_ts"] = "10 Aug 2026, 5:57am New York · Kitco live board · Editor's press-time read, written back to the tape"
wire["items"] = [
 {"b":"TWO DUBAI RATES, 2% APART","t":" — LivePriceOfGold's Dubai board, timestamped 10 August at 10:07 UTC, reads AED 512.45 a gram for 24-carat gold and AED 470.43 for 22-carat. Goodreturns' Dubai page, dated the same day, reads AED 523.25 and AED 484.50, a gap of 2.11% and 2.99% respectively, both derived by this desk. The peg arithmetic on Kitco spot at $4,341.40 an ounce gives AED 512.59 a gram, which puts LivePriceOfGold on the raw-metal lane, AED 0.14 away, and Goodreturns AED 10.66 above it. Neither page is wrong; they publish different quantities under one label. Goodreturns' page stepped up AED 13.25 between 7 and 8 August against a metal move of AED 3.13 and has held flat for three days since"},
 {"b":"THE EDITOR'S READ IS THE MARK","t":" — Under the one-price rule, the tape carries this desk's 5:57am New York reading of Kitco's live board on 10 August: gold $4,341.40, up $0.10 or 0.00% against Friday 7 August's close; silver $63.99, up 52.8 cents or 0.83%; platinum $1,737.00, down $6.00 or 0.34%; palladium $1,340.00, down $17.00 or 1.25%. The 4:58am tape had read $4,345.40, $64.06, $1,739.00 and $1,342.00; every previous close matches, so this is one open session moving between two reads and the fresher verified reading has been written back. Fine gold is $139.58 a gram and the gold-to-silver ratio narrows to 67.84 from 68.41"},
 {"b":"5.9 MILLION SILVER PIECES","t":" — India hallmarked 5.9 million silver articles in the 2025-26 financial year against 3.2 million the year before, an increase of about 84% derived by this desk, on Bureau of Indian Standards figures disclosed 9 August. About 230 recognised assaying and hallmarking centres handle silver testing; the recognised laboratory network has gone from 147 in 2014 to 440 and government-empanelled laboratories from 24 to 350, against ten standalone bureau laboratories and roughly 270,000 samples tested. Silver hallmarking has been voluntary since 2005 and no mandatory date has been set, though the unique identification number the regime would need was introduced for silver in September 2025. The bureau names the cause as consumers moving into silver because gold has become unaffordable"},
 {"b":"ETSY CUTS 220","t":" — Etsy is removing about 220 roles, roughly 12% of its marketplace workforce, mainly from product and engineering, at an estimated $35 million charge booked in the third quarter, leaving about 1,600 employees. The plan was disclosed 6 August alongside second-quarter revenue of $668.3 million, up 6.2% and ahead of a $646.1 million consensus, gross merchandise sales from continuing operations of $2.58 billion, Etsy-only GMS up 7.5%, a take rate of 25.9%, active sellers up 5.9% to 5.7 million and active buyers down 0.4% to 87.0 million. The company says the cut is neither a cost-reduction exercise nor related to artificial intelligence. Jewellery and personal accessories is one of the six largest categories by GMS in Etsy's own filings"},
 {"b":"QVC OUT IN 113 DAYS","t":" — QVC Group formally exited Chapter 11 on 7 August, 113 days after filing on 16 April, a count derived by this desk from the two dates, having removed more than $5 billion of debt. It issued $1.2 billion of take-back notes due 2032 at a 10% coupon and secured a $600 million asset-based lending facility, with the equity approved for Nasdaq trading under QVCG. David Rawlinson, chief executive since 2021, stepped down; Mike George returns as interim chief executive and board chair alongside a new eight-member board. Fine and fashion jewellery has been among the top-selling categories on the platform"},
 {"b":"PANDORA'S THIRD SEAT","t":" — Pandora named Paulo Garcia chief financial officer on 6 August. He joins 1 October and takes the role 1 December, succeeding Anders Boyer, who retires 30 November after more than fourteen years and stays until 31 March 2027 to hand over. Garcia arrives from the chief financial officer's seat at Walmart de Mexico y Centroamerica, a listed subsidiary with about $50 billion of revenue and 240,000 employees, and was previously chief financial officer for Europe and Indonesia at Ahold Delhaize and before that at Unilever. With Berta de Pablos-Barbier taking office as chief executive on 1 January and Andre Branch named North America president, three of the top seats at the largest jewellery company in the world by units turn over inside twelve months, and none of the three arrives from jewellery"},
 {"b":"THE SEVEN AUGUST SPREAD, RESOLVED","t":" — This paper printed three UAE retail gold readings for the 7 August session and declined to choose between them: Khaleej Times at AED 517.50 a gram, one bureau desk at AED 510.25 and another at AED 514.00. The peg arithmetic for that session gives AED 509.42, which places the 510.25 on the raw-metal lane and the 517.50 on the counter lane. The divergence this desk carried unresolved across three editions was a category error rather than a data error. The correction of understanding is recorded here rather than left in the archive; no published figure was wrong, and none has been altered"},
 {"b":"DIAMONDS DARK ON VERIFICATION, NOT ON ABSENCE","t":" — The rough desk filed seven items and none survived the archive check: De Beers' 88% second-quarter production rise ran here 24 July, Gem Diamonds' Letšeng half-year ran 29 July, the RapNet index rebound ran 4 August, Antwerp's half-year ran 8 August, the Belgium-India tariff gap has run five times since 8 July, and a lab-grown stabilisation figure was recycled from sourcing this paper already rejected on 31 July. A seventh, an Alrosa price signal, traces to an article dated 26 March 2026 and filed as August news. The Editor's own diamonds sweep returned only stale or already-published material. Third consecutive dark diamonds edition"},
 {"b":"WHAT ELSE DID NOT PRINT TODAY","t":" — Three more slate items were killed on date. Brilliant Earth's second quarter, ranked the day's strongest item, published here on 7 August as twenty-two-thirty-eight-an-order with the identical $115.1 million, 5.7% rise, $2,238 average order value, 57.9% gross margin and $459-462 million guidance; killed as a repeat. Pandora's lab-grown expansion to Spain and Italy carries a release date of 25 June with the Barcelona and Milan flagships opened 12 and 26 June, and the Pandora Wonders platform with Harry Lambert launched 8-9 July at Paris Couture Week; the company's newsroom index lists both under today's date, which is a page artefact rather than a publication date. Van Cleef & Arpels' first Madrid boutique opened 11 April, four months before the 7 August press release that surfaced it. The Chinese brand-counter spread was pulled: the aggregators returned stale or empty cells again and this desk will not print a counter price it cannot verify. Gemstones is dark for a sixth consecutive edition, watches and auctions for the first. Sotheby's Arcade Hong Kong closed 6 August and has published no result for a fifth day. RAPI returned 403 for a sixth day and the Zimnisky rough index remains unreadable; NAT1 and LGD1 both carry unchanged"},
]
wire["tape"] = [
 {"name":"Gold / oz","code":"XAU","px":"4,341.40","chg":"— +0.00%","dir":"flat",
  "pts":[16,15,16,15,18,19,21,23,23,23]},
 {"name":"Natural 1ct (RAPI proxy)","code":"NAT1","px":"5,232.00","chg":"— unch.","dir":"flat",
  "pts":[13,13,13,13,13,13,13,13,13,13]},
 {"name":"Lab-grown 1ct wholesale","code":"LGD1","px":"727.00","chg":"— unch.","dir":"flat",
  "pts":[13,13,13,13,13,13,13,13,13,13]},
 {"name":"Platinum / oz","code":"XPT","px":"1,737.00","chg":"▼ −0.34%","dir":"down",
  "pts":[17,16,17,18,19,20,22,21,21,20]},
 {"name":"Silver / oz","code":"XAG","px":"63.99","chg":"▲ +0.83%","dir":"up",
  "pts":[16,15,16,17,19,18,22,21,21,22]},
]
(C/"wire.json").write_text(json.dumps(wire,ensure_ascii=False,indent=1))

# ---- record: new week at the top (Monday rollover) ----
old = record["weeks"][0]
assert old["label"] == "This week — August 3", old["label"]
old["label"] = "Week of August 3"

newent = [
 {"d":"gold-metals","h":"Two Dubai gold pages read 2.11% apart on the same morning, and neither is wrong",
  "t":"On 10 August 2026 two of the most widely quoted Dubai gold pages published materially different rates for the same metal on the same day. LivePriceOfGold's Dubai board, timestamped 10 August at 10:07 UTC, read AED 512.45 a gram for 24-carat gold, AED 470.43 for 22-carat, AED 448.40 for 21-carat and AED 384.34 for 18-carat, and states on the page that it prints a raw gold rate to which commission and labour charges are added. Goodreturns' Dubai page, dated the same day, read AED 523.25 for 24-carat and AED 484.50 for 22-carat, reporting no change against 9 August. The gaps are 2.11% on the 24-carat line and 2.99% on the 22-carat line, both derived by this desk from the two published figures. Kitco's live board at 5:57am New York time on 10 August put gold at $4,341.40 an ounce, which is $139.58 a gram at 31.1035 grams to the troy ounce and AED 512.59 a gram at the dirham's fixed peg of 3.6725 to the dollar; both conversions are this desk's arithmetic and are published by no source. That places LivePriceOfGold AED 0.14 from the raw-metal figure and Goodreturns AED 10.66 above it. Goodreturns' own ten-day table runs AED 485.25 on 1 August, 487.25 on the 2nd and 3rd, 485.50 on the 4th, 492.25 on the 5th, 510.25 on the 6th, 510.50 on the 7th, 523.75 on the 8th and 523.25 on the 9th and 10th: a step of AED 13.25 between 7 and 8 August against a metal move of AED 3.13 over the same span, then three flat days while spot continued to move. Read against this, the three UAE readings this paper printed for the 7 August session without choosing between them, Khaleej Times at AED 517.50, one bureau desk at AED 510.25 and another at AED 514.00, sit on two different lanes rather than representing three attempts at one figure; the peg arithmetic for 7 August gives AED 509.42.",
  "s":"Kitco / LivePriceOfGold / Goodreturns / Carat Capital arithmetic at the AED peg"},
 {"d":"gold-metals","h":"India hallmarked 5.9 million silver articles in FY2025-26, nearly double the year before",
  "t":"The Bureau of Indian Standards disclosed on 9 August 2026 that the volume of hallmarked silver articles in India rose to 5.9 million pieces in the 2025-26 financial year from 3.2 million in 2024-25, an increase of about 84% derived by this desk from the two published counts, and set out a plan to scale up testing and certification capacity to match. The bureau attributes the rise to consumers moving into silver as gold prices have risen beyond reach. About 230 bureau-recognised assaying and hallmarking centres currently handle silver testing across the country. The bureau's recognised laboratory network has grown from 147 in 2014 to 440, and government-empanelled laboratories from 24 to 350, against ten standalone bureau laboratories and roughly 270,000 product samples tested; the bureau holds about 700 mandatory standards out of 23,000 in total. Nishat S Haque, deputy director general for laboratories, said the referral and assay laboratory expansion would run across the next two years. Gold surveillance remains in-house while silver testing is outsourced to the recognised centres as capacity is built. Silver hallmarking has been voluntary in India since 2005 and no timeline has been announced for making it mandatory, so the 5.9 million figure counts articles voluntarily submitted rather than total production. A hallmark unique identification number for silver articles was introduced in September 2025. The demand backdrop previously filed by this paper is Indian gold jewellery demand down 15% by weight in the second quarter to 75.1 tonnes, its lowest second quarter since the pandemic, and Kalyan Jewellers taking more than 46% of June-quarter revenue in recycled metal.",
  "s":"Bureau of Indian Standards via Business Today, Business Standard and The Daily Pioneer"},
 {"d":"retail-tech","h":"Etsy cuts 220 roles from product and engineering in a quarter it beat",
  "t":"Etsy disclosed on 6 August 2026 a restructuring removing approximately 220 roles, about 12% of its marketplace workforce, falling mainly on the product and engineering organisation, at an estimated charge of about $35 million, primarily severance and benefits, to be booked in the third quarter of 2026 and completed within it. Approximately 1,600 employees remain. The company stated that the reduction is not a cost-cutting measure and is not related to artificial intelligence, describing the intent as flatter teams with wider remits, fewer handoffs and quicker decisions. The plan was announced alongside second-quarter results for the period ended 30 June 2026: revenue of $668.3 million, up 6.2% year on year against a FactSet consensus of $646.1 million; gross merchandise sales from continuing operations of $2.58 billion, with Etsy-only gross merchandise sales up 7.5%; a revenue take rate of 25.9%; active sellers up 5.9% to 5.7 million; and active buyers down 0.4% to 87.0 million. The reported net loss of $46.7 million is driven by $161 million of losses on discontinued Depop operations rather than by the core marketplace. Kruti Patel Goyal took the chief executive role earlier in 2026. Wedbush read the reduction as supportive of the gross merchandise sales trend. Jewellery and personal accessories is one of the six largest categories by gross merchandise sales in Etsy's own filings; third-party estimates place it near 30% of the platform total, a figure this desk carries as an outside estimate because Etsy does not publish a category split.",
  "s":"Etsy Q2 2026 Form 10-Q / Reuters / Shopifreaks / MarketScreener"},
 {"d":"retail-tech","h":"QVC Group leaves Chapter 11 in 113 days having cut more than $5 billion of debt",
  "t":"QVC Group formally emerged from Chapter 11 protection on 7 August 2026, having filed on 16 April 2026, a span of 113 days derived by this desk from the two dates. The restructuring removed more than $5 billion of debt. As part of the exit the company issued $1.2 billion of take-back notes due 2032 carrying a 10% coupon, disclosed in a regulatory filing, and secured a $600 million asset-based lending facility; the equity was approved for trading on Nasdaq under the ticker QVCG. David Rawlinson, chief executive since 2021, stepped down at the exit and was succeeded by Mike George, who previously ran QVC for more than a decade, as interim chief executive officer and board chair with immediate effect, alongside a newly appointed eight-member board. The company entered court with a pre-negotiated restructuring plan intended to compress the timetable, and the plan received judicial approval in July before the exit closed. Fine and fashion jewellery has been among the top-selling categories on the QVC platform, making the outcome directly relevant to suppliers who use long-form television demonstration as a volume channel. Alex Hennick, president and chief executive of A.D. Hennick & Associates, said the company still has brand recognition, loyal customers and strong vendor relationships. The 10% coupon on the new paper is the credit market's price for the business after the debt reduction and is carried here as the material figure alongside the headline cut.",
  "s":"JCK / Retail Dive / Bloomberg / PYMNTS"},
 {"d":"retail-tech","h":"Pandora names Paulo Garcia chief financial officer, the third top seat to turn in a year",
  "t":"Pandora announced on 6 August 2026 the appointment of Paulo Garcia as chief financial officer. Garcia joins the company on 1 October 2026 and assumes the role on 1 December 2026, succeeding Anders Boyer, who retires on 30 November 2026 after more than fourteen years with the company and remains until 31 March 2027 to support the handover. Garcia is a Portuguese national with twenty-five years of international executive experience across Europe and Latin America. He joins from the chief financial officer's role at Walmart de Mexico y Centroamerica, a separately listed subsidiary with about $50 billion of revenue and 240,000 employees, and was previously chief financial officer for Europe and Indonesia at Ahold Delhaize and before that at Unilever. The appointment completes a turnover of three senior seats inside twelve months at the largest jewellery company in the world by units: Berta de Pablos-Barbier takes office as chief executive on 1 January 2027, and Andre Branch was named president of the North America cluster in an announcement this paper filed on 5 August 2026 as pandora-fills-the-seat. None of the three arrives from the jewellery trade. Pandora's own published figures put the company at around 7,000 points of sale globally including more than 2,800 concept stores, and approximately 39,000 employees. The company sells lab-grown diamonds in eight markets, having added Spain and Italy in June 2026 with flagship stores in Barcelona and Milan.",
  "s":"Pandora Group / WWD / FashionUnited / Carat Capital archive"},
]
record["weeks"].insert(0, {"label":"This week — August 10","entries":newent})
record["updated"] = "10 Aug 2026"
(C/"record.json").write_text(json.dumps(record,ensure_ascii=False,indent=1))
print("wire No.031 written; new record week with", len(newent), "entries; weeks now", len(record["weeks"]))
