#!/usr/bin/env python3
import json, pathlib
C = pathlib.Path("content")
wire = json.loads((C/"wire.json").read_text())
record = json.loads((C/"record.json").read_text())

wire["date_line"] = "Thursday, August 13, 2026"
wire["edition"] = "Vol. I — No. 034"
wire["tape_ts"] = "13 Aug 2026, 6:00am New York · Kitco live board · Editor's press-time read, written back to the tape"
wire["items"] = [
 {"b":"THE LOSS THAT DID NOT COME FROM REVENUE","t":" — Sarine Technologies reported its first half of 2026 on 11 August with revenue of $14.4 million, down 6%, and a net loss of $3.5 million against $166,000 a year earlier. No dividend was declared. Dividing one deficit by the other gives 21.1 times, this desk's arithmetic, and it is the least useful figure in the release, because a loss starting at $166,000 will produce a frightening multiple out of almost any deterioration. Take 6% off the published revenue and the prior half implies roughly $15.3 million, which puts the revenue decline at about $0.9 million against a deficit that widened by $3.334 million, roughly three and a half times as much. The loss did not come from the top line. The company names higher operating expenses on a weaker US dollar against the Israeli shekel, and lower natural-diamond processing volumes. Against that, GCAL grading revenue rose more than 50%, MVP rough-planning revenue more than doubled and Kitov.ai, 33% held, booked $1.5 million and also more than doubled. First coverage of this company anywhere in this paper's archive"},
 {"b":"THREE SESSIONS UNDONE","t":" — Kitco's live board at 06:00 New York time read gold $4,384.10 and silver $64.52, and the Editor wrote both back over caratwire's 04:59 marks of $4,374.20 and $64.31 under the one-price rule, with the timestamp and source named. Both were checked against TradingEconomics the same morning at $4,383.54 and $64.65, 0.01% and 0.20% away. Against this paper's own mark of record 24 hours earlier gold is down $31.10 or 0.70% and silver $1.78 or 2.68%. The gold-to-silver ratio, this desk's division of its own gold mark by its own silver mark, has widened to 67.95 from 66.59. Yesterday this desk published a four-session narrowing and said in print it was not yet a trend anybody should trade. The series ran 68.41 on 9 August, 67.84 on 10 August, 67.49 on 11 August and 66.59 on 12 August. One session has given back 1.36 of the 1.82 points, or 74.7% of the run, and the ratio now sits above every reading since 9 August. Fine gold is $140.95 a gram and fine silver $2.07"},
 {"b":"THE PLATINUM MARK THIS DESK WOULD NOT TAKE, AGAIN","t":" — Platinum and palladium were not written back for a second consecutive morning, for a sharper reason than yesterday's. Kitco's board read platinum $1,717.00, down $31.00 or 1.77%. TradingEconomics read $1,731.60 and JM Bullion's board at 06:01 New York time read $1,731.10. The two pages this paper does not use as its mark of record agree with each other to within 50 cents and put Kitco $14.60 low, a gap of 0.85% of the metal, which makes the board this paper reads the outlier rather than the market unsettled. That is not a verified press-time reading, so under rule 5 caratwire's 04:59 mark of $1,710.00 stands as filed and prints as-is. Palladium has no comparable second page at all this morning: Kitco bid $1,324.00 and the only other reachable board quoted an ask of $1,360.65, a different side of the spread and not a check, so the 04:59 mark of $1,319.00 stands. Yesterday the failure was a stale cell; today it is a live cell nobody else agrees with"},
 {"b":"TITAN CALLS THE PRICE STABLE","t":" — India's largest branded jeweller has put a view on natural-diamond pricing on the record, the first time in this paper's archive that the counter rather than the index has said it. Arun Narayan, Titan's jewellery chief executive, told an earnings call the company has seen more stability in the pricing of both solitaires and small diamonds. Ajoy Chawla, the managing director, said that at the market level it has stabilized and that the lab-grown-versus-natural narrative has faded. Published 12 August. The quarter behind it: consolidated income of Rs 20,753 crore for the three months to 30 June, up 40%, profit before tax of Rs 2,429 crore, up 64%, jewellery of Rs 18,253 crore, up 43% excluding bullion and digital gold, at a 12.9% EBIT margin, watches of Rs 1,543 crore, up 21%, and a net 77 stores added to reach 3,680. This paper published the same quarter on 28 July from the business update at about 41% and 39%; the 43% is a different basis, not a revision, and a third basis circulating in secondary coverage at 29.25% is disclosed on the page rather than chosen quietly"},
 {"b":"PRICED LIKE 1999","t":" — Senil Lakhani, president of Kiran Gems USA, told Rapaport's Heard on the Street that diamonds below one carat and up to 1.5 carats are less expensive than ever before and are selling at prices from the 1990s and early 2000s. He put the core range at 0.30, 0.40, 0.50 and 0.70 carats, calling those sizes the bread and butter for America, and placed the money at $1,000, $2,000 and $5,000. This paper has reported the same goods from the index end all month: 0.30-carat up 1.6% and 0.50-carat up 1.8% in July against a flat one-carat, published 4 August, and K to M colours averaging 1.7% against 0.1%, published yesterday. Those are directions for one month. Lakhani is describing a level, and no index this desk can reach publishes a 1999 comparison, which is said on the page rather than papered over. On the same panel Jeff Angel, head buyer at RDI Diamonds, said he can find a traceable Botswana-origin stone in about five minutes and recently filled a million-dollar order in which every stone had to come from Botswana"},
 {"b":"WHAT DID NOT PRINT TODAY","t":" — The Bureau ranked UAE 24k gold third, at 530-531 AED a gram against spot near $4,400, on two independent Arabic sources agreeing within about a dirham a gram, and flagged the over-serving history itself. It is dropped again. This paper ran the Dubai two-page wedge on 10 and 11 August and dropped it on 12 August for over-serving; a fourth appearance in five days is the same call a second time, and the sourcing being better does not make the story newer. The Bureau also held an SGE item at 952.50 yuan a gram with a Chow Tai Fook counter easing to 1,329 yuan, killed on its own judgement before it reached this desk, and this desk agrees: the SGE leg came from an aggregator rather than the exchange and the retail wrinkle is unexplained. Four of seven Bureau desks filed nothing at all, and all five dry desks named their second-door sources and printed what came back. Four articles today rather than eight, per the runbook"},
 {"b":"GEMSTONES DARK A NINTH EDITION","t":" — Colour has now missed nine consecutive editions, its last appearance being minus-point-one-for-color on 4 August, and it breaks the paper's own record of eight set yesterday. Recomputed here from the raw per-edition desk mix across Nos. 027 to 033 rather than carried forward from yesterday's prose. The Bureau escalated it this morning as a structural problem rather than a sourcing one: the beat has checked the same five standing anchors faithfully for over a week and a ninth blocked morning from the same URLs is not new information. This desk seconds that to the Managing Editor. Watches is dark a fourth consecutive edition, having last run in No. 030 on 9 August, with Swiss federation July export data not due until about 20 August. Auctions is dark a fourth consecutive edition, same count, and genuinely calendar-driven: Sotheby's Gem Drop closes in New York today and Heritage's New York sale runs through the 15th, so no result can exist yet"},
 {"b":"THE STANDARDS FILE WAS CLEAR","t":" — The newest standards audit is caratcheck's file of 12 August, read first this morning ahead of the slate per the correction route. It lists nothing under FOR CORRECTION TODAY and records no fault on any live page in edition No. 033: on the order of 90 numeric claims traced across four articles, none failed, and the four pull quotes counted 13, 12, 11 and 13 words against the cap of 15. There is no outstanding correction on any published page this morning and no figure was altered today. Today's four pull quotes were counted before the queue was written, as the quote gate requires, and the apply script fails the build on any quote over the cap"},
]
wire["tape"] = [
 {"name":"Gold / oz","code":"XAU","px":"4,384.10","chg":"▼ −0.70%","dir":"down",
  "pts":[16,15,18,19,21,23,23,24,26,24]},
 {"name":"Natural 1ct (RAPI proxy)","code":"NAT1","px":"5,232.00","chg":"— unch.","dir":"flat",
  "pts":[13,13,13,13,13,13,13,13,13,13]},
 {"name":"Lab-grown 1ct reference","code":"LGD1","px":"711.00","chg":"— unch.","dir":"flat",
  "pts":[13,13,13,13,13,13,13,13,13,13]},
 {"name":"Platinum / oz","code":"XPT","px":"1,710.00","chg":"▼ −2.12%","dir":"down",
  "pts":[17,18,19,20,22,21,21,22,21,18]},
 {"name":"Silver / oz","code":"XAG","px":"64.52","chg":"▼ −2.68%","dir":"down",
  "pts":[16,17,19,18,22,21,22,23,25,22]},
]
(C/"wire.json").write_text(json.dumps(wire,ensure_ascii=False,indent=1))

# ---- record: append into the current week (Thursday, no rollover) ----
wk = record["weeks"][0]
assert wk["label"] == "This week — August 10", wk["label"]

newent = [
 {"d":"diamonds","h":"Sarine's first-half deficit widened 21-fold on a revenue decline of about $0.9 million",
  "t":"Sarine Technologies reported results for the six months ended 30 June 2026 on 11 August 2026. Revenue was $14.4 million, down 6% on the first half of 2025, and the group recorded a net loss of $3.5 million against a net loss of $166,000 in the comparable half. No dividend was declared. Dividing one deficit by the other gives 21.1 times, this desk's arithmetic on the two published figures. Taking 6% off the published revenue implies revenue of roughly $15.3 million in the first half of 2025, which puts the revenue decline at about $0.9 million against a deficit that widened by $3.334 million, or approximately three and a half times the fall in the top line; those three figures are this desk's arithmetic on rounded published figures and are published by no source. The company attributes the wider loss to higher operating expenses, driven by a weaker US dollar against the Israeli shekel, and to reduced natural-diamond processing volumes in the face of lab-grown competition. Against that, revenue from GCAL grading rose more than 50% in the half, revenue from the MVP rough-planning service more than doubled, and Kitov.ai, the industrial-inspection associate in which Sarine holds 33%, booked $1.5 million of revenue and also more than doubled. The company's own framing is that a 6% revenue decline is modest relative to a significantly greater contraction in rough diamond supply. Sarine sells the scanning, planning and grading equipment and services that stones pass through on the way to a polished parcel, so its revenue tracks stones processed rather than stones sold at retail. This paper published global rough production down 8% to 98.8 million carats in 2025 on 27 July 2026, and Lucara Diamond selling 24% fewer carats in its second quarter on 12 August 2026. This is the first coverage of Sarine Technologies in this paper's archive.",
  "s":"Rapaport (11 August 2026) / Minichart (11 August 2026) / Carat Capital arithmetic and archive"},
 {"d":"gold-metals","h":"The gold-to-silver ratio widens to 67.95, giving back three-quarters of a four-session run",
  "t":"On 13 August 2026 Kitco's live board at 06:00 New York time read gold at $4,384.10 an ounce and silver at $64.52. Under the one-price rule the Editor wrote both readings back over caratwire's 04:59 marks of $4,374.20 and $64.31, with the new timestamp and the source named on the tape before the edition built. Both were cross-checked the same morning against TradingEconomics, which read gold $4,383.54 and silver $64.65, differences of 0.01% and 0.20%. Measured against this paper's own mark of record 24 hours earlier, gold fell $31.10 or 0.70% and silver fell $1.78 or 2.68%. The gold-to-silver ratio, this desk's division of its own published gold mark by its own published silver mark on the same tape at the same hour, widened to 67.95 from 66.59. The series now reads 68.41 on 9 August, 67.84 on 10 August, 67.49 on 11 August, 66.59 on 12 August and 67.95 on 13 August. The four-session narrowing to 12 August was worth 1.82 points; 1.36 of them, or 74.7%, came back in a single session, and the ratio now sits above every reading since 9 August. Fine gold works out at $140.95 a gram and fine silver at $2.07, at 31.1035 grams to the troy ounce. Platinum and palladium were not written back for a second consecutive morning. Kitco's board read platinum $1,717.00, down $31.00 or 1.77%, while TradingEconomics read $1,731.60 and JM Bullion's board at 06:01 New York time read $1,731.10; the two pages this paper does not carry as its mark of record agree with each other to within 50 cents and put Kitco $14.60 or 0.85% low, so no press-time reading was treated as verified and caratwire's 04:59 mark of $1,710.00 stands as filed. Palladium had no comparable second reading available, Kitco bidding $1,324.00 against an ask of $1,360.65 on the only other reachable board, so the 04:59 mark of $1,319.00 stands.",
  "s":"Kitco / TradingEconomics / JM Bullion / Carat Capital tape and arithmetic"},
 {"d":"retail-tech","h":"Titan says natural-diamond pricing has stabilised, on a 43% jewellery quarter",
  "t":"In remarks published on 12 August 2026, Arun Narayan, chief executive of Titan's jewellery business, said the company has seen more stability in the pricing of both solitaires and small diamonds, and Ajoy Chawla, Titan's managing director, said that at the market level natural-diamond pricing has stabilized and that the lab-grown-versus-natural narrative has faded from the conversation. Titan reported a resurgence in diamond-jewellery buying in the fourth quarter of its fiscal 2026 and into the first quarter of fiscal 2027, with demand strengthening through the April-to-June period. Titan's consolidated income for the three months to 30 June 2026 was Rs 20,753 crore, up 40% year on year, with profit before tax of Rs 2,429 crore, up 64%, at a margin of 11.7%. The jewellery division recorded Rs 18,253 crore, up 43% excluding bullion and digital gold, at an EBIT of Rs 2,360 crore and a margin of 12.9%. Watches and wearables recorded Rs 1,543 crore, up 21%, at an EBIT margin of 19.1%. The group added a net 77 stores in the quarter to reach 3,680 worldwide as at June 2026. This paper published the same quarter on 28 July 2026 from the company's own business update at approximately 41% revenue growth and 39% for jewellery; the 43% figure excludes bullion and digital gold and is a different basis rather than a revision. A third basis circulating in secondary coverage, revenue from operations of Rs 21,356 crore and growth of 29.25% against Rs 16,523 crore, is internally consistent on its own terms and does not agree with the 40% consolidated-income headline; the divergence is disclosed rather than resolved. Titan is a retailer of natural diamonds and the statement is made by an interested party on its own earnings call. This paper reported Indian gold jewellery demand down 15% by weight in the second quarter of 2026 even as its value rose.",
  "s":"Rapaport (12 August 2026) / afaqs (8 August 2026) / Sahi (7 August 2026) / Carat Capital archive"},
 {"d":"diamonds","h":"Kiran Gems USA says 0.30 to 0.70-carat goods are selling at 1990s prices",
  "t":"On Rapaport's Heard on the Street, published 12 August 2026, Senil Lakhani, president of Kiran Gems USA, said that diamonds below one carat and up to 1.5 carats are less expensive than ever before and are selling at prices from the 1990s and early 2000s. He identified the 0.30, 0.40, 0.50 and 0.70-carat range as the bread and butter for America and placed the relevant price points at $1,000, $2,000 and $5,000 rather than at the half-million and million-dollar level. Kiran Gems is one of the largest diamond manufacturers in the world. This paper has reported the same goods from the index side through August: RapNet monthly moves for July had 0.30-carat goods up 1.6% and 0.50-carat goods up 1.8% against a flat one-carat index, published here on 4 August 2026, and the colour split inside that flat month had K to M goods averaging 1.7% against 0.1% for D to F and G to J colours in IF to VVS and VS clarity, published here on 12 August 2026. Those figures are directions for a single month; the characterisation of a 1990s price level is a level, and no index reachable by this desk publishes a 1999 comparison for 0.30 to 0.70-carat goods, so the level claim is reported as a named executive's characterisation of his own market and not as a price. On the same panel, Jeff Angel, head buyer at RDI Diamonds, said he can locate a diamond of traceable Botswana origin in about five minutes and recently filled a million-dollar order in which every stone was required to come from Botswana. Other participants in the episode included Ari Jain of House of Diamonds, Angelo Palmieri of GCAL by Sarine and Kerri Lavine of Diamanti NYC, moderated by Heather Chambers.",
  "s":"Rapaport Heard on the Street (12 August 2026) / Carat Capital archive"},
]
wk["entries"] = newent + wk["entries"]
record["updated"] = "13 Aug 2026"
(C/"record.json").write_text(json.dumps(record,ensure_ascii=False,indent=1))
print("wire No.034 written;", len(newent), "record entries prepended into", wk["label"], "->", len(wk["entries"]), "total")
