#!/usr/bin/env python3
# Edition No. 045 - wire tape + the record.
import json, pathlib
C = pathlib.Path("content")
w = json.loads((C/"wire.json").read_text())
r = json.loads((C/"record.json").read_text())

w["date_line"] = "Wednesday, August 26, 2026"
w["edition"] = "Vol. I - No. 045"
w["tape_ts"] = ("26 Aug 2026, 06:05 ET - Kitco, corroborated on TradingEconomics - Editor re-read at press time "
                "and wrote back gold at $4,622.30 and silver at $68.55. Platinum and palladium held at $1,881.00 "
                "and $1,336.00, a sixth session, with Kitco and TradingEconomics 0.83% and 1.40% apart")

w["items"] = [
 {"b":"DOYLE NEW YORK TAKES $457,700 FOR 12.46 CARATS, AND 1890 SAPPHIRES BEAT THEIR BOOK BY 180%",
  "t":"The top lot, a D colour VS2 emerald cut, cleared its $350,000 high estimate by 30.8%. A pair of antique earrings holding a 4-carat Ceylon and a 4.17-carat Kashmir sapphire made $140,200 against $30,000 to $50,000, which is 2.80 times the high. Four of the top five beat the book; the sale made more than $8 million."},
 {"b":"A ROYAL BROOCH LED THE ELMWOOD'S COVERAGE AND FINISHED FOURTH OF FOUR ON PRICE",
  "t":"The Verdura unicorn brooch from Queen Elizabeth II's lady-in-waiting made 23,750 pounds, or $32,400, at the 19 August London sale. A 1927 Van Cleef and Arpels feather brooch made 75,000 pounds, 3.16 times as much. Every dollar conversion in the report reconciles to one rate near $1.363 to the pound."},
 {"b":"KAGEM SHOWS ROUGH EMERALDS IN JAIPUR FOR NINETEEN DAYS, AND PUBLISHES NO PRICE",
  "t":"The 13th India Rough Gemstones Sourcing Show opened 24 August and runs to 11 September, with more than 60 Indian manufacturers on the council's own count. Kagem's May book in London took $26.8 million at $146.08 a carat. No value, carat weight or lot count has been published for Jaipur."},
 {"b":"FOSSIL'S SALES FELL 4.9% AND THE WATCH LINE FELL 1.5%",
  "t":"The quarter to 4 July puts net sales at $209.7 million against $220.4 million. Traditional watches went from $178.4m to $175.7m. Leathers fell 31.1% and jewellery 11.2%, and leathers alone are about half the whole decline. Across six months traditional watch sales rose 0.4%."},
 {"b":"A ROUGH STONE PASSED VISUAL SCREENING AS NATURAL AND FAILED ONLY AT INFRARED",
  "t":"The Israeli Diamond Institute reports a stone submitted 18 August that looked like ordinary natural rough, drew a preliminary and self-qualified flag from a CVD screening device, and was classified Type IIa by FTIR. Single-source, the testing laboratory itself, and no carat weight published."},
 {"b":"GOLD WRITTEN BACK AT $4,622.30, DOWN $21.60 ACROSS TWO SESSIONS",
  "t":"Kitco and TradingEconomics sat $1.54 apart, or 0.033%. Silver written back at $68.55 on a 0.19% gap, up 0.99% on yesterday, narrowing the ratio to 67.43 from 68.27. Platinum and palladium held a sixth session at $1,881.00 and $1,336.00, their two sources 0.83% and 1.40% apart."},
]

for t in w["tape"]:
    if t["code"] == "XAU":
        t["px"], t["chg"], t["dir"] = "4,622.30", "▼ −0.26%", "down"
        t["pts"] = [26,25,23,22,26,28,29,29,31,30]
    elif t["code"] == "XAG":
        t["px"], t["chg"], t["dir"] = "68.55", "▲ +0.99%", "up"
        t["pts"] = [23,26,25,19,26,28,27,27,26,27]
    elif t["code"] == "XPT":
        t["px"], t["chg"], t["dir"] = "1,881.00", "— unch.", "flat"

(C/"wire.json").write_text(json.dumps(w, indent=1, ensure_ascii=False))

ENTRIES = [
 {"d":"auctions","h":"Doyle New York takes $457,700 for a 12.46-carat ring, and an 1890 sapphire pair beats its book by 180%",
  "t":"Doyle's Important Jewelry sale in New York was led by a 12.46-carat cut-cornered step-cut emerald cut, D colour, VS2, between tapered baguettes, at $457,700 against a $350,000 high estimate, which is $107,700 or 30.8% above the ceiling on this desk's arithmetic, and $36,733.55 a carat. Rapaport's report of 24 August, drawing on Doyle's own website, puts the whole sale above $8 million. A JAR ring of about 1980 with a 5.78-carat G VS2 cushion modified brilliant made $165,600 against $80,000 to $120,000, or 1.38 times the high. A Cartier Mahango Panthere necklace of more than 500 diamonds weighing about 30 carats made $133,850 against $50,000 to $70,000, 1.91 times the high. A pair of 1890 earrings holding an oval 4-carat Ceylon sapphire and an oval 4.17-carat Kashmir sapphire, each ringed by ten old-mine diamonds, made $140,200 against $30,000 to $50,000, which is 2.80 times the high and 180.4% above it, the widest margin in the top five. A Tiffany and Co. Fleurage bracelet, eight rounds of 10.80 carats and 439 smaller rounds of 25 carats, made $127,500 inside a $100,000 to $150,000 estimate, 15% below the high, the one lot of the five that did not beat its book. The five together made $1,024,850, at most 12.8% of a sale of more than $8 million. Doyle publishes no origin or treatment detail in the results this desk read, so the sapphires' laboratory origin call and heat status are unknown and are not asserted here.",
  "s":"Rapaport News, 24 August 2026"},
 {"d":"auctions","h":"A Verdura brooch with royal provenance makes 23,750 pounds at Elmwood's, and a 1927 Van Cleef feather makes 75,000",
  "t":"Elmwood's Auctioneers sold a Verdura unicorn-head brooch, about 1.10 carats of diamonds under a circular cabochon turquoise crown, made by Fulco di Verdura, for 23,750 pounds or $32,400 at its London sale of 19 August 2026, reported by Rapaport on 24 August. It belonged to Virginia Fortune Ryan Ogilvy, dowager countess of Airlie, a lady-in-waiting to Queen Elizabeth II for close to fifty years. Three lots named in the same report sold for more: a 1927 Van Cleef and Arpels Art Deco diamond feather brooch at 75,000 pounds or $102,229, an Art Deco Egyptian Revival tiara at 65,000 pounds or $88,595, and a Cartier tutti frutti brooch of about 1940 at 60,000 pounds or $81,780. The Van Cleef made 3.16 times the royal brooch on this desk's division. Each dollar figure divided by its sterling figure returns 1.36305, 1.36300, 1.36300 and 1.36421, so one conversion rate near $1.363 to the pound was applied across the sale rather than four separately struck prices. The four named lots total 223,750 pounds or $305,004. Elmwood's published no sale total in the report this desk read, so the four lots' share of the sale is not stated. Priced as jewellery the Verdura returned $29,455 for each carat of diamond content, which is the signature and the provenance rather than the goods.",
  "s":"Rapaport News, 24 August 2026"},
 {"d":"gemstones","h":"Kagem shows rough emeralds at the 13th India Rough Gemstones Sourcing Show in Jaipur, nineteen days and no published price",
  "t":"The Gem and Jewellery Export Promotion Council's release of 25 August 2026 records the 13th India Rough Gemstones Sourcing Show opening in Jaipur on 24 August and running to 11 September, a nineteen-day window. Kagem Mining Ltd of Zambia is named as showing rough emeralds, and is the only source-country miner named. The council puts attendance at more than 60 Indian coloured-gemstone manufacturers, its own count and not independently audited. R.K. Chandan, Commissioner of Customs at Jaipur, was chief guest, with Jeevan Ram Dhaka, Assistant Commissioner of Customs at ACC Jaipur, Yogendra Garg, the council's regional chairman for Rajasthan, and D.P. Khandelwal, convener of its coloured gemstones panel. The stated purpose is to let Indian manufacturers buy rough at source without travelling abroad. Kagem is Gemfields' Zambian emerald mine, 75% owned with the Industrial Development Corporation of Zambia holding the rest; its higher-quality rough auction held in London across May took $26.8 million, clearing 36 of 37 lots and 183,385 of 185,135 carats at an average $146.08 a carat, as this paper reported on 24 July, and Gemfields took $102.9 million from auctions across the first half of 2026, up 72%, as reported here on 31 July. No value, carat weight, lot count, sale mechanism or result has been published for the Jaipur show, which does not close until 11 September.",
  "s":"GJEPC release, 25 August 2026; Carat Capital, 24 and 31 July 2026"},
 {"d":"watches","h":"Fossil Group's quarter to 4 July falls 4.9% to $209.7 million, and the watch line falls 1.5%",
  "t":"Fossil Group's Form 10-Q for the thirteen weeks to 4 July 2026, filed with the SEC on 13 August, puts net sales at $209,688 thousand against $220,388 thousand for the quarter to 5 July 2025, a fall of $10.7 million or 4.9%. On the company's own table of net sales by class of similar products, traditional watches fell from $178,446 to $175,746 thousand, which is 1.5%; smartwatches from $1,400 to $1,388 thousand; total watches from $179,846 to $177,134 thousand, 1.5%. Leathers fell from $16,947 to $11,679 thousand, a drop of $5,268 thousand or 31.1%, which is roughly half the company's entire decline from a line worth under 6% of sales. Jewellery fell from $19,390 to $17,220 thousand, $2,170 thousand or 11.2%. Across twenty-six weeks traditional watch sales rose, from $363,076 to $364,477 thousand, up $1,401 thousand or 0.4%, while total watches were down 0.25%, leathers down 34.6% and jewellery down 10.3%, on half-year net sales down 4.2% from $453,681 to $434,449 thousand. Watches rose as a share of quarterly sales from 81.6% to 84.5%, jewellery slipped from 8.8% to 8.2% and leathers from 7.7% to 5.6%. The filing is thirteen days old and cannot lead under this paper's fourteen-day rule.",
  "s":"Fossil Group Form 10-Q, filed 13 August 2026, SEC EDGAR"},
 {"d":"diamonds","h":"A rough stone passes visual screening as natural at the Israeli Diamond Institute and is classified Type IIa by infrared",
  "t":"The Israeli Diamond Institute's technology department, in an article dated 25 August 2026 on its own site and bylined to staff gemologist Sergey Lazon, reports a rough stone submitted on Tuesday 18 August whose recorded data matched expected parameters and which externally appeared to be natural rough. Microscopy found small clouds and inclusions of the kind natural rough carries, together with minor defects the institute describes as atypical of natural diamond and consistent with CVD growth. A dedicated CVD screening device returned a preliminary indication of laboratory origin, which the institute itself qualifies by noting such devices can give ambiguous readings where inclusions are weak. Fourier transform infrared spectroscopy returned what the institute calls an unambiguous result and classified the stone as Type IIa, the nitrogen-poor category most laboratory-grown diamond falls into and one the institute says is difficult to attribute to natural origin given this rough's structure and shape. The account gives no carat weight, measurements, colour, price or country of submission. It states that the Gemological Institute of America identified a comparable stone days earlier and attributes that to a report by IDEX Online rather than to the GIA directly, a claim hedged twice in the original and carried hedged here. Single-source: the testing laboratory describing its own test, with no independent outlet reporting it and no submitting party named.",
  "s":"Israeli Diamond Institute, 25 August 2026 (Hebrew)"},
 {"d":"gold-metals","h":"Gold is written back to the tape at $4,622.30, down $21.60 across two sessions, and silver at $68.55",
  "t":"The Editor re-read all four metals on Kitco at press time on 26 August 2026, board timestamp 05:59 ET, and wrote two back. Gold $4,622.30 the ounce against TradingEconomics at $4,623.84, a gap of $1.54 or 0.033%; silver $68.55 against $68.68, a gap of 13 cents or 0.19%. Both replace 05:00 marks of $4,626.00 and $68.462. Gold's marks of record ran $4,643.90 on Monday, $4,634.20 on Tuesday and $4,622.30 today, down $9.70 then $11.90, for $21.60 or 0.465% across two sessions. Kitco's own board showed a larger fall of $35.60 or 0.76% measured against its own previous close rather than this paper's daily mark, which is a different reference and not a divergence between sources; its day range ran $4,615.50 to $4,674.60, so the morning mark sits $6.80 above the low in a $59.10 range. Silver ran $68.74, $67.88 and $68.55 across the same three sessions, up 0.99% on yesterday and 19 cents or 0.28% below Monday, narrowing the gold to silver ratio to 67.43 from 68.27, with Monday's at 67.56. Platinum and palladium were held a sixth session at $1,881.00 and $1,336.00, both set 21 August: Kitco read $1,856.00 and $1,321.00 against TradingEconomics at $1,871.40 and $1,339.50, gaps of 0.83% and 1.40%, outside the band. Both held marks sit inside today's Kitco day ranges of $1,846.00 to $1,887.00 and $1,305.00 to $1,375.00.",
  "s":"Kitco and TradingEconomics, read 26 August 2026, 05:59-06:05 ET"},
]
r["weeks"][0]["entries"][:0] = ENTRIES
r["updated"] = "26 Aug 2026"
(C/"record.json").write_text(json.dumps(r, indent=1, ensure_ascii=False))
print("wire edition", w["edition"], "| record entries wk0", len(r["weeks"][0]["entries"]))
