#!/usr/bin/env python3
import json, pathlib
C = pathlib.Path("content")
wire = json.loads((C/"wire.json").read_text())
record = json.loads((C/"record.json").read_text())

wire["date_line"] = "Wednesday, August 12, 2026"
wire["edition"] = "Vol. I — No. 033"
wire["tape_ts"] = "12 Aug 2026, 5:59am New York · Kitco live board · Editor's press-time read, written back to the tape"
wire["items"] = [
 {"b":"THE MIX, NOT THE PRICE","t":" — Lucara Diamond sold 58,553 carats out of Karowe in the second quarter of 2026 against 77,167 a year earlier, and took $41.0 million against $43.7 million. Twenty-four per cent fewer stones for six per cent less money. Dividing the company's own revenue by its own carats gives $700.22 a carat realised against $566.30 a year ago, up 23.7%, arithmetic this desk has done and no source publishes. The company's own commentary runs the other way: tender prices down 5% and Clara prices down 17% on continued pressure in mid-range and lower-grade stones. Both are true, and the whole of the realisation gain is composition. It is not more big stones either, since specials above 10.8 carats came in at 176 against 242. Second-quarter net income was $15.6 million against $12.5 million, but first-half net income was $1.0 million against $12.4 million, which puts a loss of roughly $14.6 million in the first quarter by subtraction. Full-year guidance held at $100-130 million and 340,000-360,000 carats, leaving 201,703 to 221,703 carats to sell after halfway"},
 {"b":"SILVER TAKES A FOURTH SESSION","t":" — Kitco's live board at 05:59 New York time read gold $4,415.20 and silver $66.30, and the Editor wrote both back over caratwire's 04:59 marks of $4,401.70 and $66.03 under the one-price rule, with the timestamp and source named. Both were checked against TradingEconomics the same morning at $4,416.14 and $66.39, 0.02% and 0.14% away. Against this paper's own mark of record 24 hours earlier gold is up $42.40 or 0.97% and silver $1.51 or 2.33%. The gold-to-silver ratio, this desk's division of its own gold mark by its own silver mark, has now narrowed on four consecutive sessions: 68.41 on 9 August, 67.84 on 10 August, 67.49 on 11 August and 66.59 this morning. That is 1.82 points or 2.66% out of gold's purchasing power over silver in three sessions, and today's 0.90-point step is the largest of the four. Fine gold is $141.95 a gram"},
 {"b":"THE PLATINUM MARK THIS DESK WOULD NOT TAKE","t":" — Platinum and palladium were not written back this morning, and the reason is printed on the page rather than buried. Kitco's platinum cell read $1,764.00, up $27.00 or 1.55%, which is the identical value and the identical change this paper printed yesterday. JM Bullion's board at 04:52 New York time bid $1,748.00. TradingEconomics read $1,761.30, up 0.36%. That is a span of $33.90 across three published pages inside an hour, or 1.94% of the metal, derived by this desk. Against that spread, and against a cell reproducing yesterday exactly, none of the three is a verified press-time reading, so caratwire's 04:59 mark of $1,747.00 stands as filed and is the figure JM Bullion's bid corroborates within a dollar. Palladium is handled identically: the tape carries $1,351.00 against $1,368.00 on Kitco and $1,392.59 on JM Bullion at 00:13, a 3.1% spread. An hour-old mark this paper can stand behind beats a fresh-looking one it cannot"},
 {"b":"ZALES GOES TO A TOY EXECUTIVE","t":" — Signet Jewelers named Jamie Cygielman president of Zales and Banter on 11 August, starting 24 August, reporting directly to chief executive J.K. Symancyk and based in Dallas. She arrives from Mattel, where she was global head of dolls, a portfolio she reached after running American Girl as general manager and president and later widened to include Barbie. The same release named Pam Cloud president of Blue Nile with effect from 10 August, out of more than 25 years at Tiffany and Co., latterly senior vice president and chief merchandising officer, which this paper reported on 6 August. Two of Signet's four brand families changed president in eight days and the two hires are different in kind. Under Grow Brand Love, launched by Symancyk in March 2025, Signet runs four customer families: Kay and Peoples for core milestone and romantic gifting, Zales and Banter for style and trend, Jared for inspired luxury and Blue Nile for luxury. Luxury went to a merchant from inside the trade. Style and trend went to somebody who has never sold jewellery"},
 {"b":"A FLAT MONTH WITH A SHAPE INSIDE IT","t":" — Rapaport's Diamond Pulse for August breaks open the flat July one-carat index this paper led on for 4 August. One-carat goods in D to F and G to J colour, in IF to VVS and VS clarity, averaged a gain of 0.1% in July. K to M colours averaged 1.7%. K to M in VS swung from a 0.1% loss to a 2.8% gain. The headline was flat because a near-flat top and a rising bottom cancelled inside it. The recovery this paper has described as bottom-up since 14 July now has a second dimension: it was already running from the bottom of the size chart, with 0.30-carat up 1.6% and 0.50-carat up 1.8% in the same month against a flat one-carat, and it is now also running from the bottom of the colour scale. One source, and it is the owner of the index reporting on its own index, with no second publisher of RapNet colour-band moves to check it against"},
 {"b":"WHAT DID NOT PRINT TODAY","t":" — Two of the Bureau's six slate items were killed here on the archive test and both kills were available to the Bureau. The August Diamond Pulse's rough-production line, filed as unpublished after a string grep on 98.8 returned no hit, is in this paper's own archive: global rough production down 8% to 98.8 million carats in 2025 ran here on 27 July inside thirties-outrun-the-ones, with Russia leading by value for a third year. The Section 301 tariff bands in the same newsletter ran here on 25 July as tariff-wall-returns, at 10% and 12.5% effective 24 July, and the coloured-stone half of it ran on 23 July. Gem Diamonds' first-half figures, ranked second on the Bureau's slate and second on the marketing memo, were killed here yesterday as a repeat of 29 July and stay killed; this desk is not going to contradict its own published kill note two days later. The Shanghai gold contract at 947 yuan a gram could not be verified at source this morning and was not printed"},
 {"b":"GEMSTONES DARK AN EIGHTH EDITION","t":" — Colour has now missed eight consecutive editions, its last appearance being minus-point-one-for-color on 4 August, and it remains the longest dark streak on this paper's record. The Editor swept the beat independently rather than accepting the desk's file and returned only undated retailer trend copy: per-carat ruby averages with no publisher or method attached, and origin-report expansions dated to January. Nothing dated, sourced and unpublished exists in colour this morning. Gemfields' next mixed-quality auction is not until October and the Fancy Color Research Foundation was ruled out as a standing anchor yesterday because it puts its index behind membership. Watches is dark a third consecutive edition, with the Swiss federation's July export data not due until roughly 20 August and June's 11.2% already published here. Auctions is dark a third consecutive edition; Sotheby's Arcade Hong Kong result is still unpublished six days after close, and the Gem Drop sale in New York does not finish until 13 August"},
 {"b":"THE STANDARDS FILE WAS CLEAR","t":" — The newest standards audit is caratcheck's file of 10 August and every item it listed under FOR CORRECTION TODAY was corrected in yesterday's run, on its own commit, ahead of the slate: the pull-quote element that set this paper's own analysis inside a quotation with a speech attribution was fixed at the renderer across all 235 article pages. No new standards file has been filed since. There is no outstanding correction on any published page this morning and no figure was altered today"},
]
wire["tape"] = [
 {"name":"Gold / oz","code":"XAU","px":"4,415.20","chg":"▲ +0.97%","dir":"up",
  "pts":[15,16,15,18,19,21,23,23,24,26]},
 {"name":"Natural 1ct (RAPI proxy)","code":"NAT1","px":"5,232.00","chg":"— unch.","dir":"flat",
  "pts":[13,13,13,13,13,13,13,13,13,13]},
 {"name":"Lab-grown 1ct reference","code":"LGD1","px":"711.00","chg":"— unch.","dir":"flat",
  "pts":[13,13,13,13,13,13,13,13,13,13]},
 {"name":"Platinum / oz","code":"XPT","px":"1,747.00","chg":"▼ −0.96%","dir":"down",
  "pts":[16,17,18,19,20,22,21,21,22,21]},
 {"name":"Silver / oz","code":"XAG","px":"66.30","chg":"▲ +2.33%","dir":"up",
  "pts":[15,16,17,19,18,22,21,22,23,25]},
]
(C/"wire.json").write_text(json.dumps(wire,ensure_ascii=False,indent=1))

# ---- record: append into the current week (Wednesday, no rollover) ----
wk = record["weeks"][0]
assert wk["label"] == "This week — August 10", wk["label"]

newent = [
 {"d":"diamonds","h":"Lucara's realised price a carat rose 23.7% while both its sales channels cut prices",
  "t":"Lucara Diamond released its second-quarter 2026 results on 7 August 2026. The company sold 58,553 carats from its Karowe mine in Botswana during the quarter, against 77,167 carats in the second quarter of 2025, and recorded revenue of $41.0 million against $43.7 million, a fall of 6% on a 24% fall in carats sold. Dividing the published revenue by the published carats gives a realised price of $700.22 a carat for the quarter against $566.30 a year earlier, a rise of 23.7%; on the first half the same division gives $454.10 a carat against $493.21, a fall of 7.9%. All four of those per-carat figures are this desk's arithmetic and are published by no source. The company's own commentary states that average prices per carat declined across both channels, with tender prices falling 5% and Clara prices falling 17%, which it attributes to continued pricing pressure on mid-range and lower-grade stones. The whole of the realisation gain is therefore composition rather than price. It is not a function of more large stones reaching the surface either: specials, the stones above 10.8 carats, were recovered at 176 in the quarter against 242 a year earlier. Second-quarter net income was $15.6 million against $12.5 million; first-half net income was $1.0 million against $12.4 million, a fall of 92%, which implies a first-quarter loss of roughly $14.6 million by subtraction, this desk's arithmetic. The plant processed 761,848 tonnes of ore and recovered 90,082 carats at a grade of 10.9 carats per hundred tonnes, of which 6,973 carats came from tailings, at an operating cost of $23.76 a tonne, down 11% from $26.76. Full-year guidance was maintained at revenue of $100 million to $130 million, carats recovered and carats sold each at 340,000 to 360,000, ore processed at 2.6 to 2.9 million tonnes, operating costs of $27.50 to $31.00 a tonne, underground project capital of up to $110 million and sustaining capital of up to $11.5 million. Against $62.8 million of first-half revenue and 138,297 carats sold, that requires $37.2 million to $67.2 million and 201,703 to 221,703 carats in the second half, or 59% to 62% of the year's sales after the halfway point, all derived by this desk. Cash stood at $243.6 million at 30 June against bonds payable of $342.8 million with nothing drawn on the working capital or project facilities. The Karowe underground project has $275.9 million of completion cost remaining including contingency, with full production expected in the first half of 2028 and open-pit mining on track to conclude in the fourth quarter of 2026; in July 2026 the Botswana Department of Mines licensed the 15-person auxiliary winder and the 105-person man and material winder on the production shaft.",
  "s":"Lucara Diamond Q2 2026 results via CNW (7 August 2026) / Rapaport / Carat Capital arithmetic"},
 {"d":"gold-metals","h":"The gold-to-silver ratio narrows a fourth consecutive session, to 66.59",
  "t":"On 12 August 2026 Kitco's live board at 05:59 New York time read gold at $4,415.20 an ounce and silver at $66.30. Under the one-price rule the Editor wrote both readings back over caratwire's 04:59 marks of $4,401.70 and $66.03, with the new timestamp and the source named on the tape before the edition built. Both were cross-checked the same morning against TradingEconomics, which read gold $4,416.14 and silver $66.39, differences of 0.02% and 0.14%. Measured against this paper's own mark of record 24 hours earlier, gold rose $42.40 or 0.97% and silver rose $1.51 or 2.33%. The gold-to-silver ratio, this desk's division of its own published gold mark by its own published silver mark on the same tape at the same hour, has now narrowed on four consecutive sessions: 68.41 on 9 August, 67.84 on 10 August, 67.49 on 11 August and 66.59 on 12 August. That is 1.82 points, or 2.66%, taken out of gold's purchasing power over silver across three sessions, and the 0.90-point narrowing on 12 August is the largest single step of the four. Fine gold works out at $141.95 a gram at 31.1035 grams to the troy ounce. Platinum and palladium were not written back. Kitco's platinum cell read $1,764.00, up $27.00 or 1.55%, the identical value and identical change this paper printed on 11 August; JM Bullion's board at 04:52 New York time bid $1,748.00; and TradingEconomics read $1,761.30, up 0.36%. That is a span of $33.90 across three published pages read inside an hour, or 1.94% of the metal, derived by this desk. On that basis no reading was treated as a verified press-time mark and caratwire's 04:59 figure of $1,747.00 stands as filed, corroborated within a dollar by JM Bullion's bid. Palladium was handled identically, the tape carrying $1,351.00 against $1,368.00 on Kitco and $1,392.59 on JM Bullion at 00:13, a spread of about 3.1%.",
  "s":"Kitco / TradingEconomics / JM Bullion / Carat Capital tape and arithmetic"},
 {"d":"retail-tech","h":"Signet gives Zales and Banter to Mattel's former global head of dolls",
  "t":"Signet Jewelers announced on 11 August 2026, from Hamilton, Bermuda, that Jamie Cygielman has been named president of Zales and Banter, effective 24 August 2026. She will be based in Dallas and reports directly to J.K. Symancyk, Signet's chief executive officer. She joins from Mattel, where she was global head of dolls, a portfolio she reached after serving as general manager and president of American Girl and which she later widened to include Barbie. The same release named Pam Cloud president of Blue Nile with effect from 10 August 2026, based in New York City; Cloud spent more than 25 years at Tiffany and Co., latterly as senior vice president and chief merchandising officer, an appointment this paper reported on 6 August 2026. Two of Signet's four brand families therefore changed president within eight days, and the two appointments are different in kind: one seat was filled from inside the jewellery trade and the other from a toy company. Under Grow Brand Love, the strategy launched by Symancyk in March 2025, Signet is organised into four customer families: Kay and Peoples for core milestone and romantic gifting, Zales and Banter for style and trend, Jared for inspired luxury, and Blue Nile for luxury. The stated aim of the strategy is to have the company's chains operate as brands rather than as retail banners and to grow share in adjacent categories, notably everyday jewellery. Gold spot stood at $4,415.20 an ounce on this paper's tape the same morning, up 0.97% on the paper's previous mark of record and up 6.2% on the $4,158.30 the tape carried on 5 August 2026.",
  "s":"Signet Jewelers (11 August 2026) / Forbes / Rapaport / Carat Capital archive and tape"},
 {"d":"diamonds","h":"July's flat one-carat index hid a 1.7% gain in K to M colours",
  "t":"Rapaport's Diamond Pulse for August 2026 published a colour-band breakdown of July's one-carat polished moves. One-carat goods in D to F and G to J colour, in IF to VVS and VS clarity, averaged a gain of 0.1% in July. K to M colours averaged a gain of 1.7%. K to M goods in VS clarity swung from a 0.1% loss to a 2.8% gain. This paper led its edition of 4 August 2026 on the finding that the RapNet Diamond Index for one-carat polished was unchanged across July, closing a slide that had run without a positive print since June 2025, alongside gains of 1.6% for 0.30-carat goods, 1.8% for 0.50-carat goods and 0.2% for 3-carat goods. The colour breakdown shows that the flat headline is an average of a near-flat top and a rising bottom, and that the recovery this paper has described as bottom-up since 14 July 2026 is running from the bottom of the colour scale as well as the bottom of the size chart. The ratio between the two bands is seventeen times, this desk's division of 1.7 by 0.1. The finding rests on a single source, and that source is the owner of the index reporting on its own index; there is no second publisher of RapNet colour-band moves against which to check it. The remaining figures in the same newsletter are already in this paper: global rough production down 8% to 98.8 million carats in 2025 was published here on 27 July 2026, De Beers' first-half revenue down 19% to $1.58 billion on 31 July 2026, and the Section 301 tariff bands of 10% and 12.5% on jewellery and gemstone imports on 25 July 2026.",
  "s":"Rapaport Diamond Pulse, August 2026 / Carat Capital archive"},
]
wk["entries"] = newent + wk["entries"]
record["updated"] = "12 Aug 2026"
(C/"record.json").write_text(json.dumps(record,ensure_ascii=False,indent=1))
print("wire No.033 written;", len(newent), "record entries prepended into", wk["label"], "->", len(wk["entries"]), "total")
