#!/usr/bin/env python3
import json, pathlib
C = pathlib.Path("content")
wire = json.loads((C/"wire.json").read_text())
record = json.loads((C/"record.json").read_text())

wire["date_line"] = "Thursday, August 6, 2026"
wire["edition"] = "Vol. I — No. 027"
wire["tape_ts"] = "6 Aug 2026, 6:03am New York · Kitco spot · change against Wednesday's close"
wire["items"] = [
 {"b":"SEVEN-WEEK HIGH, FOURTH SESSION","t":" — At 6:03am New York gold bid $4,270.90, up $24.70 or 0.58%, its highest in seven weeks and a fourth consecutive advance; platinum $1,753.00, up $23.00 or 1.33%; palladium $1,367.00, up $20.00 or 1.48%. Against the $4,157.80 this paper carried on Wednesday, gold has added $113.10 an ounce, or 2.72%, in twenty-four hours"},
 {"b":"SILVER ALONE IN THE RED","t":" — Silver bid $61.67, down 25 cents or 0.41%, the only one of the four metals lower and the first down session after leading the complex all week with gains of 3.27% and 3.2%; the gold to silver ratio widens back to 69.3 from 67.8, undoing two sessions of tightening in one"},
 {"b":"ONE THIRTY-SEVEN THIRTY-ONE A GRAM","t":" — Fine gold at $4,270.90 an ounce is $137.31 a gram against $133.68 on Wednesday and $130.17 on Tuesday, $3.63 added to the metal cost of every piece in a case since yesterday morning and $7.14 since Tuesday; platinum stands at 41.0% of the gold price, down from 42.0%"},
 {"b":"PAYROLLS AT HALF PAST EIGHT","t":" — The Bureau of Labor Statistics releases July non-farm payrolls at 8:30am Friday, the first full read on American hiring since the Federal Reserve held on 29 July with three dissents; June's print was 57,000. This desk carried the same release as a binary on 2 August and has nothing to add until it lands"},
 {"b":"ALROSA BOOKS A LOSS","t":" — Half-year accounts for the world's largest rough producer by volume show revenue of 74.2 billion roubles, about $932.5 million, down 36%, and a net loss of 10.67 billion roubles, about $134.1 million, against a $490.1 million profit a year earlier; several open pits go to care and maintenance in 2026 and mining at Severalmaz, roughly 10% of Russian output, is suspended"},
 {"b":"TWENTY-FIVE YEARS OF TIFFANY","t":" — Pam Cloud becomes president of Blue Nile on 10 August, reporting to Signet chief operating and financial officer Joan Hilson; she spent more than 25 of her 30 years in luxury retail at Tiffany and Co., latterly as senior vice president and chief merchandising officer, and founded the pearl brand Roseate Jewelry"},
 {"b":"THIRTEEN BILLION INSIDE THE PERIMETER","t":" — Deferred payment credit came under Financial Conduct Authority supervision in the United Kingdom on 15 July; the market grew from about £60 million of transactions in 2017 to more than £13 billion in 2024 with around 11 million British users, and lenders now owe affordability checks, upfront terms and Financial Ombudsman access, with six months from commencement to apply for full authorisation"},
 {"b":"NINE THIRTY-FOUR FOR ONE SEVENTEEN","t":" — Onyx Partners has bid $934 million for 117 J.C. Penney stores covering 15.7 million square feet across 35 states, about $8 million a store or roughly $59 a square foot; a $947 million offer was rejected in December by Copper Property CTL Pass Through Trust, and the firm says financing is in place to close on 25 September"},
 {"b":"SIXTY-SEVEN PERCENT ASKED A MACHINE","t":" — Attentive's survey of 600 United States adults finds 67% used an AI chatbot to help them shop in the past three months, rising to 80% of Gen Z and with 51% comparing brands that way; separately 62% will plan holiday purchases before November and 71% will start buying before Black Friday"},
]
wire["tape"] = [
 {"name":"Gold / oz","code":"XAU","px":"4,270.90","chg":"▲ +0.58%","dir":"up",
  "pts":[15,15,14,15,16,15,16,15,18,19]},
 {"name":"Natural 1ct (RAPI proxy)","code":"NAT1","px":"5,232.00","chg":"— unch.","dir":"flat",
  "pts":[13,13,13,13,13,13,13,13,13,13]},
 {"name":"Lab-grown 1ct wholesale","code":"LGD1","px":"727.00","chg":"— unch.","dir":"flat",
  "pts":[13,13,13,13,13,13,13,13,13,13]},
 {"name":"Platinum / oz","code":"XPT","px":"1,753.00","chg":"▲ +1.33%","dir":"up",
  "pts":[16,16,15,15,17,16,17,18,19,20]},
 {"name":"Silver / oz","code":"XAG","px":"61.67","chg":"▼ −0.41%","dir":"down",
  "pts":[17,17,17,16,16,15,16,17,19,18]},
]
(C/"wire.json").write_text(json.dumps(wire,ensure_ascii=False,indent=1))

# ---- record: prepend into the current week ----
wk = record["weeks"][0]
assert wk["label"] == "This week — August 3", wk["label"]

newent = [
 {"d":"gold-metals","h":"Gold makes a seven-week high on a fourth session up while silver turns lower",
  "t":"At 6:03am New York time on 6 August, Kitco's spot page had gold bid at $4,270.90 an ounce, up $24.70 or 0.58% against Wednesday's close and its highest level in seven weeks, a fourth consecutive advance. Platinum was bid at $1,753.00, up $23.00 or 1.33%, and palladium at $1,367.00, up $20.00 or 1.48%. Silver was bid at $61.67, down $0.25 or 0.41%, the only one of the four lower on the session, after leading the complex all week with gains of 3.27% on 5 August and 3.2% the session before. The gold to silver ratio widened back to 69.3 from 67.8, undoing two sessions of tightening. Against the 5:58am mark this paper carried on 5 August, $4,157.80, gold added $113.10 an ounce or 2.72% in twenty-four hours. Fine gold at $4,270.90 an ounce is $137.31 a gram against $133.68 the previous session and $130.17 on 4 August; platinum stood at 41.0% of the gold price, down from 42.0%. This paper's own overnight tape recorded gold at $4,276.60 at 4:58am, $5.70 above the 6:03am bid carried here, and read silver as flat at $61.92 rather than down, a divergence recorded rather than resolved. NAT1 and LGD1 were both carried unchanged; the lab-grown reference was not printed as a market because two trackers stood 28% apart at $709 and $555. July non-farm payrolls are released at 8:30am on 7 August, the first full read on American hiring since the Federal Reserve held on 29 July with three dissents; June's print was 57,000.",
  "s":"Kitco / FX Leaders / GoldSilver / BLS"},
 {"d":"diamonds","h":"Alrosa swings to a half-year loss and prepares to idle open pits",
  "t":"Alrosa's first-half 2026 accounts, as reported in English-language coverage of the filing, show revenue of 74.2 billion roubles, about $932.5 million, down 36% year on year, and a net loss of 10.67 billion roubles, about $134.1 million, against a net profit of 39 billion roubles, about $490.1 million, in the first half of 2025. Cost of sales fell 20% to 69.5 billion roubles, about $873.4 million, so revenue fell nearly twice as fast as the cost of production. The comparative half carried about 53.1 billion roubles, some $667.3 million, of non-operating income, including roughly 30 billion roubles, about $377 million, from the sale of Alrosa's stake in Angola's Catoca venture, which flatters the base. The company is preparing to place several open-pit mines into care and maintenance during 2026 and has suspended mining at Severalmaz, which accounts for roughly 10% of Russian diamond output. The 2026 production target of 25 to 26 million carats, down 14% from 29.7 million carats in 2025, is not new: it was set out by the company's head in December 2025, with the stated reason that it was not a question of capacity but of regulating demand and global inventories. For comparison, De Beers' consolidated average realised price fell 32% to $105 a carat across the same half, filed by this paper on 31 July. These figures rest on a single English-language report of the filing and no second outlet has yet carried them.",
  "s":"Sada Elbalad / Interfax (Dec 2025) / De Beers Group"},
 {"d":"retail-tech","h":"Signet gives Blue Nile to a Tiffany merchandising veteran",
  "t":"Signet announced on 5 August that Pam Cloud becomes president of Blue Nile effective 10 August, reporting to Joan Hilson, Signet's chief operating and financial officer. Cloud has more than thirty years in luxury retail, of which more than twenty-five were spent at Tiffany and Co., latterly as senior vice president and chief merchandising officer and a member of the executive committee. She subsequently founded Roseate Jewelry, a direct-to-consumer pearl brand. Signet acquired Blue Nile in 2022 for $360 million. The appointment places a merchant rather than a marketer in charge of a business originally built on price transparency for loose stones, which reads as a decision about assortment and presentation rather than traffic or conversion. It is the second senior jewellery appointment in a week and close to the inverse of the first: Pandora named Andre Branch, a consumer-brands executive with no jewellery background, president of its North America cluster from 15 August, filed by this paper on 5 August. Both new presidents start in mid-August, with the American fourth quarter already substantially bought.",
  "s":"JCK / The Jewelry Wire / Rapaport"},
 {"d":"retail-tech","h":"British buy-now-pay-later came under FCA supervision on 15 July",
  "t":"Deferred payment credit, the interest-free instalment model underpinning buy-now-pay-later, entered the United Kingdom's regulatory perimeter under Financial Conduct Authority supervision on 15 July 2026. The market grew from about £60 million of transaction value in 2017 to more than £13 billion in 2024, with the FCA putting British usage at around 11 million consumers. Lenders entering deferred payment credit agreements must be authorised for the relevant consumer credit activities or hold temporary permission under the temporary permissions regime, and must carry out proportionate affordability checks before extending credit and give consumers clear upfront terms covering payment dates, amounts and the consequence of a missed payment. Consumers gain access to the Financial Ombudsman Service. Firms could register for temporary permission between 15 May and 1 July 2026 and have six months from commencement to apply for full authorisation. The relevance to jewellery is direct: most independents accept a provider's checkout plug-in rather than lending themselves, so the authorisation duty sits with the provider, but the January authorisation deadline is the point at which some smaller providers may withdraw. This is a three-week-old rule change filed now for its forward consequences, not news of the day.",
  "s":"Financial Conduct Authority / GOV.UK / Reed Smith"},
 {"d":"retail-tech","h":"Onyx Partners bids $934 million for 117 J.C. Penney anchor stores",
  "t":"Onyx Partners, a Boston-area private equity firm, has offered $934 million for a portfolio of 117 J.C. Penney stores covering 15.7 million square feet across 35 states, about $8 million a store or roughly $59 a square foot. It is the firm's second attempt; a higher offer of $947 million was rejected in December. Onyx states that financing is fully in place and that it is prepared to close on 25 September. The seller is Copper Property CTL Pass Through Trust, a Jersey City vehicle created after J.C. Penney's 2020 Chapter 11 filing with a mandate to liquidate real estate for the benefit of investors. The relevance to the jewellery trade is the anchor position: J.C. Penney has operated fine jewellery departments for decades, and anchor ownership determines footfall past every specialist jeweller in a mall concourse. An implied price near land-and-shell levels rather than going-concern retail levels indicates a market clearing anchor space on the assumption the current use may not be the final use. The transaction has not closed.",
  "s":"National Jeweler / CoStar / Retail Dive"},
 {"d":"retail-tech","h":"Two thirds of American shoppers used an AI chatbot to shop in the past three months",
  "t":"Attentive's holiday research, conducted online among 600 United States adults and published in the first week of August 2026, finds that 67% of respondents used an AI chatbot such as ChatGPT, Gemini or Perplexity to assist with shopping in the previous three months, rising to 80% among Gen Z respondents. Among AI users the most common activities were researching specific products, comparing brands and features, seeking recommendations and finding deals, with 51% using the tools to compare brands and almost three in five asking questions about specific products. On timing, 62% of consumers will plan holiday purchases before November, 71% expect to start shopping before Black Friday, and 46% plan to begin holiday shopping before November. Two limits belong on the figures: a sample of 600 adults surveyed online is small and skews toward respondents comfortable answering on a screen, the same population most likely to have tried a chatbot, and the survey measures consultation rather than conversion, with no figure establishing that a purchase was completed through a model. Related: the Natural Diamond Council has engaged the agency Artefact on how natural diamonds appear inside large language models, filed by this paper on 5 August.",
  "s":"JCK / Global Toy News / Retail Dive"},
]
wk["entries"] = newent + wk["entries"]
record["updated"] = "6 Aug 2026"
(C/"record.json").write_text(json.dumps(record,ensure_ascii=False,indent=1))
print("wire No.027 written;", len(newent), "record entries prepended into", wk["label"], "- week now", len(wk["entries"]))
