#!/usr/bin/env python3
# Edition No. 048 - wire tape + the record.
import json, pathlib
C = pathlib.Path("content")
w = json.loads((C/"wire.json").read_text())
r = json.loads((C/"record.json").read_text())

w["date_line"] = "Saturday, August 29, 2026"
w["edition"] = "Vol. I - No. 048"
w["tape_ts"] = ("29 Aug 2026 - Kitco, corroborated on TradingEconomics and CNBC - the Editor re-read all four metals "
                "at press time and wrote nothing back: gold $4,454.40, silver $66.253, platinum $1,819.00 and "
                "palladium $1,405.00, each identical to the 05:00 mark. Today is Saturday and spot does not trade; "
                "Kitco's board carries Friday's 13:00 ET print, read live today and confirmed unchanged. On platinum, "
                "TradingEconomics at $1,833.60 sits 0.526% from Kitco's mid while CNBC at $1,820.15 agrees with Kitco, "
                "and the divergent outside reading is disclosed rather than dropped")

w["items"] = [
 {"b":"GOLD LOST $150.10 AND SILVER 5.85%, THE WORST SESSION THIS TAPE HAS RECORDED",
  "t":"Against Thursday's marks of record, gold fell 3.2604% to $4,454.40 and silver 5.8507% to $66.253. In twenty-three sessions since 5 August the next-worst gold day is 0.9259% and the next-worst silver day 2.89%, so Friday is 3.52 and 2.02 times worse than anything before it. Platinum fell 3.3989% to $1,819.00. Palladium rose 1.7378% to $1,405.00, the only riser."},
 {"b":"WARSH PUT A SEPTEMBER RATE RISE BACK ON THE BOARD, AND THE METAL REPRICED",
  "t":"The Federal Reserve chair told Jackson Hole that better summer PCE and CPI readings did not show underlying inflation improving, and that more than half of PCE items have risen above 3% over the past year against 32% in the two decades before the pandemic. CME FedWatch odds on a September hike moved from about 35.5% to 57.5%."},
 {"b":"OFAC MOVED THE GRANDFATHERED RUSSIAN DIAMOND DEADLINE TO 1 SEPTEMBER 2027",
  "t":"General License No. 104B, issued 27 August, adds 365 days to a window that had closed on 1 September 2026. Stones of a carat and above must have left Russia before 1 March 2024 and half-to-one-carat goods before 1 September 2024, so the qualifying parcels will have sat 1,279 and 1,095 days by the new date. No carat weight for the remaining population has been published."},
 {"b":"GIA AND GÜBELIN CONFIRMED ETHIOPIA AS A FOURTH SOURCE OF PARAÍBA TOURMALINE",
  "t":"The two laboratories announced jointly on 27 August, on separate samples, that Ethiopian copper-bearing tourmaline meets the accepted definition. Gübelin first saw the material in early May and GIA in June, later studying a parcel of more than 100 rough and faceted stones. Vanadium, lead and gallium separate it; no thresholds are published yet. SSEF called the same material inconclusive in June."},
 {"b":"CHOW SANG SANG'S PROFIT ROSE 139% ON REVENUE UP 17%, AND THE MARGIN DOUBLED",
  "t":"The half to 30 June took HK$12.88 billion with HK$2.15 billion of profit, a net margin near 16.69% against about 8.17% a year earlier on this desk's arithmetic from the company's own figures. Mainland same-store sales went from 7% to 17% across the two quarters while Hong Kong and Macau fell from 46% to 30%. A net 47 shops closed."},
 {"b":"A SOURCE THIS PAPER CITED WENT DARK AND CAME BACK, AND THE FIGURES CHECK OUT",
  "t":"diamondcitynews.com, cited on five Carat Capital articles, 301-redirected to an unrelated domain when Standards audited it on 28 August. This desk refetched it today: the site answers 200 and the cited Raksha Bandhan article renders. All four Ahmedabad counter figures Standards could not confirm - ₹1.7 lakh and ₹1.02 lakh gold, ₹2.45 lakh and ₹1.17 lakh silver - are present in the source's own Gujarati body text. No correction is required."},
]

for t in w["tape"]:
    if t["code"] == "XAU":
        t["px"], t["chg"], t["dir"] = "4,454.40", "▼ −3.26%", "down"
        t["pts"] = [13,22,29,30,33,32,31,28,30,20]
    elif t["code"] == "XAG":
        t["px"], t["chg"], t["dir"] = "66.253", "▼ −5.85%", "down"
        t["pts"] = [13,23,30,29,28,26,28,27,33,22]
    elif t["code"] == "XPT":
        t["px"], t["chg"], t["dir"] = "1,819.00", "▼ −3.40%", "down"
        t["pts"] = [13,22,33,33,33,33,33,24,33,25]

(C/"wire.json").write_text(json.dumps(w, indent=1, ensure_ascii=False))

ENTRIES = [
 {"d":"gold-metals","h":"Gold falls $150.10 to $4,454.40 and silver 5.85% to $66.253, the worst session on this paper's tape",
  "t":"The Editor re-read all four metals on Kitco at press time on 29 August 2026 and wrote nothing back: gold $4,454.40 the ounce, silver $66.253, platinum $1,819.00 and palladium $1,405.00, each identical to the 05:00 mark filed by the tape desk. Today is Saturday, spot metal does not trade until Sunday evening, and Kitco's board carries an internal timestamp of 13:00 ET Friday across all four, so these are Friday's last prints read live today and confirmed unchanged rather than a new session. Against Thursday's marks of record ($4,604.50, $70.37, $1,883.00 and $1,381.00) gold fell $150.10 or 3.2604%, silver $4.117 or 5.8507%, platinum $64.00 or 3.3989%, and palladium rose $24.00 or 1.7378%. This paper's tape has carried a daily mark of record for all four metals across twenty-three sessions since 5 August 2026. The next-worst gold session on that record is 27 August at 0.9259%, making Friday 3.52 times worse; the next-worst silver session is 19 August at 2.89%, making Friday 2.02 times worse. Silver set the tape's high-water mark of $70.37 on Thursday and gave 5.85% back on Friday. Gold's high-water mark, $4,643.90 on 24 August, now sits $189.50 or 4.0806% above the mark. Kitco's Friday ranges: gold $4,444.80 to $4,629.10, a spread of $184.30 or 4.146% of the low, closing $9.60 off the low and $174.70 below the high; silver $65.998 to $71.230, 7.928% of the low, closing 25.5 cents off the low; platinum $1,815.00 to $1,907.00; palladium $1,304.00 to $1,492.00. Palladium's bid-ask of $40.00 is 2.847% of its bid against gold's 0.0449%, sixty-three times wider. The gold-to-silver ratio moved from 65.43 to 67.23, 2.75% wider in one session. Outside-source divergence disclosed: TradingEconomics read platinum at $1,833.60 against Kitco's mid of $1,824.00, a gap of 0.526%, while CNBC at $1,820.15 agreed with Kitco. Cause named by Federal Reserve chair Kevin Warsh at Jackson Hole on 28 August: summer PCE and CPI readings did not show underlying inflation improving, more than half of PCE items rose above 3% over the past year against 32% in the twenty pre-pandemic years and a post-pandemic peak of 77%, and CME FedWatch odds on a September rise moved from about 35.5% to 57.5%.",
  "s":"Kitco, TradingEconomics and CNBC, read 29 August 2026; Carat Capital daily tape, 5-29 August 2026"},
 {"d":"diamonds","h":"OFAC issues General License No. 104B, moving the grandfathered Russian diamond deadline to 1 September 2027",
  "t":"The United States Treasury's Office of Foreign Assets Control issued General License No. 104B on 27 August 2026, moving to 1 September 2027 a deadline that had stood at 1 September 2026, an extension of 365 days. The licence covers loose, nonindustrial Russian-origin diamonds purchased before the sanctions took effect and not yet entered into the American market. Stones of one carat and above must have left Russia before 1 March 2024; stones between 0.50 and 1.00 carat before 1 September 2024. General License No. 103, governing imports of diamond jewellery, is unchanged. Measured to the new deadline, a qualifying one-carat stone will have been outside Russia at least 1,279 days, three and a half years, and a qualifying half-carat stone at least 1,095 days, three years to the day. Neither the licence as reported nor any trade body reached by this desk publishes a carat weight, value or count for the population still waiting, so the extension cannot be priced. The licence number itself is the second amendment to General License No. 104. This desk fetched OFAC's own recent-actions listing on 29 August 2026; the page returned HTTP 200 but renders its results dynamically and produced no diamond entry to a plain fetch, so the licence detail is carried from Rapaport's report of 27 August 2026, which the bureau independently confirmed against the page's own publication metadata and against direct text matches on the licence number and the new date.",
  "s":"Rapaport News, 27 August 2026; OFAC recent-actions listing, fetched 29 August 2026"},
 {"d":"gemstones","h":"GIA and Gübelin confirm Ethiopia as a fourth source of Paraíba tourmaline, three months after SSEF called it inconclusive",
  "t":"The Gemological Institute of America and the Gübelin Gem Lab announced jointly on 27 August 2026 that Ethiopia is a new source of copper-bearing tourmaline meeting the widely accepted definition of Paraíba tourmaline, which had previously been produced in Brazil, Nigeria and Mozambique. The two laboratories reached the conclusion independently and on separate material. Gübelin first encountered stones with an unfamiliar chemical signature in early May 2026. GIA began examining goods represented as Ethiopian in June 2026 and later received a parcel of more than one hundred rough and faceted samples. Both name elevated concentrations of vanadium, lead and gallium as the separating markers and describe them as measurable determinations; neither has published thresholds, and the detailed findings are going to Gems & Gemology. Colours reported run from blue to bluish green, violet, purple and colourless, with colour zoning and compositional variation within single stones. In June 2026 the Swiss Gemmological Institute SSEF reported credible accounts of an Ethiopian deposit and said its own preliminary trace-element work on submitted stones showed considerable overlap with previously known localities, particularly Brazil, calling origin determination on some specimens difficult and in some cases inconclusive. No price, parcel value or carat weight has been published for Ethiopian material. For price context this paper reported on 30 July 2026, from Rapaport's January survey, that Mozambican Paraíba had moved from around $7,000 a carat to between $10,000 and $12,000 a carat.",
  "s":"GIA and Gübelin joint statement via JCK, 27 August 2026; SSEF, June 2026; National Jeweler, 23 June 2026"},
 {"d":"retail-tech","h":"Chow Sang Sang's half to 30 June takes HK$12.88 billion with profit up 139%, and the net margin roughly doubles",
  "t":"Chow Sang Sang reported on 27 August 2026 that revenue for the six months to 30 June 2026 was HK$12.88 billion, about $1.64 billion, up 17% year on year, with retail sales of HK$12.71 billion or $1.62 billion, up 18%, which is 98.68% of the group figure. Profit was HK$2.15 billion, about $274.6 million, up 139%. Working back from those figures, the comparable half produced roughly HK$11.01 billion of revenue and about HK$900 million of profit, a net margin near 8.17% against 16.69% this half, on this desk's arithmetic from the company's own published percentages. Same-store sales grew 11% in mainland China, made of 7% in the first quarter and 17% in the second, and 38% in Hong Kong and Macau, made of 46% then 30%. A net 47 shops closed, predominantly on the mainland. The company said key collections including Cultural Blessings and Noir recorded strong growth. Divergence disclosed: this paper reported on 22 July 2026, from the company's earlier quarterly update, a net 49 shops closed in the first half ending June at 776 stores; the interim results give 47 for the same six months. The two are not reconciled from the material this desk holds, and the likeliest explanations, a group-versus-mainland scope difference or a revision between operational update and audited accounts, are neither confirmed. The release carries no split between gold and gem-set jewellery. Implied exchange rates from the company's own dual figures are HK$7.8537 and HK$7.8296 to the dollar.",
  "s":"Rapaport News, 27 August 2026; Carat Capital, 22 July 2026"},
 {"d":"retail-tech","h":"A Gujarat gold board prints ₹1,63,790 for all three cities, and two of its three karat prices are pure division",
  "t":"TV9 Gujarati published a gold and silver rate board on 27 August 2026, bylined to Dhruval Shah and timestamped 9.45 a.m., putting 24-carat gold at ₹1,63,790 per ten grams, 22-carat at ₹1,50,140 and 18-carat at ₹1,22,840, and repeating those identical figures for Ahmedabad, Surat and Rajkot. The page credits Groww as its data source and carries its own disclaimer that the information rests on media reports. This desk fetched the page directly on 29 August 2026 and confirmed each figure and the date in the Gujarati body text rather than in a listing. The karat lines are pure ratio: ₹1,63,790 times 22/24 is ₹1,50,140.83, printed as ₹1,50,140, and times 18/24 is ₹1,22,842.50, printed as ₹1,22,840, both rounded to the nearest ten rupees and neither carrying the alloy, wastage or making premium a real 22-carat counter charges. The same page puts the ten-day high at ₹1,64,020 on 24 August and the ten-day low at ₹1,55,020 on 19 August, a range of ₹9,000 or 5.8057% of the low, and 27 July at ₹1,45,940 against 27 August at ₹1,63,790, a gain of ₹17,850 or 12.2311% in a month. The 24 August peak falls on the same date this paper's own tape recorded its gold high-water mark of $4,643.90, from an entirely separate source. The board's 27 August reading predates Friday's 3.2604% fall in spot gold. Per gram the 24-carat figure is ₹16,379.",
  "s":"TV9 Gujarati, 27 August 2026 (Gujarati), fetched and confirmed 29 August 2026"},
]
r["weeks"][0]["entries"][:0] = ENTRIES
r["updated"] = "29 Aug 2026"
(C/"record.json").write_text(json.dumps(r, indent=1, ensure_ascii=False))
print("wire edition", w["edition"], "| record entries wk0", len(r["weeks"][0]["entries"]))
