#!/usr/bin/env python3
# Edition No. 045 - editorial.json entries for the six new slugs.
import json, pathlib
C = pathlib.Path("content")
ed = json.loads((C/"editorial.json").read_text())

def spec(slug, cap, cells, fig, flow, desk_split, nxt):
    for f in flow:
        if "pull" in f:
            assert len(f["pull"]["q"].split()) <= 15, (slug, len(f["pull"]["q"].split()))
    d = {"strip": {"cap": cap, "cells": cells}, "flow": flow,
         "desk": {"split": desk_split}, "next": nxt}
    if fig: d["figs"] = [fig]
    ed[slug] = d

# ---- 1. Doyle (lead)
spec("one-eighty-percent-on-the-sapphires",
"By the numbers - Doyle New York, Important Jewelry",
[{"fig":"$457,700","delta":"+30.8%","dir":"up","lab":"top lot, 12.46ct D VS2"},
 {"fig":"2.80x","delta":"+180%","dir":"up","lab":"1890 sapphires over high estimate"},
 {"fig":"$8M+","lab":"whole sale, per the house"},
 {"fig":"4 of 5","delta":"beat","dir":"up","lab":"top lots clearing the book"},
 {"fig":"$36,733","lab":"per carat, the leading ring"}],
{"no":"Plate I","title":"Top five lots - price as a multiple of the high estimate",
 "rows":[{"l":"1890 SAPPHIRE EARRINGS","v":280,"d":"2.80x","hi":True},
         {"l":"CARTIER PANTHERE","v":191,"d":"1.91x"},
         {"l":"JAR RING, c.1980","v":138,"d":"1.38x"},
         {"l":"12.46CT DIAMOND RING","v":131,"d":"1.31x"},
         {"l":"TIFFANY FLEURAGE","v":85,"d":"0.85x"}],
 "note":"The diamond met the book. The coloured stones left it behind",
 "cap":"Four of the top five cleared their high estimates; the one that did not was the only lot already estimated in six figures at the top. Carat Capital graphics desk, on Doyle results reported by Rapaport. &nbsp;CC/2026/045"},
[{"sub":"A cautious book, and a room that found the gaps in it.","n":"§1"},
 {"p":0},
 {"sub":"The multiple sits where the headline does not.","n":"§2"},
 {"p":1},
 {"pull":{"q":"The diamond met its estimate. The sapphires embarrassed it.","attr":"The Auctions Desk"}},
 {"sub":"One lot in five stayed inside its range.","n":"§3"},
 {"p":2},
 {"p":3,"split":"The house priced a pair of 1890 sapphire earrings"},
 {"also":{"t":"Bonhams Sydney runs 39 of its first 48 lots away","href":"a-thirty-nine-of-forty-eight.html"}}],
"A jeweller pricing estate stock this autumn",
{"lead":{"slug":"three-times-the-royal-brooch","tag":"Auctions","blurb":"A palace provenance led the write-ups at Elmwood's and finished fourth of four on price."},
 "minis":[{"slug":"thirty-nine-of-forty-eight","tag":"Auctions"},{"slug":"four-times-melt","tag":"Auctions"}]})

# ---- 2. Elmwood's
spec("three-times-the-royal-brooch",
"By the numbers - Elmwood's, London, 19 August",
[{"fig":"GBP 23,750","lab":"Verdura brooch, royal provenance"},
 {"fig":"GBP 75,000","delta":"3.16x","dir":"up","lab":"Van Cleef feather brooch, 1927"},
 {"fig":"$1.363","lab":"one rate across every conversion"},
 {"fig":"4th of 4","lab":"where the palace piece finished"},
 {"fig":"$29,455","lab":"per carat of diamond in the Verdura"}],
{"no":"Plate I","title":"Named lots at Elmwood's - hammer, pounds sterling",
 "rows":[{"l":"VAN CLEEF FEATHER, 1927","v":75000,"d":"GBP 75,000","hi":True},
         {"l":"EGYPTIAN REVIVAL TIARA","v":65000,"d":"GBP 65,000"},
         {"l":"CARTIER TUTTI FRUTTI","v":60000,"d":"GBP 60,000"},
         {"l":"VERDURA, ROYAL PROVENANCE","v":23750,"d":"GBP 23,750"}],
 "note":"The lot everyone wrote about is the cheapest one named",
 "cap":"Four lots named in the sale report, ranked by hammer price. The royal brooch that led the coverage sold for less than a third of the top lot. Carat Capital graphics desk. &nbsp;CC/2026/045"},
[{"sub":"A unicorn, a countess, and fifty years at the palace.","n":"§1"},
 {"p":0},
 {"sub":"Three lots in the same report sold for more.","n":"§2"},
 {"p":1},
 {"pull":{"q":"The palace sells the story. The 1927 feather sells for more.","attr":"The Auctions Desk"}},
 {"sub":"The conversions reconcile to one rate.","n":"§3"},
 {"p":2},
 {"p":3,"split":"No parcel of 1.10 carats"},
 {"also":{"t":"$457,700 led Doyle, and an 1890 sapphire pair beat its estimate by 180%","href":"a-one-eighty-percent-on-the-sapphires.html"}}],
"For anyone consigning estate goods this autumn",
{"lead":{"slug":"one-eighty-percent-on-the-sapphires","tag":"Auctions","blurb":"Four of Doyle's top five beat their high estimates, and a pair of 1890 sapphires beat theirs by 180%."},
 "minis":[{"slug":"thirteen-thousand-for-costume","tag":"Auctions"},{"slug":"trophy-lots-carry-the-half","tag":"Auctions"}]})

# ---- 3. Jaipur
spec("kagem-comes-to-jaipur",
"By the numbers - 13th India Rough Gemstones Sourcing Show",
[{"fig":"19 days","lab":"24 August to 11 September"},
 {"fig":"60+","lab":"Indian manufacturers, council's count"},
 {"fig":"$146.08","lab":"Kagem's May emerald average, a carat"},
 {"fig":"$26.8M","lab":"that London auction, reported here 24 July"},
 {"fig":"0","lab":"prices published from Jaipur"}],
{"no":"Plate I","title":"What the council's release actually publishes",
 "rows":[{"l":"MANUFACTURERS ATTENDING","v":60,"d":"60+","hi":True},
         {"l":"DAYS THE SHOW RUNS","v":19,"d":"19"},
         {"l":"SOURCE MINERS NAMED","v":1,"d":"1"},
         {"l":"PRICES OR VOLUMES GIVEN","v":0,"d":"0"}],
 "note":"A confirmed event, confirmed officials, and no confirmed commerce",
 "cap":"Everything countable in the release. There is no value, no carat weight, no lot count and no result, because the show does not close until 11 September. Carat Capital graphics desk. &nbsp;CC/2026/045"},
[{"sub":"Nineteen days, one Zambian miner, and sixty benches.","n":"§1"},
 {"p":0},
 {"sub":"This paper has already priced the goods.","n":"§2"},
 {"p":1},
 {"pull":{"q":"Access is not a price. No result exists until September.","attr":"The Gemstones Desk"}},
 {"sub":"The travel goes away. The currency does not.","n":"§3"},
 {"p":2},
 {"p":3,"split":"The figure of more than 60 manufacturers"},
 {"also":{"t":"$102.9 million, up 72%: Gemfields' emeralds cover for its rubies","href":"a-gemfields-covers-the-ruby.html"}}],
"This desk will look for a result after 11 September",
{"lead":{"slug":"emeralds-hold-at-146","tag":"Gemstones","blurb":"Kagem's higher-quality emerald book cleared 99% by weight at $146.08 a carat in London."},
 "minis":[{"slug":"gemfields-covers-the-ruby","tag":"Gemstones"},{"slug":"sixty-six-dollars-a-carat","tag":"Gemstones"}]})

# ---- 4. Fossil
spec("watches-were-the-line-that-held",
"By the numbers - Fossil Group, quarter to 4 July 2026",
[{"fig":"$209.7M","delta":"-4.9%","dir":"down","lab":"net sales, the quarter"},
 {"fig":"-1.5%","delta":"","lab":"traditional watches, the quarter"},
 {"fig":"+0.4%","delta":"up","dir":"up","lab":"traditional watches, six months"},
 {"fig":"-31.1%","delta":"","lab":"leathers, the quarter"},
 {"fig":"84.5%","delta":"from 81.6%","dir":"up","lab":"watches as a share of sales"}],
{"no":"Plate I","title":"Fall by product line - quarter to 4 July, percent",
 "rows":[{"l":"LEATHERS","v":31.1,"d":"-31.1%","hi":True},
         {"l":"JEWELLERY","v":11.2,"d":"-11.2%"},
         {"l":"NET SALES, ALL LINES","v":4.9,"d":"-4.9%"},
         {"l":"TRADITIONAL WATCHES","v":1.5,"d":"-1.5%"},
         {"l":"SMARTWATCHES","v":0.9,"d":"-0.9%"}],
 "note":"Half the company's decline came out of a line worth 6% of it",
 "cap":"Every line fell, and the two that fell hardest were not watches. Bars show the size of the fall, not the size of the line. Carat Capital graphics desk, on the company's 10-Q. &nbsp;CC/2026/045"},
[{"sub":"A top line that circulated, and a table nobody read.","n":"§1"},
 {"p":0},
 {"sub":"The decline is in leather and jewellery, not in watches.","n":"§2"},
 {"p":1},
 {"pull":{"q":"The watches held. The leather goods lost a third.","attr":"The Watches Desk"}},
 {"sub":"Across six months the watch line rose.","n":"§3"},
 {"p":2},
 {"p":3,"split":"On the jewellery line itself"},
 {"also":{"t":"560 applicants for 27 places: the watchmaker shortage","href":"a-five-sixty-for-twenty-seven.html"}}],
"The transferable point is about substitution",
{"lead":{"slug":"five-sixty-for-twenty-seven","tag":"Watches","blurb":"Rolex's Dallas school took 27 of more than 560 applicants, and the trade is short of benches."},
 "minis":[{"slug":"four-groups-in-the-black","tag":"Watches"},{"slug":"independents-pass-lvmh","tag":"Watches"}]})

# ---- 5. Israeli Diamond Institute (no plate - nothing countable to plot)
spec("only-the-last-test-was-decisive",
"By the numbers - one rough stone, four examinations",
[{"fig":"18 Aug","lab":"date the stone was submitted"},
 {"fig":"4","lab":"examinations before a verdict"},
 {"fig":"Type IIa","lab":"what infrared classified it as"},
 {"fig":"1","lab":"source, the testing laboratory itself"},
 {"fig":"0","lab":"carat weight published"}],
None,
[{"sub":"A stone that looked like ordinary rough.","n":"§1"},
 {"p":0},
 {"sub":"Four steps, and only the fourth settled it.","n":"§2"},
 {"p":1},
 {"pull":{"q":"A green light at the sorting table is not a verdict.","attr":"The Diamonds Desk"}},
 {"sub":"Rough is where the defences were never built.","n":"§3"},
 {"p":2},
 {"p":3,"split":"The institute also states"},
 {"also":{"t":"DNA on the parcel: Provenance Proof marks melee","href":"a-dna-on-the-parcel.html"}}],
"A dealer buying rough on visual screening alone",
{"lead":{"slug":"dna-on-the-parcel","tag":"Retail & Tech","blurb":"Gubelin's subsidiary marks polished melee with synthetic DNA, and rough defeats the method."},
 "minis":[{"slug":"five-ninety-four-from-china","tag":"Diamonds"},{"slug":"gia-lights-up-fluorescence","tag":"Diamonds"}]})

# ---- 6. The tape
spec("two-sessions-and-twenty-one-sixty",
"By the numbers - the tape, 26 August, 05:59 ET",
[{"fig":"$4,622.30","delta":"-0.26%","dir":"down","lab":"gold, written back at press time"},
 {"fig":"$68.55","delta":"+0.99%","dir":"up","lab":"silver, written back"},
 {"fig":"-$21.60","delta":"two sessions","dir":"down","lab":"gold's give-back since Monday"},
 {"fig":"67.43","delta":"from 68.27","dir":"down","lab":"gold to silver ratio"},
 {"fig":"6th","lab":"session platinum and palladium held"}],
{"no":"Plate I","title":"How far apart the two pricing sources sit, by metal",
 "rows":[{"l":"PALLADIUM","v":1.40,"d":"1.40%","hi":True},
         {"l":"PLATINUM","v":0.83,"d":"0.83%"},
         {"l":"SILVER","v":0.19,"d":"0.19%"},
         {"l":"GOLD","v":0.033,"d":"0.033%"}],
 "note":"Two metals agree and get written. Two do not and are held",
 "cap":"Kitco against TradingEconomics at press time. A mark moves only when the second page corroborates it; the white metals have not corroborated for six sessions. Carat Capital graphics desk. &nbsp;CC/2026/045"},
[{"sub":"Two metals re-read, two written back.","n":"§1"},
 {"p":0},
 {"sub":"Gold has given back two sessions running.","n":"§2"},
 {"p":1},
 {"pull":{"q":"A gram moved more than the margin on the piece.","attr":"The Metals Desk"}},
 {"sub":"Silver went the other way and the ratio narrowed.","n":"§3"},
 {"p":2},
 {"p":3,"split":"Both were checked against Kitco's own day ranges"},
 {"also":{"t":"1,004.21 in Shanghai, and five bank counters spread 16.60 yuan apart","href":"a-ten-oh-four-twenty-one.html"}}],
"The number a bench should carry out of this morning",
{"lead":{"slug":"ten-oh-four-twenty-one","tag":"Gold & Metals","blurb":"Shanghai's Au99.99 closed at 1,004.21 yuan a gram, and it is a return rather than a record."},
 "minis":[{"slug":"four-metals-four-write-backs","tag":"Gold & Metals"},{"slug":"the-platinum-hold-ends","tag":"Gold & Metals"}]})

(C/"editorial.json").write_text(json.dumps(ed, indent=1, ensure_ascii=False))
print("editorial entries now", len(ed))
