#!/usr/bin/env python3
import json, pathlib
C = pathlib.Path("content")
wire = json.loads((C/"wire.json").read_text())
record = json.loads((C/"record.json").read_text())

wire["date_line"] = "Friday, August 7, 2026"
wire["edition"] = "Vol. I — No. 028"
wire["tape_ts"] = "7 Aug 2026, 5:58am New York · Kitco spot · change against Thursday's close"
wire["items"] = [
 {"b":"FIFTEEN YEARS, NO INDIAN TAX","t":" — India's Lok Sabha passed the Taxation and Other Laws (Amendment) Bill, 2026 on 6 August, proposing to exempt qualifying foreign sellers of rough diamonds from Indian income tax from 1 October 2026 to 31 March 2041 where the sale takes place in a Special Notified Zone; the zones that matter are inside the Bharat Diamond Bourse in Mumbai and the Surat Diamond Bourse, and the class covers miners, brokers, aggregators, auction operators and sightholders. It still requires Rajya Sabha passage and presidential assent, with no hearing date set"},
 {"b":"FIFTH SESSION, EVERY METAL UP","t":" — At 5:58am New York gold bid $4,314.50, up $75.20 or 1.77%, a fifth consecutive advance and above Thursday's seven-week high; platinum $1,772.00, up $54.00 or 3.14%; palladium $1,382.00, up $29.00 or 2.14%. Against the $4,270.90 this paper carried on Thursday, gold has added $43.60 an ounce, or 1.02%, in twenty-four hours"},
 {"b":"SILVER TAKES IT BACK, UP 4.71%","t":" — Silver bid $64.29, up $2.89 or 4.71%, the largest single-session move of the four metals and a full reversal of Thursday's 0.41% decline; the gold to silver ratio tightens to 67.1 from 69.3. This desk wrote on Thursday that silver turning red beneath a gold high was the clearest internal warning the tape had printed all week, and records that call against the print that followed it"},
 {"b":"PAYROLLS AT HALF PAST EIGHT","t":" — The Bureau of Labor Statistics releases July non-farm payrolls at 8:30am Friday, after this edition closes. ADP put July private hiring at 44,000 against about 50,000 expected, JOLTS came in softer and initial claims rose to 199,000; the CME FedWatch tool has September's move at 56.9% against 63.4% a week earlier. Iran says it has reached an understanding with Oman on a proposed Hormuz shipping lane, and has been explicit that it is a temporary route rather than a full reopening"},
 {"b":"ONE THIRTY-TWO AGAINST THREE THIRTY-NINE","t":" — China Gold Association half-year figures put Chinese gold jewellery consumption at 132.13 tonnes, down 33.88%, against bar and coin demand of 339.34 tonnes, up 28.42%, with total consumption up 1.23% to 511.41 tonnes; the World Gold Council put the same half at about 136 tonnes and a roughly 30% fall, a gap of some four tonnes on differing definitions that this desk carries rather than reconciles"},
 {"b":"TWENTY-TWO THIRTY-EIGHT AN ORDER","t":" — Brilliant Earth second-quarter revenue rose 6% to $115.1 million on a 2.1% fall in total orders, with average order value up 8% to $2,238 and gross margin at 57.9%, a 360 basis point sequential improvement; net income was $0.8 million against a $1.1 million loss, fine jewellery bookings grew 32%, and full-year guidance was raised to $459 million to $462 million with the third quarter guided to roughly flat sales"},
 {"b":"THE FOURTEEN PERCENT THAT ISN'T","t":" — The World Platinum Investment Council projects Chinese platinum jewellery down 14% in 2026 and global platinum jewellery down 6%, but attributes the Chinese figure to an unrepeated second-quarter 2025 stock build; excluding it, Chinese fabrication shows a small year-on-year increase. WPIC also forecasts a fourth consecutive annual market deficit for 2026 at 297,000 ounces"},
 {"b":"TWENTY-NINE NINETY-NINE AT THE CHAIR","t":" — Claire's is relaunching in-store piercing across the United States and Canada from August, its second overhaul of that service in three years, and adding lab-grown diamond and coloured gemstone studs to the starter assortment; kits begin at $29.99 with the piercing free, with 14-carat white gold lab-grown studs at 0.10 carats total weight sold as complete kits"},
 {"b":"DUBAI RETAIL SPREADS BY AED 7.25","t":" — Khaleej Times had Dubai 24-carat gold at AED 517.50 a gram on Friday morning while this paper's own metals desk read AED 510.25 the same day and the overnight desk AED 514.00 on Thursday, a spread of AED 7.25 a gram between two readings of the same session. Both figures are printed and neither is picked. On the diamond lines NAT1 and LGD1 are carried unchanged, the lab-grown reference holding at $709 on CaratRadar for a third straight day against $536 on a second tracker"},
]
wire["tape"] = [
 {"name":"Gold / oz","code":"XAU","px":"4,314.50","chg":"▲ +1.77%","dir":"up",
  "pts":[15,14,15,16,15,16,15,18,19,21]},
 {"name":"Natural 1ct (RAPI proxy)","code":"NAT1","px":"5,232.00","chg":"— unch.","dir":"flat",
  "pts":[13,13,13,13,13,13,13,13,13,13]},
 {"name":"Lab-grown 1ct wholesale","code":"LGD1","px":"727.00","chg":"— unch.","dir":"flat",
  "pts":[13,13,13,13,13,13,13,13,13,13]},
 {"name":"Platinum / oz","code":"XPT","px":"1,772.00","chg":"▲ +3.14%","dir":"up",
  "pts":[16,15,15,17,16,17,18,19,20,22]},
 {"name":"Silver / oz","code":"XAG","px":"64.29","chg":"▲ +4.71%","dir":"up",
  "pts":[17,17,16,16,15,16,17,19,18,22]},
]
(C/"wire.json").write_text(json.dumps(wire,ensure_ascii=False,indent=1))

# ---- record: prepend into the current week ----
wk = record["weeks"][0]
assert wk["label"] == "This week — August 3", wk["label"]

newent = [
 {"d":"diamonds","h":"India's lower house passes a fifteen-year tax exemption for foreign rough sellers",
  "t":"The Taxation and Other Laws (Amendment) Bill, 2026 passed the Lok Sabha on 6 August 2026, proposing an income-tax exemption for qualifying non-resident companies selling rough diamonds in India between 1 October 2026 and 31 March 2041, a fifteen-year window. The exemption is conditional on the sale taking place inside a Special Notified Zone; the two relevant zones sit inside the Bharat Diamond Bourse in Mumbai and the Surat Diamond Bourse. The class of qualifying seller covers miners, brokers, aggregators, auction operators and sightholders, and a qualifying company must furnish information when required. The existing regime offers a safe harbour presuming taxable profit at 1.25% of gross revenue, with Indian corporate tax at rates reaching about 33% of profit where the safe harbour is not elected. The stated policy aim is to reduce the movement of rough and encourage direct sales within India, positioning Mumbai and Surat against Dubai and Antwerp. The Gem and Jewellery Export Promotion Council welcomed the introduction. The Bill has cleared the lower house only and requires Rajya Sabha passage and presidential assent before any exemption takes effect; no date has been set for a hearing in the upper house, which makes the 1 October start date an intention rather than a commitment. For comparison, this paper reported on 2 August that a single tender cleared at 100% in Dubai against 75% in Johannesburg, and on 15 July that Dubai's diamond trade was worth $41.7 billion in a year.",
  "s":"Rapaport / IDEX Online / GJEPC via Mines to Market"},
 {"d":"gold-metals","h":"All four metals rise on a fifth session, silver up 4.71% into the payrolls print",
  "t":"At 5:58am New York time on 7 August, Kitco's spot page had gold bid at $4,314.50 an ounce, up $75.20 or 1.77% against Thursday's close, a fifth consecutive advance and above the seven-week high carried the previous day. Silver was bid at $64.29, up $2.89 or 4.71%, the largest single-session move of the four; platinum at $1,772.00, up $54.00 or 3.14%; palladium at $1,382.00, up $29.00 or 2.14%. The gold to silver ratio tightened to 67.1 from 69.3, more than reversing Thursday's widening. Against the 6:03am mark this paper carried on 6 August, gold added $43.60 an ounce or 1.02% and silver $2.62 or 4.25% in twenty-four hours. Fine gold at $4,314.50 an ounce is $138.72 a gram against $137.31 the previous session; platinum stood at 41.1% of the gold price against 41.0%. This desk wrote on 6 August that silver turning red beneath a gold high was the clearest internal warning the tape had printed all week; silver reversed that decline in full the following session, and the call is recorded here against the print that followed it. Context: Iran said it had reached an understanding with Oman on a proposed shipping route through the Strait of Hormuz, describing it as a temporary route and not a full reopening; ADP put July private hiring at 44,000 against about 50,000 expected, JOLTS was softer and initial claims rose to 199,000; the CME FedWatch tool showed September at 56.9% against 63.4% a week earlier. July non-farm payrolls were scheduled for 8:30am on 7 August, after this edition closed. Two divergences are recorded rather than resolved: this paper's own overnight tape read gold at $4,304.40 at 4:58am, $10.10 below the 5:58am bid, with silver at $64.16 and platinum at $1,763.00 and palladium identical at $1,382.00 on matching previous closes; and Dubai 24-carat retail was quoted at AED 517.50 a gram by Khaleej Times on 7 August, AED 510.25 by this paper's metals desk the same day and AED 514.00 by the overnight desk on 6 August. NAT1 and LGD1 were carried unchanged, the lab-grown reference holding at $709 on CaratRadar for a third straight day against $536 on StoneAlgo, a spread of roughly 24%.",
  "s":"Kitco / FXStreet / Khaleej Times / BLS"},
 {"d":"gold-metals","h":"China Gold Association puts first-half jewellery down 33.88% and bars up 28.42%",
  "t":"China Gold Association half-year figures, reported 6-7 August 2026, put national gold consumption at 511.41 tonnes for the first half of 2026, up 1.23% year on year. Gold jewellery consumption fell 33.88% to 132.13 tonnes while gold bar and coin consumption rose 28.42% to 339.34 tonnes, making investment metal roughly two and a half times the jewellery figure. The association attributes the divergence to elevated and volatile gold prices and to the rollout of new domestic gold tax policies, with temporary price corrections boosting bar sales through banks. These figures sit alongside, and do not match, the World Gold Council data this paper filed on 3 August, which put Chinese jewellery demand at roughly 136 tonnes across the half, a fall of about 30%, and the second quarter at 50.0 tonnes, the weakest since 2004. The gap between the two authorities is about four tonnes and nearly four percentage points, arising from differing definitions between a consumption series and a demand series; both are printed here and neither is preferred. Related context previously filed by this paper: Indian jewellery demand of 75.1 tonnes in the second quarter, down 15% by weight and up about 50% by value (31 July), and Luk Fook's record profit driven by fixed-price design rather than gram weight (5 August).",
  "s":"China Gold Association via China.org.cn / China Daily / World Gold Council"},
 {"d":"retail-tech","h":"Brilliant Earth returns to profit on a bigger ticket and fewer orders",
  "t":"Brilliant Earth reported second-quarter 2026 revenue of $115.1 million, up 6% year on year, on a 2.1% decline in total orders, with average order value up 8% to $2,238. Net income was $0.8 million against a net loss of $1.1 million in the same quarter a year earlier. Gross margin was 57.9%, a 360 basis point sequential improvement. Fine jewellery bookings grew 32% year on year. The company raised full-year revenue guidance to $459 million to $462 million and guided the third quarter to roughly flat sales with adjusted EBITDA between $3 million and $5 million. The composition is the result: revenue growth came from ticket rather than customer count, which concentrates the quarter in existing higher-income demand and leaves no volume growth underneath to absorb a trim in that cohort. The pattern matches other results filed by this paper in the same period, including US jewellery revenue rising while tonnage fell (3 August) and Luk Fook's fixed-price mix carrying a record profit (5 August).",
  "s":"Rapaport / GlobeNewswire company release / JCK"},
 {"d":"gold-metals","h":"WPIC's 14% Chinese platinum jewellery decline is a base effect, not a demand fall",
  "t":"The World Platinum Investment Council projects Chinese platinum jewellery demand down 14% year on year in 2026 and global platinum jewellery demand down about 6%. The council attributes the Chinese figure to an unrepeated and exceptionally high stock build in the second quarter of 2025, when Chinese fabricators bought platinum ahead of a gold price that had made their usual metal unaffordable; excluding that atypical inventory build, Chinese platinum jewellery fabrication would show a small year-on-year increase. The global 6% contraction reflects North American and European growth consolidating after strong years and Indian demand facing tariff-related headwinds, with the largest single contributor being the Chinese comparison. WPIC separately forecasts a fourth consecutive annual platinum market deficit for 2026, with supply falling short of demand by 297,000 ounces. Against this, platinum spot was bid at $1,772.00 an ounce at 5:58am New York on 7 August, up 3.14% on the session and standing at 41.1% of the gold price. The general caution applies beyond platinum: any 2026 comparison against 2025 in this trade is a comparison against a year in which buyers front-ran the gold price.",
  "s":"World Platinum Investment Council via CME Group / WPIC press release / Kitco"},
 {"d":"retail-tech","h":"Claire's puts lab-grown diamond studs on a $29.99 piercing counter",
  "t":"Claire's is relaunching its in-store piercing experience across the United States and Canada from August 2026, the second overhaul of that service in three years, and has expanded the starter stud assortment to include lab-grown diamonds and coloured gemstones alongside existing gold and steel options. Piercing kits start at $29.99 with the piercing itself free on kit purchase. The lab-grown range includes 14-carat white gold studs at 0.10 carats total weight, sold as complete kits with aftercare solution. The significance is the price tier rather than the material: at this level grown diamond functions as a finish and hypoallergenic setting specification rather than as a gemstone purchase, and the competitive displacement falls on cubic zirconia and surgical steel rather than on natural diamond. It is the clearest published evidence to date of grown material reaching mass-market starter pricing, and follows this paper's earlier coverage of grown wholesale price declines and of retailers tiering their floors between lab-grown for everyday and natural for rarity.",
  "s":"National Jeweler / Forbes / Retail Dive / Claire's"},
]
wk["entries"] = newent + wk["entries"]
record["updated"] = "7 Aug 2026"
(C/"record.json").write_text(json.dumps(record,ensure_ascii=False,indent=1))
print("wire No.028 written;", len(newent), "record entries prepended into", wk["label"], "- week now", len(wk["entries"]))
