#!/usr/bin/env python3
import json, pathlib
C = pathlib.Path("content")
wire = json.loads((C/"wire.json").read_text())
record = json.loads((C/"record.json").read_text())
articles = json.loads((C/"articles.json").read_text())

# ---- standards housekeeping: caratcheck 2026-08-14 §4 flagged two figures on
# ---- a-the-platinum-hold-ends attributed to the right organisation but the wrong page.
# ---- Not a FOR CORRECTION TODAY item and no figure is wrong, so no correction note is
# ---- printed; the two specific source pages are added to the article's sources list.
fixed = False
for a in articles:
    if a["slug"] == "the-platinum-hold-ends":
        have = {s["url"] for s in a["sources"]}
        for t, u in [
            ("Platinum — price, chart, historical data (cited for the $1,737.70 reading of 14 August 2026)",
             "https://tradingeconomics.com/commodity/platinum"),
            ("Palladium prices today per ounce — JM Bullion (cited for the $1,336.71 reading of 14 August 2026)",
             "https://www.jmbullion.com/charts/palladium-price/"),
        ]:
            if u not in have:
                a["sources"].append({"title": t, "url": u}); fixed = True
(C/"articles.json").write_text(json.dumps(articles, ensure_ascii=False, indent=1))
print("platinum-hold-ends citation completeness fix applied:", fixed)

wire["date_line"] = "Monday, August 17, 2026"
wire["edition"] = "Vol. I — No. 036"
wire["tape_ts"] = "17 Aug 2026, 5:59am New York · Kitco live board · Editor's press-time read, all four metals written back to the tape"
wire["items"] = [
 {"b":"TWO SOTHEBY'S JEWEL SALES CLOSED AND NEITHER HAS PUBLISHED A NUMBER","t":" — The Gem Drop August closed online in New York on 13 August after four days of bidding. Four days on, Sotheby's own results index lists it as past and shows no total, no sell-through rate and no top lot. The Arcade Sale in Hong Kong, which ran 31 July to 6 August, is listed the same way and has been for eleven days. Neither is particular to this month: the Gem Drop July closed on 16 July and thirty-two days later its page carries no result either. The house's landing page for the series carries a heading for past auctions with nothing underneath it. One limit is stated rather than buried: Sotheby's builds parts of these pages with scripts this desk's fetch does not execute, so this is what the public page gives a reader, not proof no figure exists inside the house"},
 {"b":"THE SAME HOUSE COUNTS WHEN IT WANTS TO","t":" — Sotheby's New York High Jewelry sale on 13 June made $31.4 million with 95% of lots sold, led by a $3.2 million Graff ring set with a 35-carat D-colour diamond, figures this paper printed on 24 July. The house reported a $4.4 billion first half for 2026 with private sales at a record $826 million. An auction house that publishes a total for a trophy night and a half-year figure for its owners is not a house that cannot count an eleven-lot online sale. The Gem Drop's distinguishing feature is that it charges no buyer's premium, which this desk described on 17 July as the auction house competing with the jewellery store on the store's own terms. Whether that is working has an empirical answer, and seven editions of it sit unpublished. This paper recommended on 14 August that the missing Gem Drop result be retired as a story. That was wrong: the waiting was never the story, the silence is"},
 {"b":"ALL FOUR METALS UP, AND A THREE-SESSION PALLADIUM MARK RETIRED","t":" — Kitco's live board at 05:59 New York time read gold $4,394.60 an ounce, silver $65.38, platinum $1,749.00 and palladium $1,311.00, and all four are written back over the 04:59 marks with the source named and the timestamp new. Two bases are printed because no edition published on 15 or 16 August. Against Kitco's own previous close: gold up $19.00, silver up $0.80, platinum up $4.00, palladium up $13.00. Against this paper's last printed marks of 14 August: gold up $38.40 or 0.88%, silver up $0.61 or 0.94%, platinum up $24.00 or 1.39%, palladium up $14.00 or 1.08%. Gold and silver cleared a second page cleanly at TradingEconomics, $4,394.79 and $65.484, 0.004% and 0.16% away. At the bench the four marks are $141.29, $2.10, $56.23 and $42.15 a gram of fine metal, and the gold-to-silver ratio reads 67.22 against 67.26 on 14 August"},
 {"b":"WHY PALLADIUM'S $1,297.00 CAME OFF","t":" — The mark retired was set on 14 August and carried unchanged since. The tape desk declined to write it back at 04:59 today, finding Kitco at $1,311.00 against FXEmpire at $1,320.55, a gap of $9.55 or 0.73%, and held under the two-page rule. At 05:59 this desk read two further pages: TradingEconomics at $1,331.00 and JM Bullion at $1,351.00. Four live readings, spanning $40.00 or 3.05% from low to high, and every one of them above the held mark, which is not one of the four. The disagreement between outside pages is real and is disclosed rather than reconciled; what it does not support is $1,297.00. Platinum shows the same basis for a fourth consecutive session, Kitco $11.40 or 0.65% below TradingEconomics at $1,760.40, the same sign and size as 12, 13 and 14 August, and Kitco is printed because it carries the other three marks on this tape"},
 {"b":"CHINA'S COUNTER HELD ITS MARGIN THROUGH A 1.4% MOVE","t":" — The Shanghai Gold Exchange's Au99.99 opened at 946.00 yuan a gram today and last traded at 954.01, up 1.41%. Chow Tai Fook's 24-carat counter reads 1,332 yuan, carried identically by two independent Chinese aggregators. That is a markup of 39.62% and a gap of 377.99 yuan a gram, this desk's arithmetic. Three days ago this paper printed the same pair at 940.72 and 1,312, a markup of 39.47% and a gap of 371.28. The exchange rose 1.41% and the counter 1.52%, so the margin held to within fifteen hundredths of a point, which is the answer this desk's 14 August argument predicted: the shop moved the same percentage the metal did, not the same number of yuan. Disclosed: the Bureau's gold desk read today's sessions at 951.80 and 952.98, on which the markup would be 39.77% and the gap 379.02; and the counter series runs 1,312, 1,325, no reading for 16 August, then 1,332"},
 {"b":"ONE FUND CUT 806,676 SIGNET SHARES, AN INDEX FUND BOUGHT 665,182","t":" — Four institutions filed amended Schedule 13G statements on Signet Jewelers between 8 July and 14 August, each reporting a position at 30 June: Vanguard Portfolio Management 3,577,704 shares or 9.09%, Dimensional Fund Advisors 2,584,443 or 6.6%, Select Equity Group 2,436,873 or 6.2%, FMR 2,168,433 or 5.5%. Together 10,767,453 shares against 39,329,783 outstanding at 29 May, or 27.38%, this desk's arithmetic. Select Equity filed at 3,243,549 or 8.1% on 3 April and has cut 806,676 shares, 24.87% of the stake and 1.9 points of the company. Vanguard Portfolio Management filed at 2,912,522 or 7.26% at 31 March and added 665,182, up 22.84%. FMR held 4,792,767 or 11.6% last August and is down 54.76% in ten months. BlackRock's last Signet filing is 14.4% at 30 September 2025 and has not been refreshed. A 13G is a passive declaration and holders below 5% never appear"},
 {"b":"THE PERTH MINT SOLD 486,043 OUNCES OF SILVER IN JULY","t":" — Gold sales of 30,871 ounces were up 4% on the month and 41% on the year; silver at 486,043 ounces up 65% and 8%; platinum at 1,915 ounces up 59% and 46%. The mint published the figures on 10 August, so they are seven days old as they print and describe a month closed more than a fortnight ago, which is stated rather than smoothed over. Fifteen point seven ounces of silver left the mint for every ounce of gold, this desk's division, which at this morning's marks is roughly $135.7 million of gold against $31.8 million of silver: gold outsold silver 4.27 to one by value while silver outsold gold 15.7 to one by weight. The mint's own note records gold near $4,050 at the end of July, 8.51% below this paper's mark this morning. PMGOLD holdings rose 1,011 ounces, or 0.26%, to 382,735 ounces, 11.90 tonnes. A 65% surge at the coin counter beside a quarter of a per cent at the fund is two different customers in one release"},
 {"b":"THE LAB-GROWN ONE-CARAT READS $705 INSIDE A RANGE THAT RUNS 17.6 TIMES","t":" — This paper's tape carries the lab-grown one-carat reference at $705 a carat today, confirmed at source on a page dated 17 August that refreshes daily. The series printed here runs $727 earlier this month, $711 on 11 August, $707 on the 14th and $705 today: down 0.84% in six days and 3.03% from $727. The same page averaging $705 shows one-carat rounds offered from $185 to $3,247, a spread of 17.6 times, this desk's division; at two carats the cushion range runs $345 to $6,984 and at three carats $449 to $12,050. A second source disagrees and both are carried: this paper's own price list of 25 July puts the one-carat lab-grown at $550 a carat from a six-retailer sample, which is 28.2% below CaratRadar's average. Marty Hurwitz of the Grown Diamond Trade Organization told JCK on 14 August that the category's real problem is getting Gen Z into stores at all"},
 {"b":"WHAT DID NOT PRINT TODAY, AND WHICH DESKS ARE DARK","t":" — The Bureau's second-ranked item, a Bonhams Modern Native American Art and Jewelry sale on 26 August in Los Angeles with a Jesse Monongya bear-motif necklace estimated at $50,000 to $80,000, was killed on verification. The Bonhams page the desk fetched is the 14 April 2026 edition of that sale, already past, in which the Monongya necklace sold for $25,600 and the bear-motif top lot is a Bill Reid suite estimated at $40,000 to $60,000; Bonhams' upcoming calendar carries no such sale on 26 August. The Bureau's fourth item, UAE 24-carat gold easing from 529.00 to 527.50 dirhams a gram on 16 August, is declined for a fourth time on over-serving, as on 12, 13 and 14 August. A JCK item of 14 August on the first commercially sold F.P. Journe Résonance is a repeat: this paper broke it on 19 July with the same CHF 500,000 to 1 million estimate. Desks dark today: watches a sixth consecutive edition, gemstones an eleventh, and no gemstones file is due until 18 August under the Tuesday and Friday cadence set by the chief on 13 August"},
]
wire["tape"] = [
 {"name":"Gold / oz","code":"XAU","px":"4,394.60","chg":"▲ +0.43%","dir":"up",
  "pts":[18,19,21,23,23,24,26,24,22,26]},
 {"name":"Natural 1ct (RAPI proxy)","code":"NAT1","px":"5,232.00","chg":"— unch.","dir":"flat",
  "pts":[13,13,13,13,13,13,13,13,13,13]},
 {"name":"Lab-grown 1ct reference","code":"LGD1","px":"705.00","chg":"▼ −0.28%","dir":"down",
  "pts":[14,14,14,14,13,13,13,13,13,12]},
 {"name":"Platinum / oz","code":"XPT","px":"1,749.00","chg":"▲ +0.23%","dir":"up",
  "pts":[19,20,22,21,21,22,21,18,20,23]},
 {"name":"Silver / oz","code":"XAG","px":"65.38","chg":"▲ +1.24%","dir":"up",
  "pts":[19,18,22,21,22,23,25,22,23,26]},
]
(C/"wire.json").write_text(json.dumps(wire,ensure_ascii=False,indent=1))

# ---- record: new week at the top (Monday rollover) ----
old = record["weeks"][0]
assert old["label"] == "This week — August 10", old["label"]
old["label"] = "Week of August 10"

newent = [
 {"d":"auctions","h":"Three closed Sotheby's jewel sales carry no published result between them",
  "t":"As at 17 August 2026, Sotheby's own past-results index carries no total, no sell-through rate and no top lot for three closed jewellery sales. The Gem Drop August, an online sale in New York, closed on 13 August after four days of bidding, four days before this reading. The Arcade Sale in Hong Kong ran from 31 July to 6 August and closed eleven days before this reading. The Gem Drop July closed on 16 July, thirty-two days before this reading, and its sale page likewise carries no result; this paper covered that sale on 17 July 2026 as eleven-lots-no-premium, describing it as the sixth in a monthly series. Sotheby's landing page for the Gem Drop series, read the same day, describes it as a monthly release of jewels through the house's Sealed platform and carries a heading for past auctions with no auctions listed beneath it. Lot pages and estimates remain accessible; realised prices do not. One limitation is recorded: Sotheby's renders parts of these pages through scripts this desk's fetch does not execute, so the finding is what the public page returns to a reader rather than proof that no figure exists internally. Against this, the same house's New York High Jewelry sale of 13 June 2026 made $31.4 million with 95% of lots sold, led by a $3.2 million Graff ring set with a 35-carat D-colour diamond, figures this paper published on 24 July 2026, and Sotheby's reported a $4.4 billion first half for 2026 with private sales at a record $826 million. The Gem Drop charges no buyer's premium, the feature that makes its performance data materially interesting to consignors and to retailers. This paper's own recommendation of 14 August 2026, that the missing Gem Drop result be retired as a story after four days, is corrected here.",
  "s":"Sotheby's results index, Gem Drop July sale page and Gem Drop series page (all read 17 August 2026) / Carat Capital archive"},
 {"d":"gold-metals","h":"All four metals written back at 05:59, ending a three-session palladium hold at $1,311.00",
  "t":"On 17 August 2026 Kitco's live board at 05:59 New York time read gold at $4,394.60 an ounce, silver at $65.38, platinum at $1,749.00 and palladium at $1,311.00. Under the one-price rule the Editor wrote all four readings back over the 04:59 marks, with the new timestamp and the source named, before the edition built. Because no edition published on 15 or 16 August, two comparison bases are printed. Against Kitco's own previous close the session moves are gold up $19.00, silver up $0.80, platinum up $4.00 and palladium up $13.00. Against this paper's last printed marks of record, set on 14 August 2026 at $4,356.20, $64.77, $1,725.00 and $1,297.00, the three-day moves are gold up $38.40 or 0.88%, silver up $0.61 or 0.94%, platinum up $24.00 or 1.39% and palladium up $14.00 or 1.08%. Gold and silver were cross-checked the same morning against TradingEconomics at $4,394.79 and $65.484, differences of 0.004% and 0.16%. The palladium mark retired, $1,297.00, was set on 14 August and carried unchanged since; the tape desk declined to replace it at 04:59 today, having found Kitco at $1,311.00 against FXEmpire at $1,320.55, a gap of $9.55 or 0.73%, and held under the two-page rule. At 05:59 the Editor read two further pages, TradingEconomics at $1,331.00 and JM Bullion at $1,351.00. The four live readings span $40.00, or 3.05%, from low to high and every one of them sits above the held mark, which is not among them; the divergence between those outside pages is disclosed rather than reconciled. Platinum showed the same basis for a fourth consecutive session, with Kitco $11.40 or 0.65% below TradingEconomics at $1,760.40, the same sign and approximate size as the gaps recorded on 12, 13 and 14 August; Kitco is printed because it is the board carrying the other three marks on this tape. At 31.1035 grams to the troy ounce the four marks work out at $141.29 a gram of fine gold, $2.10 of fine silver, $56.23 of fine platinum and $42.15 of fine palladium, and the gold-to-silver ratio reads 67.22 against 67.26 on 14 August, all this desk's arithmetic.",
  "s":"Kitco / TradingEconomics / JM Bullion / FXEmpire via caratwire / Carat Capital tape and arithmetic"},
 {"d":"gold-metals","h":"Shanghai gold rose 1.41% and China's jewellery counter held its markup at 39.62%",
  "t":"On 17 August 2026 the Shanghai Gold Exchange's Au99.99 contract opened at 946.00 yuan a gram and last traded at 954.01, a rise of 1.41% on the session, per the market report carried by the Chinese finance aggregator cngold. Chow Tai Fook's 24-carat counter read 1,332 yuan a gram the same day, a figure carried identically by two independent Chinese price aggregators, jinjia.com.cn and cngold. Dividing the counter by the exchange, this desk's arithmetic, puts the counter 39.62% above the exchange, a gap of 377.99 yuan on every gram. This paper published the same pair on 14 August 2026 at 940.72 and 1,312, a markup of 39.47% and a gap of 371.28 yuan. Over the three days the exchange rose 13.29 yuan, or 1.41%, and the counter rose 20 yuan, or 1.52%, moving the markup by fifteen hundredths of a percentage point. This is the test this desk set for its own 14 August argument, that the Chinese counter price is a merchant setting a margin rather than a market clearing, and the result is consistent with it: the counter tracked the metal in percentage terms rather than in absolute yuan. Two divergences between outside sources are disclosed. On the exchange leg, the Bureau's gold desk read today's Shanghai sessions at 951.80 and 952.98 yuan against the 954.01 used here; on 952.98 the markup would read 39.77% and the gap 379.02 yuan, and this desk cannot establish which minute of the board each page reads. On the counter leg, the aggregator series runs 1,312 on 14 August, 1,325 on 15 August, no published reading for 16 August and 1,332 on 17 August, so the 20-yuan rise spans two counter revisions rather than one. As a sanity check on the Shanghai figure, gold at this paper's own mark of $4,394.60 an ounce is $141.29 a gram, and 954.01 yuan against $141.29 implies 6.752 yuan to the dollar; that implied rate is this desk's arithmetic and is not an official currency quotation. A listed counter price is an asking price rather than a transacted one, and workmanship charges, store discounts and buy-back terms sit outside both numbers.",
  "s":"Shanghai Gold Exchange market report via cngold (17 August 2026) / jinjia.com.cn / caratgold bureau file / Carat Capital arithmetic and archive"},
 {"d":"retail-tech","h":"Four filers disclose 27.38% of Signet; one active manager cut 24.87% as an index fund added 22.84%",
  "t":"Four institutions filed amended Schedule 13G statements with the United States Securities and Exchange Commission in respect of Signet Jewelers between 8 July and 14 August 2026, each reporting a position as at 30 June 2026. Vanguard Portfolio Management reported 3,577,704 shares, or 9.09%. Dimensional Fund Advisors LP reported 2,584,443 shares, or 6.6%. Select Equity Group, L.P. reported 2,436,873 shares, or 6.2%. FMR LLC reported 2,168,433 shares, or 5.5%. The four positions total 10,767,453 shares against the 39,329,783 common shares Signet disclosed as outstanding at 29 May 2026 in its quarterly report on Form 10-Q, which is 27.38%, this desk's arithmetic on the filings. Two positions changed materially over the quarter. Select Equity Group filed its first Schedule 13G on Signet on 3 April 2026 reporting 3,243,549 shares, or 8.1%, as at 1 April; its amended filing of 14 August reports 2,436,873 shares at 30 June, a reduction of 806,676 shares, or 24.87% of the stake and 1.9 percentage points of the company. Vanguard Portfolio Management filed on 29 April 2026 reporting 2,912,522 shares, or 7.26%, as at 31 March; its amendment of 31 July reports 3,577,704 at 30 June, an increase of 665,182 shares, or 22.84%. The net of the two is 141,494 shares. Over a longer window, FMR LLC reported 4,792,767 shares, or 11.6%, as at 29 August 2025, so its 30 June position represents a reduction of 54.76% across ten months. BlackRock, Inc. last filed on Signet reporting 5,893,515 shares, or 14.4%, as at 30 September 2025 and has not filed since. The Vanguard Group lodged a fifteenth amendment on 27 March 2026 reporting zero shares, and two separately named Vanguard entities filed fresh Schedule 13Gs at the end of April 2026; this desk reads that sequence as a re-registration of the same holding under new filing entities rather than a disposal, and states it as a reading rather than as an established fact. A Schedule 13G is a passive declaration by holders who state they are not seeking to influence control. Holders below the 5% threshold do not appear, so these filings are not a complete register.",
  "s":"SEC EDGAR, Schedule 13G and 13G/A filings on Signet Jewelers Ltd (CIK 0000832988) / Signet Jewelers Form 10-Q share count at 29 May 2026 / Carat Capital arithmetic"},
 {"d":"gold-metals","h":"Perth Mint July: silver sales up 65% on the month, gold up 4%, platinum up 59%",
  "t":"The Perth Mint reported on 10 August 2026 that it sold 30,871 troy ounces of gold, 486,043 ounces of silver and 1,915 ounces of platinum in minted product form during July 2026. Month on month, gold sales rose 4%, silver 65% and platinum 59%. Year on year, gold rose 41%, silver 8% and platinum 46%. Holdings in the mint's exchange-traded product, PMGOLD, rose 1,011 ounces, or 0.26%, to 382,735 ounces, which is 11.90 tonnes at 31.1035 grams to the troy ounce. The mint's own commentary records gold trading near US$4,050 an ounce at the end of July, a monthly gain of about 1%, after touching its lowest level of the year during the month. Against this paper's mark of record of US$4,394.60 an ounce on 17 August 2026, that end-July level is 8.51% lower, this desk's arithmetic, so the July demand recorded here was transacted at a materially lower price than the metal now carries. Derived figures, all this desk's: 15.7 ounces of silver left the mint for every ounce of gold; valued at this paper's 17 August marks of US$4,394.60 and US$65.38 an ounce, the month's gold sales are approximately US$135.7 million against approximately US$31.8 million of silver, so gold outsold silver by 4.27 to one by value while silver outsold gold by 15.7 to one by weight. The figures are seven days old as this paper prints them and describe a month that closed more than a fortnight ago. They cover one refiner's minted-product sales through a retail channel weighted to Australian and Asian buyers, and are neither Australian nor global demand. This paper reported on 14 August 2026 that global gold exchange-traded fund flows in July were principally European, with North America contributing US$71 million of a US$3 billion month.",
  "s":"The Perth Mint, July 2026 sales update (10 August 2026) / Kitco / Carat Capital tape, arithmetic and archive"},
 {"d":"diamonds","h":"The lab-grown one-carat reference reads $705, drawn from offers spanning 17.6 times",
  "t":"On 17 August 2026 CaratRadar's reference average for a one-carat round lab-grown diamond read US$705 a carat, on a page dated the same day which states that it refreshes daily; this is the figure carried on this paper's tape. The series this paper has published runs US$727 earlier in August, US$711 on 11 August 2026, US$707 on 14 August 2026 and US$705 on 17 August 2026, a decline of 0.84% over six days and 3.03% from US$727. The same source page shows the offers underlying that average running from US$185 to US$3,247 a carat for a one-carat round, a spread of 17.6 times, this desk's division; at two carats the cushion range runs US$345 to US$6,984 and at three carats US$449 to US$12,050. A second source disagrees and both are carried. This paper's own Natural Diamond Price List, compiled 25 July 2026 from a live retail sample, puts the one-carat round lab-grown at US$550 a carat against a natural one-carat round at US$4,581, a multiple of 8.3; CaratRadar's US$705 is 28.2% above that US$550, this desk's arithmetic, across a three-week gap and two different samples of the same market. Neither figure is presented as correct against the other: one is a live retail asking average from one aggregator, the other a six-retailer median from another, and no clearing exchange exists to settle the difference. Separately, Marty Hurwitz, executive director of the Grown Diamond Trade Organization, told JCK in an article published 14 August 2026 that lab-grown diamonds are a help and not a hindrance to the jewelry industry, and identified the sector's principal challenge as bringing Gen Z consumers into jewellery stores at all, noting that consumers continue to buy the category without macro-level marketing behind it.",
  "s":"CaratRadar (read 17 August 2026) / Carat Capital Natural Diamond Price List (25 July 2026) / JCK (14 August 2026) / Carat Capital arithmetic and archive"},
]
record["weeks"].insert(0, {"label":"This week — August 17","entries":newent})
record["updated"] = "17 Aug 2026"
(C/"record.json").write_text(json.dumps(record,ensure_ascii=False,indent=1))
print("wire No.036 written; new record week with", len(newent), "entries; weeks now", len(record["weeks"]))
