#!/usr/bin/env python3
import json, pathlib
C = pathlib.Path("content")
wire = json.loads((C/"wire.json").read_text())
record = json.loads((C/"record.json").read_text())

wire["date_line"] = "Friday, August 14, 2026"
wire["edition"] = "Vol. I — No. 035"
wire["tape_ts"] = "14 Aug 2026, 6:00am New York · Kitco live board · Editor's press-time read, all four metals written back to the tape"
wire["items"] = [
 {"b":"NINE FORTY AT THE EXCHANGE, THIRTEEN TWELVE AT THE COUNTER","t":" — The Shanghai Gold Exchange closed Au99.99 at 940.72 yuan a gram today, from an opening of 955.00 and a session low of 933.01, on 3,886.14 kilogrammes; Au(T+D) closed at 940.44 on 41,646 kilogrammes. Those are the exchange's own published quotations, not an aggregator's copy. On the same day Chow Tai Fook listed 24-carat jewellery at 1,312 yuan a gram, carried identically by two independent Chinese aggregators, jinjia.com.cn and cngold. That puts the counter 39.47% above the exchange, a gap of 371.28 yuan a gram, this desk's arithmetic. This paper published the same pair on 9 August at 938 and 1,286, a gap of 348 yuan and a markup of 37.10%. Six days on, the exchange has moved 0.29% and the counter 2.02%: the gap did not close, it widened by 23.28 yuan a gram"},
 {"b":"THE COUNTER CUT TWICE AS FAST AS THE METAL","t":" — Today both legs fell and they fell at very different speeds. The exchange closed 8.52 yuan below its 13 August close of 949.24, a fall of 0.90%. The Chow Tai Fook counter came off 28 yuan from 1,340, a fall of 2.09%, roughly two and a third times as fast. The premium therefore narrowed today, from 41.17% on one aggregator's 13 August counter price or 40.01% on the other's, to 39.47%. The counter moves in steps and the exchange moves in fractions: this month the brand price has gone 1,231, 1,240, 1,297, 1,286, 1,308, 1,308, 1,336, 1,329, 1,340 and 1,312, round jumps of tens of yuan against an exchange that rarely moves one per cent in a day. On the readings this desk can verify, the Chinese jewellery markup has run between 37.10% and 41.17% in August. A listed counter price is an asking price, not a transacted one, and workmanship charges and store discounts sit outside both numbers"},
 {"b":"OUTSIDE SOURCES DISAGREE ON THE CHINESE COUNTER, AND IT IS DISCLOSED","t":" — Two disclosures belong with the figures above. One aggregator's series carries 1,286 against 7 August rather than the 8 August this paper published it under, and the same two aggregators disagree about 13 August by 11 yuan, one reading 1,340 and the other 1,329. This desk cannot establish which board hour either page is reading and does not resolve it here. The 14 August counter price of 1,312 is the one both pages agree on, which is why today's comparison is anchored there rather than on the disputed day. Separately, the Bank of China's market note of 13 August put Shanghai spot gold up 0.96% at 955.75 yuan a gram, where the exchange's own daily quotation for that date closes Au99.99 at 949.24. The exchange's own figure is the one used here. Divergence between outside sources is always disclosed; that rule is untouched"},
 {"b":"THE PLATINUM HOLD ENDS AT $1,725","t":" — Kitco's live board at 06:00 New York time read gold $4,356.20, silver $64.77, platinum $1,725.00 and palladium $1,297.00, and all four are written back over caratwire's 04:59 marks with the source named and the timestamp new. Against this paper's own marks 24 hours earlier: gold down $27.90 or 0.64%, silver up $0.25 or 0.39%, platinum up $15.00 or 0.88%, palladium down $22.00 or 1.67%. Gold and silver were checked against TradingEconomics at $4,356.79 and $64.89, 0.01% and 0.19% away. Platinum had been held twice, on 12 August for a stale cell and on 13 August because Kitco sat $14.60 below two pages that agreed with each other. At 04:59 today the tape desk found the same shape a third time and held again. At 06:00 the gap is $12.70 against TradingEconomics at $1,737.70 and $14.90 against JM Bullion at $1,739.90, with those two agreeing to $2.20, or 0.13%"},
 {"b":"WHY THE MARK WAS TAKEN RATHER THAN HELD A THIRD TIME","t":" — Three mornings of the same gap in the same direction, at the same order of magnitude, reads as a basis difference between outside pages rather than as a market nobody can read. Treating it as the second thing had a cost: the held mark of $1,710.00 was two sessions old and 1.62% below where two other pages put the metal, which is a stale number wearing the protection of good procedure. Platinum is therefore written back on Kitco, the board that carries every other mark on this tape, and palladium with it at Kitco's $1,297.00 bid. JM Bullion read palladium at $1,336.71 at 06:01, $39.71 or 3.06% higher, which on a metal this thin is the other side of a spread rather than a disagreement about the price. Leaving one Kitco mark frozen and three Kitco marks fresh, from the same board at the same minute, is the two-numbers problem the one-price rule exists to remove. A jeweller quoting platinum off a single public board this morning is choosing between $1,725.00 and $1,739.90 without being told there is a choice"},
 {"b":"SEVENTY-ONE MILLION FROM AMERICA IN A THREE BILLION DOLLAR MONTH","t":" — Global gold-backed ETFs took in $3 billion in July, reversing two consecutive months of outflows, in figures the World Gold Council published on 6 August under the title Europe's golden heatwave. Collective holdings rose 23 tonnes to 4,068 tonnes and assets under management rose 1% to $530 billion. Europe took $2 billion of it, the United Kingdom alone $875 million and Switzerland $657 million. Asia took $616 million, with China strongest and Japan in outflow. North America took $71 million. Other regions took $140 million. Britain and Switzerland together raised $1,532 million against $827 million from everywhere outside Europe, a ratio of 1.85 to one and this desk's arithmetic; North America, the largest gold ETF market in the world by assets, supplied 2.5% of the named regional total. The named regions sum to $2,827 million against a rounded headline of $3 billion because every component is rounded, and that subtraction is this desk's. The figures are eight days old as they print, and this paper has cited the World Gold Council fifteen times without ever covering its flows series"},
 {"b":"WHAT DID NOT PRINT TODAY","t":" — The Bureau ranked the ETF item first and this desk moved it to third after confirming the publication date, which is 6 August and eight days back; a monthly research report that old is reported honestly rather than led with. The Bureau's second item, Shanghai gold with a Chow Tai Fook counter at 1,340 yuan described as closing the wholesale-retail gap, ran as the lead with both halves corrected: 1,340 is one aggregator's 13 August figure and the other reads 1,329, and on this paper's own arithmetic the gap has widened since 8 August rather than closed. The gold-to-silver ratio piece the Bureau offered as optional filler is not run as an article; the ratio at 67.26, narrowing 0.69 points from 67.95, appears inside the tape story instead. Two items were verified and dropped: Tenoris's US jewellery half-year, which is dated 9 July and which this paper has already covered nine times including on 8 August, and Sotheby's Gem Drop August, whose sale closed in New York yesterday and whose own results page still carries no total"},
 {"b":"GEMSTONES DARK A TENTH EDITION, DIAMONDS AND RETAIL GO DARK FOR THE FIRST TIME","t":" — Recomputed here from the raw per-edition desk mix across Nos. 028 to 034 rather than carried forward from yesterday's prose. Colour last ran in No. 025 on 4 August and misses a TENTH consecutive edition today, which is this paper's own record and was escalated as structural by the Bureau and by the standards desk before it. Watches last ran in No. 030 on 9 August and is dark a FIFTH consecutive edition; Swiss federation July export data is not due until about 20 August. Auctions last ran in No. 030 and is dark a FIFTH; Sotheby's Arcade Hong Kong results are now nine days overdue against a two-to-three-day house turnaround, which is worth a line on its own. Diamonds ran in Nos. 032, 033 and 034 and goes dark today for the first time in four editions. Retail and technology had run in every edition from 027 through 034 and goes dark today for the first time in nine. Gold and metals runs a NINTH consecutive edition and is the whole of today's paper"},
 {"b":"THE STANDARDS FILE WAS CLEAR","t":" — The newest standards audit is caratcheck's file of 13 August, read first this morning ahead of the slate per the correction route. It lists nothing under FOR CORRECTION TODAY and grades both No. 034 and a catch-up audit of No. 032 at A: roughly twenty independently re-traceable figures across the two editions, twenty traced clean and none failed, and two source quotes confirmed word for word against the primary source. There is no outstanding correction on any published page this morning and no published figure was altered today. Today's three pull quotes were counted before the queue was written, at 12, 14 and 13 words against a cap of 15, and the apply script fails the build on any quote over it. There are no source quotes in today's edition at all and no quotation mark appears in any of the three articles. The standards desk flags the CC20 index figure on the homepage as its next audit's first item, a pipeline this desk has already recorded as manually refreshed"},
]
wire["tape"] = [
 {"name":"Gold / oz","code":"XAU","px":"4,356.20","chg":"▼ −0.64%","dir":"down",
  "pts":[15,18,19,21,23,23,24,26,24,22]},
 {"name":"Natural 1ct (RAPI proxy)","code":"NAT1","px":"5,232.00","chg":"— unch.","dir":"flat",
  "pts":[13,13,13,13,13,13,13,13,13,13]},
 {"name":"Lab-grown 1ct reference","code":"LGD1","px":"707.00","chg":"— unch.","dir":"flat",
  "pts":[13,13,13,13,13,13,13,13,13,13]},
 {"name":"Platinum / oz","code":"XPT","px":"1,725.00","chg":"▲ +0.88%","dir":"up",
  "pts":[18,19,20,22,21,21,22,21,18,20]},
 {"name":"Silver / oz","code":"XAG","px":"64.77","chg":"▲ +0.39%","dir":"up",
  "pts":[17,19,18,22,21,22,23,25,22,23]},
]
(C/"wire.json").write_text(json.dumps(wire,ensure_ascii=False,indent=1))

# ---- record: append into the current week (Friday, no rollover) ----
wk = record["weeks"][0]
assert wk["label"] == "This week — August 10", wk["label"]

newent = [
 {"d":"gold-metals","h":"China's jewellery counter is 39.47% above the Shanghai exchange price, and the gap has widened since 8 August",
  "t":"The Shanghai Gold Exchange closed its Au99.99 contract at 940.72 yuan a gram on 14 August 2026, from an opening of 955.00 and a session low of 933.01, on volume of 3,886.14 kilogrammes; the deferred Au(T+D) contract closed at 940.44 on 41,646 kilogrammes. Those figures are taken from the exchange's own published daily quotations rather than from an aggregator. On the same day Chow Tai Fook listed 24-carat jewellery at 1,312 yuan a gram, a figure carried identically by two independent Chinese price aggregators, jinjia.com.cn and cngold. Dividing the counter price by the exchange price, this desk's arithmetic, puts the counter 39.47% above the exchange, a gap of 371.28 yuan on every gram. This paper published the same pair on 9 August 2026 at 938 yuan on the exchange and 1,286 at the counter, a gap of 348 yuan and a markup of 37.10%. Six days later the exchange has moved 2.72 yuan, or 0.29%, and the counter has moved 26 yuan, or 2.02%, so the gap has widened by 23.28 yuan a gram rather than closing. Today both legs fell: the exchange closed 8.52 yuan, or 0.90%, below its 13 August close of 949.24, while the counter came off 28 yuan, or 2.09%, from 1,340, roughly two and a third times as fast, narrowing the premium from 41.17% on one aggregator's 13 August counter price, or 40.01% on the other's, to 39.47%. Across the sessions the aggregator series records this month the Chow Tai Fook price has gone 1,231, 1,240, 1,297, 1,286, 1,308, 1,308, 1,336, 1,329, 1,340 and 1,312. On the readings this desk can verify, the Chinese jewellery markup has run between 37.10% and 41.17% in August. Two divergences between outside sources are disclosed: one aggregator's series carries 1,286 against 7 August rather than the 8 August this paper published it under, and the two aggregators disagree about 13 August by 11 yuan, at 1,340 and 1,329. Separately, the Bank of China's market note of 13 August put Shanghai spot gold up 0.96% at 955.75 yuan a gram against the exchange's own close of 949.24 for that date; the exchange's own figure is used here. A listed counter price is an asking price rather than a transacted one, and workmanship charges, store discounts and buy-back terms sit outside both numbers.",
  "s":"Shanghai Gold Exchange daily quotations (14 August 2026) / jinjia.com.cn / cngold / Bank of China market note (13 August 2026) / Carat Capital arithmetic and archive"},
 {"d":"gold-metals","h":"All four metals written back on one board, ending a two-session platinum hold at $1,725.00",
  "t":"On 14 August 2026 Kitco's live board at 06:00 New York time read gold at $4,356.20 an ounce, silver at $64.77, platinum at $1,725.00 and palladium at $1,297.00. Under the one-price rule the Editor wrote all four readings back over caratwire's 04:59 marks, with the new timestamp and the source named on the tape before the edition built. Measured against this paper's own marks of record 24 hours earlier, gold fell $27.90 or 0.64%, silver rose $0.25 or 0.39%, platinum rose $15.00 or 0.88% and palladium fell $22.00 or 1.67%. Gold and silver were cross-checked the same morning against TradingEconomics at $4,356.79 and $64.89, differences of 0.01% and 0.19%. The gold-to-silver ratio, this desk's division of its own published gold mark by its own published silver mark on the same board at the same minute, narrowed to 67.26 from 67.95. Platinum had been held twice: on 12 August 2026 because Kitco's cell was stale, and on 13 August 2026 because Kitco's live cell sat $14.60 below TradingEconomics and JM Bullion, which agreed with each other to within 50 cents. At 04:59 on 14 August the tape desk found the same shape a third time, with Kitco $13.30 below TradingEconomics, and held again. At 06:00 the gap was $12.70 against TradingEconomics at $1,737.70 and $14.90 against JM Bullion at $1,739.90, with those two pages agreeing to $2.20, or 0.13%. This desk's judgement is that a gap recurring at the same size and sign across three consecutive sessions is a basis difference between outside pages rather than an unreadable market, and that continuing to hold had produced a mark two sessions old and 1.62% below where two other pages put the metal. Platinum is therefore written back on Kitco, the board that carries every other mark on this tape, and palladium with it at Kitco's $1,297.00 bid; JM Bullion read palladium at $1,336.71 at 06:01, $39.71 or 3.06% higher, disclosed as the other side of a thin spread. At 31.1035 grams to the troy ounce the four marks work out at $140.05 a gram of fine gold, $2.08 of fine silver, $55.46 of fine platinum and $41.70 of fine palladium, all this desk's arithmetic.",
  "s":"Kitco / TradingEconomics / JM Bullion / Carat Capital tape and arithmetic"},
 {"d":"gold-metals","h":"Gold ETFs took in $3bn in July; Europe supplied $2bn of it and North America $71mn",
  "t":"The World Gold Council reported on 6 August 2026, under the title Europe's golden heatwave, that global physically backed gold exchange-traded funds took in US$3 billion in July 2026, reversing two consecutive months of outflows. Collective holdings rose 23 tonnes to 4,068 tonnes and assets under management rose 1% to US$530 billion. Holdings remain 108 tonnes, or 2.59%, below the record of 4,176 tonnes set on 27 February 2026, that subtraction being this desk's. By region, Europe took US$2 billion, of which the United Kingdom contributed US$875 million and Switzerland US$657 million; Asia took US$616 million, with China the strongest contributor and Japan in outflow; North America took US$71 million; and other regions, chiefly Australia and South Africa, took US$140 million. Britain and Switzerland together raised US$1,532 million against US$827 million from Asia, North America and all other regions combined, a ratio of 1.85 to one, and North America supplied 2.5% of the named regional total; both figures are this desk's arithmetic. The named regional components sum to US$2,827 million against a rounded headline of US$3 billion because every component is rounded, a difference this desk states rather than reconciles. Year to date, global gold ETF inflows amounted to US$11 billion, equivalent to a 39-tonne increase in holdings. Average daily trading volumes across the gold market fell 3.5% to US$356 billion in the month and over-the-counter volumes fell 3.4% to US$205 billion. This paper has previously reported global jewellery demand of 278 tonnes in the second quarter of 2026, the smallest since the pandemic, on 31 July 2026; Indian jewellery demand of 75.1 tonnes, down 15% by weight, on the same day; China's gold jewellery consumption at its lowest since 2004, on 3 August 2026; and China's heaviest month of bullion buying since 2023, on 9 August 2026. This is the first coverage of the World Gold Council's monthly ETF flows series in this paper's archive, and the report is eight days old as it prints.",
  "s":"World Gold Council, Gold ETF Flows: July 2026 (6 August 2026) / Carat Capital arithmetic and archive"},
]
wk["entries"] = newent + wk["entries"]
record["updated"] = "14 Aug 2026"
(C/"record.json").write_text(json.dumps(record,ensure_ascii=False,indent=1))
print("wire No.035 written;", len(newent), "record entries prepended into", wk["label"], "->", len(wk["entries"]), "total")
