#!/usr/bin/env python3
import json, pathlib
C = pathlib.Path("content")
wire = json.loads((C/"wire.json").read_text())
record = json.loads((C/"record.json").read_text())

wire["date_line"] = "Saturday, August 8, 2026"
wire["edition"] = "Vol. I — No. 029"
wire["tape_ts"] = "7 Aug 2026, 5:00pm New York close · Kitco spot · change against Thursday's close · no Saturday session"
wire["items"] = [
 {"b":"MINUS TWENTY-THREE THOUSAND","t":" — US non-farm payrolls fell 23,000 in July against a consensus of roughly 83,000 jobs added, a miss of 106,000, with June revised to a 20,000 loss. The unemployment rate edged down to 4.1% while the participation rate fell to 61.4%, its lowest in more than five years; average hourly earnings rose two cents and annual wage growth slowed to 3.2%. The Bureau of Labor Statistics release page returned 403 to this desk and the figures are carried as reported by two outlets"},
 {"b":"GOLD CLOSES AT $4,341.30","t":" — Kitco's 5:00pm New York close on Friday had gold bid $4,341.30, up $102.00 or 2.41% against Thursday; silver $63.46, up $2.06 or 3.36%; platinum $1,743.00, up $25.00 or 1.46%; palladium $1,357.00, up $4.00 or 0.30%. Fine gold is $139.58 a gram. Outside sources diverge: Trading Economics carried $4,343.43 for the same day, $2.13 higher, and Reuters reporting had spot near $4,356 at its intraday best. This paper carries the Kitco close as a stated closing print at a stated time"},
 {"b":"GOLD KEPT IT, THE OTHERS GAVE IT BACK","t":" — Against this paper's own 5:58am marks on Friday, gold added a further $26.80 into the close while platinum gave back $29.00, palladium $25.00 and silver $0.83. Platinum was up 3.14% on the session in the morning and closed up 1.46%; palladium was up 2.14% and closed up 0.30%. The gold to silver ratio tightened to 67.11 by morning and widened back to 68.41 at the close, from 69.04 on Thursday"},
 {"b":"SEPTEMBER PRICED OUT TO 46%","t":" — The CME FedWatch tool had the probability of a September rate hike at 46% immediately after the payrolls release, from 55% before it; this paper carried 56.9% on Friday morning. Ellen Zentner of Morgan Stanley Wealth Management noted that next week's inflation data will still likely be the deciding factor. Consumer prices are released next week"},
 {"b":"BONHAMS RUNS CHANEL IN THREE CITIES","t":" — Bonhams has set three Chanel sales for September: New York 7 to 17, Paris 14 to 24 with roughly 400 lots, and London 21 September to 1 October. London carries the jewellery weight, with a private collection of 1960s to 1990s Chanel costume pieces led by a Robert Goossens filigree snake bangle circa 1960 at $13,000 to $20,000, against Chanel Fine Jewelry 18-carat white gold and diamond Comète Géode earrings from 2024 at £2,000 to £3,000. New York highlights go on view at the Manhattan flagship from 17 August"},
 {"b":"TWENTY-NINE PER CENT SAID DIAMOND","t":" — HKTDC surveyed 1,507 buyers and exhibitors at its twin Hong Kong shows, which ran 29 July to 2 August at the convention centre. Diamond led the most-in-demand question at 29%, ahead of ruby at 25% and pearl at 20%, while trendy fashion jewellery led growth potential at 57% against precious jewellery at 35% and designer at 21%. Yellow gold was the preferred metal for 40%. Respondents expect one to two years before confidence is fully restored"},
 {"b":"EIGHT POINT SIX UP, NINE DOWN","t":" — Tenoris figures reported by JCK put US jewellery sales up 8.6% across the first half on a 19% rise in average purchase price, with unit sales falling; the implied unit change, derived by this desk rather than published, is about −9%. June sales rose 13% year on year and sales below $1,500 continued to decline. It is the same shape this paper filed from Brilliant Earth, Richemont and Luk Fook in the past fortnight"},
 {"b":"NY NOW REBOOKS 96%","t":" — NY Now's summer market ran 2 to 4 August at the Javits Center with 460 exhibitors, more than 70 of them new or returning, in the first edition under Rockview Management Group after Emerald sold the show. Buyer attendance rose 5% year on year, 107 prospective exhibitors walked the floor, and organisers report a 96% renewal rate for the winter 2027 market, which opens 31 January"},
 {"b":"WHAT DID NOT PRINT TODAY","t":" — Etsy is cutting 220 jobs, 12% of its workforce, in product and engineering, with second-quarter sales up 6%; carried as context because no jewellery-seller-specific impact has been reported. Four slate items were killed on verification: the NDC and GJEPC Mumbai strategy meeting (already published here on 5 August), Rio Tinto's Diavik half-year production (published three times, most recently 29 July), Antwerp's half-year trade figures and the Israel Diamond Exchange leadership change (both previously published). Angola's rough production ranking was pulled because the desk's figures did not match its own cited source. Sotheby's Arcade Hong Kong closed on 6 August and has published no result for a third consecutive day. On the diamond lines NAT1 and LGD1 are carried unchanged; the lab-grown reference reads $711 on CaratRadar against $510 on StoneAlgo, a spread of roughly 39% this desk carries rather than reconciles. RAPI returned 403 for a fourth day"},
]
wire["tape"] = [
 {"name":"Gold / oz","code":"XAU","px":"4,341.30","chg":"▲ +2.41%","dir":"up",
  "pts":[14,15,16,15,16,15,18,19,21,23]},
 {"name":"Natural 1ct (RAPI proxy)","code":"NAT1","px":"5,232.00","chg":"— unch.","dir":"flat",
  "pts":[13,13,13,13,13,13,13,13,13,13]},
 {"name":"Lab-grown 1ct wholesale","code":"LGD1","px":"727.00","chg":"— unch.","dir":"flat",
  "pts":[13,13,13,13,13,13,13,13,13,13]},
 {"name":"Platinum / oz","code":"XPT","px":"1,743.00","chg":"▲ +1.46%","dir":"up",
  "pts":[15,15,17,16,17,18,19,20,22,21]},
 {"name":"Silver / oz","code":"XAG","px":"63.46","chg":"▲ +3.36%","dir":"up",
  "pts":[17,16,16,15,16,17,19,18,22,21]},
]
(C/"wire.json").write_text(json.dumps(wire,ensure_ascii=False,indent=1))

# ---- record: prepend into the current week ----
wk = record["weeks"][0]
assert wk["label"] == "This week — August 3", wk["label"]

newent = [
 {"d":"gold-metals","h":"July payrolls fall 23,000 against a consensus of 83,000; gold closes at $4,341.30",
  "t":"US non-farm payroll employment fell by 23,000 in July 2026 against a market consensus of roughly 83,000 jobs added, a miss of 106,000, with June revised down to a loss of 20,000. The unemployment rate edged down to 4.1% while the labour force participation rate fell to 61.4%, its lowest in more than five years; average hourly earnings rose two cents on the month and annual wage growth slowed to 3.2%. The Bureau of Labor Statistics release page returned HTTP 403 to this desk, and the figures are carried as reported by Brisk Markets and CNBC on 7 August 2026 rather than from the primary release. Kitco's 5:00pm New York close on 7 August had gold bid at $4,341.30 an ounce, up $102.00 or 2.41% against Thursday's close; silver $63.46, up $2.06 or 3.36%; platinum $1,743.00, up $25.00 or 1.46%; palladium $1,357.00, up $4.00 or 0.30%. Fine gold at that level is $139.58 a gram against $138.72 at this paper's Friday morning mark; ten grams of 18-carat gold carries $1,046.85 of metal. Outside sources diverge on the day's gold mark and the divergence is recorded rather than resolved: Trading Economics carried $4,343.43 for 7 August, $2.13 above the Kitco close, and Reuters reporting during the session had spot near $4,356 at its intraday best. This paper carries the Kitco close because it is a stated closing print at a stated time. The CME FedWatch tool had September rate-hike probability at 46% immediately after the release, from 55% before it and against the 56.9% this paper carried on Friday morning. Consumer price data is released the following week. Saturday 8 August is a weekend and spot markets did not trade; the Editor re-read Kitco at press time and the reading matched the 05:00 tape exactly, so the tape stands unamended.",
  "s":"Kitco / Brisk Markets / CNBC / Trading Economics"},
 {"d":"gold-metals","h":"Gold added $26.80 after the morning mark while platinum gave back $29.00",
  "t":"Carat Capital marked four metals from Kitco spot at 5:58am New York on 7 August, an hour and a half before the payrolls release. Measured against Kitco's 5:00pm close the same day, gold rose a further $26.80 from $4,314.50 to $4,341.30, while silver fell $0.83 from $64.29 to $63.46, platinum fell $29.00 from $1,772.00 to $1,743.00 and palladium fell $25.00 from $1,382.00 to $1,357.00. In session-percentage terms platinum was up 3.14% at the morning mark and closed up 1.46%, surrendering more than half its gain; palladium was up 2.14% and closed up 0.30%; silver was up 4.71% and closed up 3.36%; gold alone improved, from 1.77% to 2.41%. The gold to silver ratio stood at 69.04 on Thursday's close, tightened to 67.11 at the Friday morning mark and widened back to 68.41 at the close. Platinum stood at 41.1% of the gold price in the morning and 40.15% at the close. Measured against this paper's marks of 5 August, the three-session move is gold +$183.00 or +4.40%, silver +$2.16 or +3.52%, palladium +$7.00 or +0.52% and platinum +$2.00 or +0.11%. Both readings are from the same source at two stated times and both were correct when taken.",
  "s":"Kitco / Carat Capital tape, 5-7 August 2026"},
 {"d":"auctions","h":"Bonhams sets three Chanel sales for September across New York, Paris and London",
  "t":"Bonhams announced on 7 August 2026 a three-city Chanel auction series for September. New York holds Chanel: From the Vault II from 7 to 17 September, led by a gold-tone bird cage minaudière from Virginie Viard's Métiers d'Art Paris-31 rue Cambon collection, set with simulated turquoise and multicoloured crystals, estimated at $20,000 to $30,000; highlights go on view at the house's Manhattan flagship from 17 August. Paris holds Chanel: From the Vault II Paris Edition from 14 to 24 September with roughly 400 lots spanning Karl Lagerfeld's 1990s work to Viard's recent collections, led by a white tweed jacket from the autumn/winter 2025 ready-to-wear collection at €2,000 to €3,000, about $2,300 to $3,460, and including a Lagerfeld-era brooch with rhinestones and turquoise-coloured paste at €700 to €900, about $810 to $1,040. London holds Designer Handbags and Fashion from 21 September to 1 October and carries the heaviest jewellery weighting, with a private collection of Chanel costume pieces from the 1960s to the 1990s led by a filigree snake bangle made by Robert Goossens for Chanel Haute Couture circa 1960, estimated at $13,000 to $20,000, against a pair of Chanel Fine Jewelry Comète Géode earrings from 2024 in 18-carat white gold and diamonds estimated at £2,000 to £3,000, about $2,690 to $4,040. The signed costume bangle therefore carries roughly five times the estimate of the current-production gold and diamond earrings from the same maison, which prices attribution and documentation rather than materials. This is the first substantial auction-house announcement this desk has been able to file in three editions.",
  "s":"JCK / WWD / Bonhams"},
 {"d":"retail-tech","h":"HKTDC survey of 1,507 puts diamond first on demand and fashion jewellery first on growth",
  "t":"The Hong Kong Trade Development Council surveyed 1,507 buyers and exhibitors at its twin fairs, the Hong Kong International Jewellery Show and the Hong Kong International Diamond, Gem and Pearl Show, which ran together from 29 July to 2 August 2026 at the Hong Kong Convention and Exhibition Centre. On the most-in-demand stone, 29% named diamond, 25% ruby and 20% pearl. On growth potential by segment, 57% named trendy fashion jewellery, 35% precious jewellery and 21% designer jewellery. Yellow gold was named the most popular precious metal by 40% of respondents. Respondents described themselves as cautious about 2026 and said they expect one to two years before confidence is fully restored. Hong Kong's own 2025 trade data provides the base: exports of fine jewellery rose 5%, driven by precious metal prices rather than units; exports of pearls, gemstones and rough diamonds fell 8%; exports of imitation jewellery fell 26%. The twenty-eight-point gap between the fashion jewellery and precious jewellery answers on growth is the widest signal in the survey and sits against a week in which gold closed at $4,341.30 an ounce, $139.58 a gram. Related context previously filed by this paper: China Gold Association half-year figures showing Chinese gold jewellery consumption down 33.88% by weight while bar and coin demand rose 28.42% (7 August).",
  "s":"HKTDC via Rapaport / HKTDC Media Room"},
 {"d":"retail-tech","h":"US jewellery value rose 8.6% in the first half on a unit count that fell about 9%",
  "t":"Figures from the analytics firm Tenoris, reported by JCK on 5 August 2026, put United States jewellery sales up 8.6% across the first half of 2026 while the average purchase price rose 19% and unit sales declined. June alone rose 13% year on year. Sales of items priced below $1,500 continued to decline. The implied unit change, derived by this desk from the published value and average-price figures rather than published as such, is a fall of roughly 9%. The composition reflects a spending distribution rather than a jewellery-specific trend: The New York Times has the top 10% of American households accounting for nearly half of all consumer spending, and a discretionary category inherits that shape. De Beers chief executive Al Cook, speaking at the JCK show, said larger and higher-quality diamonds are growing in value and desire. The same mechanism appears in three company results previously filed by this paper: Brilliant Earth's second quarter, revenue up 6% on total orders down 2.1% with average order value up 8% to $2,238 (7 August); Richemont's quarter to 30 June, jewellery up 24% within total sales up 20% and a seventh consecutive quarter of double-digit jewellery growth (15 July); and Luk Fook's record profit taken from fixed-price design rather than gram weight (5 August). The Knot separately reports six of ten brides in 2025 chose lab-grown centre stones.",
  "s":"Tenoris via JCK / New York Times / company results"},
 {"d":"retail-tech","h":"NY Now closes its first show under Rockview with buyers up 5% and 96% rebooked",
  "t":"NY Now's summer market ran from 2 to 4 August 2026 at the Jacob K. Javits Center in New York with 460 exhibitors, more than 70 of them new to the show or returning after an absence, across its Gift and Lifestyle, Jewelry and Accessories, and Home sections. Buyer attendance rose 5% on the previous summer edition. Organisers report a 96% renewal rate for the winter 2027 market and say 107 prospective exhibitors walked the summer floor to assess taking space. It was the first edition under Rockview Management Group, which acquired NY Now and JA New York from Emerald before that company's own acquisition by Apollo, and which has placed the industry veteran Dorothy Belshaw in charge. The winter 2027 market is scheduled for 31 January to 2 February 2027. Neither the attendance rise nor the renewal rate is broken out by section, so the jewellery-specific read is limited: NY Now is a gift and home market with a jewellery and accessories hall inside it rather than a jewellery fair. This paper filed the show's opening on 2 August. Separately and not filed as an article: Etsy is cutting 220 jobs, 12% of its workforce, in product and engineering, with second-quarter sales up 6% and first-half revenue up 5%; no jewellery-seller-specific impact has been reported and it is carried here as context only.",
  "s":"Gifts & Decorative Accessories / National Jeweler / NY NOW"},
]
wk["entries"] = newent + wk["entries"]
record["updated"] = "8 Aug 2026"
(C/"record.json").write_text(json.dumps(record,ensure_ascii=False,indent=1))
print("wire No.029 written;", len(newent), "record entries prepended into", wk["label"], "- week now", len(wk["entries"]))
